// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.1 (64-bit)
// Version: 2021.1
// Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module resize_accel_resizeNNBilinear_0_2160_3840_1_1080_1920_1_2_Pipeline_VITIS_LOOP_389_5 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        in_mat_420_dout,
        in_mat_420_empty_n,
        in_mat_420_read,
        out_mat_421_din,
        out_mat_421_full_n,
        out_mat_421_write,
        read_pixel,
        indexy_V,
        nextYScale_V,
        ret_V_17,
        loop_col_count,
        cmp273,
        line_buffer_V_0_0_address0,
        line_buffer_V_0_0_ce0,
        line_buffer_V_0_0_we0,
        line_buffer_V_0_0_d0,
        line_buffer_V_0_0_q0,
        line_buffer_V_0_0_address1,
        line_buffer_V_0_0_ce1,
        line_buffer_V_0_0_q1,
        line_buffer_V_1_0_address0,
        line_buffer_V_1_0_ce0,
        line_buffer_V_1_0_we0,
        line_buffer_V_1_0_d0,
        line_buffer_V_1_0_q0,
        line_buffer_V_1_0_address1,
        line_buffer_V_1_0_ce1,
        line_buffer_V_1_0_q1,
        tmp_V,
        first_row_index_5,
        trunc_ln3,
        indexy_pre_V,
        add_i_i_i_i_i199_i,
        ret_V_3_cast,
        p_Result_s,
        indexy_pre_V_cast,
        shl_i_i_i_i_i,
        indexx_pre_V_1,
        cmp89,
        p_read1,
        icmp_ln1061_1,
        op2_assign_2,
        op2_assign,
        cmp277,
        p_read3,
        read_pixel_1_out,
        read_pixel_1_out_ap_vld,
        indexy_V_1_out,
        indexy_V_1_out_ap_vld,
        nextYScale_V_1_out,
        nextYScale_V_1_out_ap_vld,
        ap_ext_blocking_n,
        ap_str_blocking_n,
        ap_int_blocking_n,
        grp_scaleCompute_17_42_20_48_16_1_s_fu_195_p_din1,
        grp_scaleCompute_17_42_20_48_16_1_s_fu_195_p_din2,
        grp_scaleCompute_17_42_20_48_16_1_s_fu_195_p_dout0,
        grp_scaleCompute_17_42_20_48_16_1_s_fu_195_p_ce
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [7:0] in_mat_420_dout;
input   in_mat_420_empty_n;
output   in_mat_420_read;
output  [7:0] out_mat_421_din;
input   out_mat_421_full_n;
output   out_mat_421_write;
input  [7:0] read_pixel;
input  [16:0] indexy_V;
input  [16:0] nextYScale_V;
input  [16:0] ret_V_17;
input  [31:0] loop_col_count;
input  [0:0] cmp273;
output  [11:0] line_buffer_V_0_0_address0;
output   line_buffer_V_0_0_ce0;
output   line_buffer_V_0_0_we0;
output  [7:0] line_buffer_V_0_0_d0;
input  [7:0] line_buffer_V_0_0_q0;
output  [11:0] line_buffer_V_0_0_address1;
output   line_buffer_V_0_0_ce1;
input  [7:0] line_buffer_V_0_0_q1;
output  [11:0] line_buffer_V_1_0_address0;
output   line_buffer_V_1_0_ce0;
output   line_buffer_V_1_0_we0;
output  [7:0] line_buffer_V_1_0_d0;
input  [7:0] line_buffer_V_1_0_q0;
output  [11:0] line_buffer_V_1_0_address1;
output   line_buffer_V_1_0_ce1;
input  [7:0] line_buffer_V_1_0_q1;
input  [31:0] tmp_V;
input  [31:0] first_row_index_5;
input  [47:0] trunc_ln3;
input  [21:0] indexy_pre_V;
input  [16:0] add_i_i_i_i_i199_i;
input  [16:0] ret_V_3_cast;
input   p_Result_s;
input  [23:0] indexy_pre_V_cast;
input  [53:0] shl_i_i_i_i_i;
input  [41:0] indexx_pre_V_1;
input  [0:0] cmp89;
input  [31:0] p_read1;
input  [0:0] icmp_ln1061_1;
input  [31:0] op2_assign_2;
input  [31:0] op2_assign;
input  [0:0] cmp277;
input  [31:0] p_read3;
output  [7:0] read_pixel_1_out;
output   read_pixel_1_out_ap_vld;
output  [16:0] indexy_V_1_out;
output   indexy_V_1_out_ap_vld;
output  [16:0] nextYScale_V_1_out;
output   nextYScale_V_1_out_ap_vld;
output   ap_ext_blocking_n;
output   ap_str_blocking_n;
output   ap_int_blocking_n;
output  [31:0] grp_scaleCompute_17_42_20_48_16_1_s_fu_195_p_din1;
output  [47:0] grp_scaleCompute_17_42_20_48_16_1_s_fu_195_p_din2;
input  [41:0] grp_scaleCompute_17_42_20_48_16_1_s_fu_195_p_dout0;
output   grp_scaleCompute_17_42_20_48_16_1_s_fu_195_p_ce;

reg ap_idle;
reg in_mat_420_read;
reg out_mat_421_write;
reg[11:0] line_buffer_V_0_0_address0;
reg line_buffer_V_0_0_ce0;
reg line_buffer_V_0_0_we0;
reg[11:0] line_buffer_V_0_0_address1;
reg line_buffer_V_0_0_ce1;
reg[11:0] line_buffer_V_1_0_address0;
reg line_buffer_V_1_0_ce0;
reg line_buffer_V_1_0_we0;
reg[11:0] line_buffer_V_1_0_address1;
reg line_buffer_V_1_0_ce1;
reg read_pixel_1_out_ap_vld;
reg indexy_V_1_out_ap_vld;
reg nextYScale_V_1_out_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_enable_reg_pp0_iter9;
reg    ap_enable_reg_pp0_iter10;
reg    ap_enable_reg_pp0_iter11;
reg    ap_enable_reg_pp0_iter12;
reg    ap_enable_reg_pp0_iter13;
reg    ap_enable_reg_pp0_iter14;
reg    ap_enable_reg_pp0_iter15;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_state4_pp0_stage0_iter3;
wire    ap_block_state5_pp0_stage0_iter4;
reg   [0:0] icmp_ln389_reg_1222;
reg   [0:0] icmp_ln389_reg_1222_pp0_iter4_reg;
reg   [0:0] and_ln406_reg_1231;
reg   [0:0] and_ln406_reg_1231_pp0_iter4_reg;
reg    ap_predicate_op97_read_state6;
reg    ap_block_state6_pp0_stage0_iter5;
wire    ap_block_state7_pp0_stage0_iter6;
wire    ap_block_state8_pp0_stage0_iter7;
wire    ap_block_state9_pp0_stage0_iter8;
wire    ap_block_state10_pp0_stage0_iter9;
wire    ap_block_state11_pp0_stage0_iter10;
wire    ap_block_state12_pp0_stage0_iter11;
wire    ap_block_state13_pp0_stage0_iter12;
wire    ap_block_state14_pp0_stage0_iter13;
wire    ap_block_state15_pp0_stage0_iter14;
reg   [0:0] and_ln487_reg_1241;
reg   [0:0] and_ln487_reg_1241_pp0_iter14_reg;
reg   [0:0] icmp_ln489_reg_1245;
reg   [0:0] icmp_ln489_reg_1245_pp0_iter14_reg;
reg   [0:0] and_ln486_reg_1249;
reg   [0:0] and_ln486_reg_1249_pp0_iter14_reg;
reg    ap_predicate_op237_write_state16;
reg    ap_block_state16_pp0_stage0_iter15;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln389_fu_633_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    in_mat_420_blk_n;
wire    ap_block_pp0_stage0;
reg    out_mat_421_blk_n;
reg   [7:0] reg_570;
reg    ap_block_pp0_stage0_11001;
reg   [0:0] icmp_ln389_reg_1222_pp0_iter6_reg;
wire   [31:0] first_row_index_5_read_reg_1203;
reg   [0:0] icmp_ln1049_reg_1235;
reg   [0:0] icmp_ln1049_reg_1235_pp0_iter6_reg;
wire   [7:0] line_buffer_V_2_0_q0;
reg   [7:0] reg_576;
reg   [7:0] reg_582;
reg   [0:0] icmp_ln389_reg_1222_pp0_iter7_reg;
reg   [0:0] icmp_ln1049_reg_1235_pp0_iter7_reg;
wire   [7:0] line_buffer_V_2_0_q1;
wire   [0:0] cmp89_read_read_fu_220_p2;
wire   [0:0] cmp273_read_read_fu_286_p2;
reg   [30:0] j_1_reg_1216;
reg   [30:0] j_1_reg_1216_pp0_iter1_reg;
reg   [30:0] j_1_reg_1216_pp0_iter2_reg;
reg   [30:0] j_1_reg_1216_pp0_iter3_reg;
reg   [30:0] j_1_reg_1216_pp0_iter4_reg;
reg   [30:0] j_1_reg_1216_pp0_iter5_reg;
reg   [0:0] icmp_ln389_reg_1222_pp0_iter1_reg;
reg   [0:0] icmp_ln389_reg_1222_pp0_iter2_reg;
reg   [0:0] icmp_ln389_reg_1222_pp0_iter3_reg;
reg   [0:0] icmp_ln389_reg_1222_pp0_iter5_reg;
reg   [0:0] icmp_ln389_reg_1222_pp0_iter8_reg;
reg   [0:0] icmp_ln389_reg_1222_pp0_iter9_reg;
reg   [0:0] icmp_ln389_reg_1222_pp0_iter10_reg;
reg   [0:0] icmp_ln389_reg_1222_pp0_iter11_reg;
reg   [0:0] icmp_ln389_reg_1222_pp0_iter12_reg;
reg   [0:0] icmp_ln389_reg_1222_pp0_iter13_reg;
wire   [1:0] trunc_ln737_fu_667_p1;
reg   [1:0] trunc_ln737_reg_1226;
reg   [1:0] trunc_ln737_reg_1226_pp0_iter1_reg;
reg   [1:0] trunc_ln737_reg_1226_pp0_iter2_reg;
reg   [1:0] trunc_ln737_reg_1226_pp0_iter3_reg;
reg   [1:0] trunc_ln737_reg_1226_pp0_iter4_reg;
reg   [1:0] trunc_ln737_reg_1226_pp0_iter5_reg;
reg   [1:0] trunc_ln737_reg_1226_pp0_iter6_reg;
reg   [1:0] trunc_ln737_reg_1226_pp0_iter7_reg;
wire   [0:0] and_ln406_fu_677_p2;
reg   [0:0] and_ln406_reg_1231_pp0_iter1_reg;
reg   [0:0] and_ln406_reg_1231_pp0_iter2_reg;
reg   [0:0] and_ln406_reg_1231_pp0_iter3_reg;
wire   [0:0] icmp_ln1049_fu_687_p2;
reg   [0:0] icmp_ln1049_reg_1235_pp0_iter1_reg;
reg   [0:0] icmp_ln1049_reg_1235_pp0_iter2_reg;
reg   [0:0] icmp_ln1049_reg_1235_pp0_iter3_reg;
reg   [0:0] icmp_ln1049_reg_1235_pp0_iter4_reg;
reg   [0:0] icmp_ln1049_reg_1235_pp0_iter5_reg;
reg   [0:0] icmp_ln1049_reg_1235_pp0_iter8_reg;
wire   [0:0] and_ln487_fu_693_p2;
reg   [0:0] and_ln487_reg_1241_pp0_iter1_reg;
reg   [0:0] and_ln487_reg_1241_pp0_iter2_reg;
reg   [0:0] and_ln487_reg_1241_pp0_iter3_reg;
reg   [0:0] and_ln487_reg_1241_pp0_iter4_reg;
reg   [0:0] and_ln487_reg_1241_pp0_iter5_reg;
reg   [0:0] and_ln487_reg_1241_pp0_iter6_reg;
reg   [0:0] and_ln487_reg_1241_pp0_iter7_reg;
reg   [0:0] and_ln487_reg_1241_pp0_iter8_reg;
reg   [0:0] and_ln487_reg_1241_pp0_iter9_reg;
reg   [0:0] and_ln487_reg_1241_pp0_iter10_reg;
reg   [0:0] and_ln487_reg_1241_pp0_iter11_reg;
reg   [0:0] and_ln487_reg_1241_pp0_iter12_reg;
reg   [0:0] and_ln487_reg_1241_pp0_iter13_reg;
wire   [0:0] icmp_ln489_fu_699_p2;
reg   [0:0] icmp_ln489_reg_1245_pp0_iter1_reg;
reg   [0:0] icmp_ln489_reg_1245_pp0_iter2_reg;
reg   [0:0] icmp_ln489_reg_1245_pp0_iter3_reg;
reg   [0:0] icmp_ln489_reg_1245_pp0_iter4_reg;
reg   [0:0] icmp_ln489_reg_1245_pp0_iter5_reg;
reg   [0:0] icmp_ln489_reg_1245_pp0_iter6_reg;
reg   [0:0] icmp_ln489_reg_1245_pp0_iter7_reg;
reg   [0:0] icmp_ln489_reg_1245_pp0_iter8_reg;
reg   [0:0] icmp_ln489_reg_1245_pp0_iter9_reg;
reg   [0:0] icmp_ln489_reg_1245_pp0_iter10_reg;
reg   [0:0] icmp_ln489_reg_1245_pp0_iter11_reg;
reg   [0:0] icmp_ln489_reg_1245_pp0_iter12_reg;
reg   [0:0] icmp_ln489_reg_1245_pp0_iter13_reg;
wire   [0:0] and_ln486_fu_711_p2;
reg   [0:0] and_ln486_reg_1249_pp0_iter1_reg;
reg   [0:0] and_ln486_reg_1249_pp0_iter2_reg;
reg   [0:0] and_ln486_reg_1249_pp0_iter3_reg;
reg   [0:0] and_ln486_reg_1249_pp0_iter4_reg;
reg   [0:0] and_ln486_reg_1249_pp0_iter5_reg;
reg   [0:0] and_ln486_reg_1249_pp0_iter6_reg;
reg   [0:0] and_ln486_reg_1249_pp0_iter7_reg;
reg   [0:0] and_ln486_reg_1249_pp0_iter8_reg;
reg   [0:0] and_ln486_reg_1249_pp0_iter9_reg;
reg   [0:0] and_ln486_reg_1249_pp0_iter10_reg;
reg   [0:0] and_ln486_reg_1249_pp0_iter11_reg;
reg   [0:0] and_ln486_reg_1249_pp0_iter12_reg;
reg   [0:0] and_ln486_reg_1249_pp0_iter13_reg;
wire   [31:0] zext_ln395_fu_735_p1;
wire   [41:0] indexx_pre_V_fu_764_p3;
reg   [41:0] indexx_pre_V_reg_1258;
reg   [16:0] trunc_ln_reg_1263;
wire   [21:0] trunc_ln902_fu_782_p1;
reg   [21:0] trunc_ln902_reg_1270;
wire   [23:0] trunc_ln712_fu_786_p1;
reg   [23:0] trunc_ln712_reg_1275;
wire   [11:0] idx_nxt_fu_866_p2;
reg   [11:0] idx_nxt_reg_1280;
wire   [11:0] line_buffer_V_1_0_addr_gep_fu_402_p3;
wire   [11:0] line_buffer_V_2_0_addr_gep_fu_417_p3;
wire   [11:0] line_buffer_V_0_0_addr_gep_fu_424_p3;
reg   [11:0] Wx_V_reg_1315;
reg   [11:0] Wx_V_reg_1315_pp0_iter7_reg;
reg   [11:0] Wx_V_reg_1315_pp0_iter8_reg;
reg   [11:0] Wx_V_reg_1315_pp0_iter9_reg;
wire   [11:0] line_buffer_V_1_0_addr_1_gep_fu_475_p3;
wire   [11:0] line_buffer_V_2_0_addr_1_gep_fu_483_p3;
wire   [11:0] line_buffer_V_0_0_addr_1_gep_fu_490_p3;
wire   [11:0] Wy_V_fu_913_p4;
reg   [11:0] Wy_V_reg_1351;
wire   [7:0] p_Result_8_fu_930_p3;
reg   [7:0] p_Result_8_reg_1366;
reg   [7:0] p_Result_8_reg_1366_pp0_iter10_reg;
reg   [7:0] p_Result_8_reg_1366_pp0_iter11_reg;
reg   [7:0] p_Result_8_reg_1366_pp0_iter12_reg;
reg   [7:0] p_Result_8_reg_1366_pp0_iter13_reg;
wire   [9:0] ret_9_fu_980_p2;
reg   [9:0] ret_9_reg_1371;
reg  signed [9:0] ret_9_reg_1371_pp0_iter10_reg;
wire   [8:0] ret_10_fu_992_p2;
reg  signed [8:0] ret_10_reg_1376;
wire   [7:0] ret_V_13_fu_1095_p3;
reg   [7:0] ret_V_13_reg_1421;
reg   [11:0] line_buffer_V_2_0_address0;
reg    line_buffer_V_2_0_ce0;
reg    line_buffer_V_2_0_we0;
reg   [11:0] line_buffer_V_2_0_address1;
reg    line_buffer_V_2_0_ce1;
reg    grp_scaleCompute_17_42_20_48_16_1_s_fu_558_ap_ce;
wire    grp_scaleCompute_17_42_20_48_16_1_s_fu_558_ap_ext_blocking_n;
wire    grp_scaleCompute_17_42_20_48_16_1_s_fu_558_ap_str_blocking_n;
wire    grp_scaleCompute_17_42_20_48_16_1_s_fu_558_ap_int_blocking_n;
wire    ap_block_state1_pp0_stage0_iter0_ignore_call6;
wire    ap_block_state2_pp0_stage0_iter1_ignore_call6;
wire    ap_block_state3_pp0_stage0_iter2_ignore_call6;
wire    ap_block_state4_pp0_stage0_iter3_ignore_call6;
wire    ap_block_state5_pp0_stage0_iter4_ignore_call6;
reg    ap_block_state6_pp0_stage0_iter5_ignore_call6;
wire    ap_block_state7_pp0_stage0_iter6_ignore_call6;
wire    ap_block_state8_pp0_stage0_iter7_ignore_call6;
wire    ap_block_state9_pp0_stage0_iter8_ignore_call6;
wire    ap_block_state10_pp0_stage0_iter9_ignore_call6;
wire    ap_block_state11_pp0_stage0_iter10_ignore_call6;
wire    ap_block_state12_pp0_stage0_iter11_ignore_call6;
wire    ap_block_state13_pp0_stage0_iter12_ignore_call6;
wire    ap_block_state14_pp0_stage0_iter13_ignore_call6;
wire    ap_block_state15_pp0_stage0_iter14_ignore_call6;
reg    ap_block_state16_pp0_stage0_iter15_ignore_call6;
reg    ap_block_pp0_stage0_11001_ignoreCallOp84;
wire   [0:0] ap_phi_mux_flag_write_phi_fu_503_p6;
wire   [0:0] ap_phi_reg_pp0_iter0_flag_write_reg_498;
reg   [0:0] ap_phi_reg_pp0_iter1_flag_write_reg_498;
reg   [0:0] ap_phi_reg_pp0_iter2_flag_write_reg_498;
reg   [0:0] ap_phi_reg_pp0_iter3_flag_write_reg_498;
reg   [0:0] ap_phi_reg_pp0_iter4_flag_write_reg_498;
reg   [0:0] ap_phi_reg_pp0_iter5_flag_write_reg_498;
reg   [0:0] ap_phi_reg_pp0_iter6_flag_write_reg_498;
wire   [7:0] ap_phi_reg_pp0_iter0_p_Val2_3_reg_514;
reg   [7:0] ap_phi_reg_pp0_iter1_p_Val2_3_reg_514;
reg   [7:0] ap_phi_reg_pp0_iter2_p_Val2_3_reg_514;
reg   [7:0] ap_phi_reg_pp0_iter3_p_Val2_3_reg_514;
reg   [7:0] ap_phi_reg_pp0_iter4_p_Val2_3_reg_514;
reg   [7:0] ap_phi_reg_pp0_iter5_p_Val2_3_reg_514;
reg   [7:0] ap_phi_reg_pp0_iter6_p_Val2_3_reg_514;
reg   [7:0] ap_phi_reg_pp0_iter7_p_Val2_3_reg_514;
reg   [7:0] ap_phi_reg_pp0_iter8_p_Val2_3_reg_514;
reg   [7:0] ap_phi_reg_pp0_iter9_p_Val2_3_reg_514;
wire   [7:0] ap_phi_reg_pp0_iter0_p_Val2_s_reg_525;
reg   [7:0] ap_phi_reg_pp0_iter1_p_Val2_s_reg_525;
reg   [7:0] ap_phi_reg_pp0_iter2_p_Val2_s_reg_525;
reg   [7:0] ap_phi_reg_pp0_iter3_p_Val2_s_reg_525;
reg   [7:0] ap_phi_reg_pp0_iter4_p_Val2_s_reg_525;
reg   [7:0] ap_phi_reg_pp0_iter5_p_Val2_s_reg_525;
reg   [7:0] ap_phi_reg_pp0_iter6_p_Val2_s_reg_525;
reg   [7:0] ap_phi_reg_pp0_iter7_p_Val2_s_reg_525;
reg   [7:0] ap_phi_reg_pp0_iter8_p_Val2_s_reg_525;
reg   [7:0] ap_phi_reg_pp0_iter9_p_Val2_s_reg_525;
wire   [7:0] ap_phi_reg_pp0_iter0_arrayidx18117515_load_065_reg_536;
reg   [7:0] ap_phi_reg_pp0_iter1_arrayidx18117515_load_065_reg_536;
reg   [7:0] ap_phi_reg_pp0_iter2_arrayidx18117515_load_065_reg_536;
reg   [7:0] ap_phi_reg_pp0_iter3_arrayidx18117515_load_065_reg_536;
reg   [7:0] ap_phi_reg_pp0_iter4_arrayidx18117515_load_065_reg_536;
reg   [7:0] ap_phi_reg_pp0_iter5_arrayidx18117515_load_065_reg_536;
reg   [7:0] ap_phi_reg_pp0_iter6_arrayidx18117515_load_065_reg_536;
reg   [7:0] ap_phi_reg_pp0_iter7_arrayidx18117515_load_065_reg_536;
reg   [7:0] ap_phi_reg_pp0_iter8_arrayidx18117515_load_065_reg_536;
reg   [7:0] ap_phi_reg_pp0_iter9_arrayidx18117515_load_065_reg_536;
wire   [7:0] ap_phi_reg_pp0_iter0_arrayidx17315516_load_061_reg_547;
reg   [7:0] ap_phi_reg_pp0_iter1_arrayidx17315516_load_061_reg_547;
reg   [7:0] ap_phi_reg_pp0_iter2_arrayidx17315516_load_061_reg_547;
reg   [7:0] ap_phi_reg_pp0_iter3_arrayidx17315516_load_061_reg_547;
reg   [7:0] ap_phi_reg_pp0_iter4_arrayidx17315516_load_061_reg_547;
reg   [7:0] ap_phi_reg_pp0_iter5_arrayidx17315516_load_061_reg_547;
reg   [7:0] ap_phi_reg_pp0_iter6_arrayidx17315516_load_061_reg_547;
reg   [7:0] ap_phi_reg_pp0_iter7_arrayidx17315516_load_061_reg_547;
reg   [7:0] ap_phi_reg_pp0_iter8_arrayidx17315516_load_061_reg_547;
reg   [7:0] ap_phi_reg_pp0_iter9_arrayidx17315516_load_061_reg_547;
wire   [63:0] zext_ln430_fu_872_p1;
wire   [63:0] zext_ln389_fu_795_p1;
wire   [63:0] zext_ln431_fu_892_p1;
reg   [16:0] nextYScale_V_1_fu_164;
wire    ap_loop_init;
reg   [16:0] tmp_fu_168;
wire   [16:0] ret_V_11_fu_659_p3;
reg   [30:0] j_fu_172;
reg   [30:0] ap_sig_allocacmp_j_1;
wire   [30:0] add_ln389_fu_639_p2;
reg   [7:0] read_pixel_1_fu_176;
wire   [0:0] p_Result_read_read_fu_244_p2;
reg    ap_block_pp0_stage0_01001;
wire   [31:0] zext_ln389_1_fu_629_p1;
wire   [0:0] icmp_ln902_fu_645_p2;
wire   [0:0] ret_V_11_fu_659_p0;
wire   [16:0] select_ln901_fu_651_p3;
wire   [0:0] icmp_ln408_fu_671_p2;
wire   [31:0] zext_ln1049_fu_683_p1;
wire   [0:0] icmp_ln1049_1_fu_705_p2;
wire   [19:0] trunc_ln395_fu_732_p1;
wire  signed [41:0] sext_ln1548_fu_740_p0;
wire  signed [41:0] tmp_2_fu_744_p1;
wire  signed [53:0] sext_ln1548_fu_740_p1;
wire   [0:0] icmp_ln1547_fu_752_p2;
wire  signed [41:0] indexx_pre_V_3_fu_757_p2;
wire   [0:0] tmp_2_fu_744_p3;
wire   [41:0] indexx_pre_V_3_fu_757_p3;
wire   [0:0] icmp_ln902_1_fu_808_p2;
wire   [16:0] ret_V_4_fu_813_p2;
wire   [0:0] p_Result_1_fu_801_p3;
wire   [16:0] select_ln901_1_fu_818_p3;
wire   [16:0] idx_1_fu_825_p3;
wire   [1:0] trunc_ln737_1_fu_832_p1;
wire   [23:0] rhs_1_fu_836_p3;
wire   [31:0] idx_fu_849_p1;
wire   [0:0] not_cmp_i_i173_fu_857_p2;
wire   [11:0] empty_fu_853_p1;
wire   [11:0] zext_ln428_fu_862_p1;
wire   [23:0] ret_V_6_fu_844_p2;
wire   [23:0] rhs_fu_901_p3;
wire   [23:0] ret_V_fu_908_p2;
wire   [8:0] zext_ln225_1_fu_948_p1;
wire   [8:0] zext_ln225_fu_944_p1;
wire   [7:0] p_Result_9_fu_937_p3;
wire   [8:0] zext_ln225_3_fu_962_p1;
wire   [8:0] zext_ln225_2_fu_958_p1;
wire   [8:0] ret_fu_952_p2;
wire   [8:0] ret_8_fu_966_p2;
wire   [9:0] zext_ln225_4_fu_972_p1;
wire   [9:0] zext_ln225_5_fu_976_p1;
wire  signed [8:0] ret_6_fu_986_p2;
wire   [23:0] Wxy_V_fu_1011_p1;
wire  signed [23:0] grp_fu_1115_p2;
wire   [11:0] Wxy_V_fu_1011_p4;
wire  signed [20:0] grp_fu_1122_p2;
wire  signed [21:0] grp_fu_1129_p3;
wire  signed [22:0] grp_fu_1138_p3;
wire   [17:0] P4_V_fu_1033_p3;
wire  signed [23:0] sext_ln1245_3_fu_1040_p1;
wire   [23:0] zext_ln1245_fu_1043_p1;
wire   [23:0] ret_V_8_fu_1047_p2;
wire   [9:0] trunc_ln902_1_fu_1071_p1;
wire   [7:0] trunc_ln882_1_fu_1053_p4;
wire   [0:0] icmp_ln902_2_fu_1075_p2;
wire   [7:0] ret_V_9_fu_1081_p2;
wire   [0:0] p_Result_6_fu_1063_p3;
wire   [7:0] select_ln901_3_fu_1087_p3;
wire   [11:0] grp_fu_1115_p0;
wire   [11:0] grp_fu_1115_p1;
wire   [11:0] grp_fu_1122_p0;
wire   [11:0] grp_fu_1129_p0;
wire   [11:0] grp_fu_1138_p0;
reg    grp_fu_1115_ce;
reg    grp_fu_1122_ce;
reg    grp_fu_1129_ce;
reg    grp_fu_1138_ce;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg    ap_loop_exit_ready_pp0_iter7_reg;
reg    ap_loop_exit_ready_pp0_iter8_reg;
reg    ap_loop_exit_ready_pp0_iter9_reg;
reg    ap_loop_exit_ready_pp0_iter10_reg;
reg    ap_loop_exit_ready_pp0_iter11_reg;
reg    ap_loop_exit_ready_pp0_iter12_reg;
reg    ap_loop_exit_ready_pp0_iter13_reg;
reg    ap_loop_exit_ready_pp0_iter14_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_int_blocking_cur_n;
reg    ap_ext_blocking_sub_n;
reg    ap_wait_0;
reg    ap_sub_ext_blocking_0;
reg    ap_str_blocking_sub_n;
reg    ap_sub_str_blocking_0;
reg    ap_int_blocking_sub_n;
reg    ap_sub_int_blocking_0;
wire    ap_enable_pp0;
wire    ap_start_int;
wire   [23:0] grp_fu_1115_p00;
wire   [23:0] grp_fu_1115_p10;
wire   [20:0] grp_fu_1122_p00;
wire   [20:0] grp_fu_1129_p00;
wire   [21:0] grp_fu_1138_p00;
reg    ap_condition_91;
reg    ap_condition_303;
reg    ap_condition_587;
reg    ap_condition_595;
reg    ap_condition_1480;
reg    ap_condition_579;
reg    ap_condition_901;
reg    ap_condition_596;
reg    ap_condition_1492;
reg    ap_condition_1495;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 ap_enable_reg_pp0_iter10 = 1'b0;
#0 ap_enable_reg_pp0_iter11 = 1'b0;
#0 ap_enable_reg_pp0_iter12 = 1'b0;
#0 ap_enable_reg_pp0_iter13 = 1'b0;
#0 ap_enable_reg_pp0_iter14 = 1'b0;
#0 ap_enable_reg_pp0_iter15 = 1'b0;
#0 ap_done_reg = 1'b0;
end

resize_accel_resizeNNBilinear_0_2160_3840_1_1080_1920_1_2_Pipeline_VITIS_LOOP_389_5_line_bbkb #(
    .DataWidth( 8 ),
    .AddressRange( 3840 ),
    .AddressWidth( 12 ))
line_buffer_V_2_0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(line_buffer_V_2_0_address0),
    .ce0(line_buffer_V_2_0_ce0),
    .we0(line_buffer_V_2_0_we0),
    .d0(read_pixel_1_fu_176),
    .q0(line_buffer_V_2_0_q0),
    .address1(line_buffer_V_2_0_address1),
    .ce1(line_buffer_V_2_0_ce1),
    .q1(line_buffer_V_2_0_q1)
);

resize_accel_mul_mul_12ns_12ns_24_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 12 ),
    .din1_WIDTH( 12 ),
    .dout_WIDTH( 24 ))
mul_mul_12ns_12ns_24_4_1_U78(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_1115_p0),
    .din1(grp_fu_1115_p1),
    .ce(grp_fu_1115_ce),
    .dout(grp_fu_1115_p2)
);

resize_accel_mul_mul_12ns_9s_21_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 12 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 21 ))
mul_mul_12ns_9s_21_4_1_U79(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_1122_p0),
    .din1(ret_6_fu_986_p2),
    .ce(grp_fu_1122_ce),
    .dout(grp_fu_1122_p2)
);

resize_accel_mac_muladd_12ns_9s_21s_22_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 12 ),
    .din1_WIDTH( 9 ),
    .din2_WIDTH( 21 ),
    .dout_WIDTH( 22 ))
mac_muladd_12ns_9s_21s_22_4_1_U80(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_1129_p0),
    .din1(ret_10_reg_1376),
    .din2(grp_fu_1122_p2),
    .ce(grp_fu_1129_ce),
    .dout(grp_fu_1129_p3)
);

resize_accel_mac_muladd_12ns_10s_22s_23_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 12 ),
    .din1_WIDTH( 10 ),
    .din2_WIDTH( 22 ),
    .dout_WIDTH( 23 ))
mac_muladd_12ns_10s_22s_23_4_1_U81(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_1138_p0),
    .din1(ret_9_reg_1371_pp0_iter10_reg),
    .din2(grp_fu_1129_p3),
    .ce(grp_fu_1138_ce),
    .dout(grp_fu_1138_p3)
);

resize_accel_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter14_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter10 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter11 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter12 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter12 <= ap_enable_reg_pp0_iter11;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter13 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter13 <= ap_enable_reg_pp0_iter12;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter14 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter14 <= ap_enable_reg_pp0_iter13;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter15 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter15 <= ap_enable_reg_pp0_iter14;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((((cmp89_read_read_fu_220_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln389_fu_633_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((cmp89_read_read_fu_220_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln389_fu_633_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'd0 == and_ln406_fu_677_p2)))) begin
        ap_phi_reg_pp0_iter1_flag_write_reg_498 <= 1'd0;
    end else if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter1_flag_write_reg_498 <= ap_phi_reg_pp0_iter0_flag_write_reg_498;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter5 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if ((1'b1 == ap_condition_91)) begin
            ap_phi_reg_pp0_iter6_flag_write_reg_498 <= 1'd1;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter6_flag_write_reg_498 <= ap_phi_reg_pp0_iter5_flag_write_reg_498;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter8 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if (((icmp_ln389_reg_1222_pp0_iter7_reg == 1'd1) & (first_row_index_5_read_reg_1203 == 32'd1))) begin
            ap_phi_reg_pp0_iter9_arrayidx17315516_load_061_reg_547 <= reg_570;
        end else if ((1'b1 == ap_condition_303)) begin
            ap_phi_reg_pp0_iter9_arrayidx17315516_load_061_reg_547 <= reg_576;
        end else if (((icmp_ln389_reg_1222_pp0_iter7_reg == 1'd1) & (first_row_index_5_read_reg_1203 == 32'd0))) begin
            ap_phi_reg_pp0_iter9_arrayidx17315516_load_061_reg_547 <= reg_582;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter9_arrayidx17315516_load_061_reg_547 <= ap_phi_reg_pp0_iter8_arrayidx17315516_load_061_reg_547;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter8 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if (((icmp_ln389_reg_1222_pp0_iter7_reg == 1'd1) & (first_row_index_5_read_reg_1203 == 32'd1))) begin
            ap_phi_reg_pp0_iter9_arrayidx18117515_load_065_reg_536 <= line_buffer_V_1_0_q1;
        end else if ((1'b1 == ap_condition_303)) begin
            ap_phi_reg_pp0_iter9_arrayidx18117515_load_065_reg_536 <= line_buffer_V_2_0_q1;
        end else if (((icmp_ln389_reg_1222_pp0_iter7_reg == 1'd1) & (first_row_index_5_read_reg_1203 == 32'd0))) begin
            ap_phi_reg_pp0_iter9_arrayidx18117515_load_065_reg_536 <= line_buffer_V_0_0_q1;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter9_arrayidx18117515_load_065_reg_536 <= ap_phi_reg_pp0_iter8_arrayidx18117515_load_065_reg_536;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter8 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if (((icmp_ln389_reg_1222_pp0_iter7_reg == 1'd1) & (first_row_index_5_read_reg_1203 == 32'd1))) begin
            ap_phi_reg_pp0_iter9_p_Val2_3_reg_514 <= line_buffer_V_2_0_q1;
        end else if ((1'b1 == ap_condition_303)) begin
            ap_phi_reg_pp0_iter9_p_Val2_3_reg_514 <= line_buffer_V_0_0_q1;
        end else if (((icmp_ln389_reg_1222_pp0_iter7_reg == 1'd1) & (first_row_index_5_read_reg_1203 == 32'd0))) begin
            ap_phi_reg_pp0_iter9_p_Val2_3_reg_514 <= line_buffer_V_1_0_q1;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter9_p_Val2_3_reg_514 <= ap_phi_reg_pp0_iter8_p_Val2_3_reg_514;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter8 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if (((icmp_ln389_reg_1222_pp0_iter7_reg == 1'd1) & (first_row_index_5_read_reg_1203 == 32'd1))) begin
            ap_phi_reg_pp0_iter9_p_Val2_s_reg_525 <= reg_576;
        end else if ((1'b1 == ap_condition_303)) begin
            ap_phi_reg_pp0_iter9_p_Val2_s_reg_525 <= reg_582;
        end else if (((icmp_ln389_reg_1222_pp0_iter7_reg == 1'd1) & (first_row_index_5_read_reg_1203 == 32'd0))) begin
            ap_phi_reg_pp0_iter9_p_Val2_s_reg_525 <= reg_570;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter9_p_Val2_s_reg_525 <= ap_phi_reg_pp0_iter8_p_Val2_s_reg_525;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if (((ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln389_fu_633_p2 == 1'd1))) begin
            j_fu_172 <= add_ln389_fu_639_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            j_fu_172 <= 31'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if (((ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln389_fu_633_p2 == 1'd1))) begin
            nextYScale_V_1_fu_164 <= ret_V_17;
        end else if ((ap_loop_init == 1'b1)) begin
            nextYScale_V_1_fu_164 <= nextYScale_V;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            read_pixel_1_fu_176 <= read_pixel;
        end else if ((1'b1 == ap_condition_1495)) begin
            read_pixel_1_fu_176 <= in_mat_420_dout;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if (((ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln389_fu_633_p2 == 1'd1))) begin
            tmp_fu_168 <= ret_V_11_fu_659_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            tmp_fu_168 <= indexy_V;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (((1'd1 == and_ln486_reg_1249_pp0_iter5_reg) & (1'd0 == and_ln487_reg_1241_pp0_iter5_reg) & (cmp273 == 1'd1)) | ((1'd1 == and_ln487_reg_1241_pp0_iter5_reg) & (icmp_ln489_reg_1245_pp0_iter5_reg == 1'd1) & (cmp273 == 1'd1))))) begin
        Wx_V_reg_1315 <= {{ret_V_6_fu_844_p2[23:12]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        Wx_V_reg_1315_pp0_iter7_reg <= Wx_V_reg_1315;
        Wx_V_reg_1315_pp0_iter8_reg <= Wx_V_reg_1315_pp0_iter7_reg;
        Wx_V_reg_1315_pp0_iter9_reg <= Wx_V_reg_1315_pp0_iter8_reg;
        and_ln406_reg_1231_pp0_iter2_reg <= and_ln406_reg_1231_pp0_iter1_reg;
        and_ln406_reg_1231_pp0_iter3_reg <= and_ln406_reg_1231_pp0_iter2_reg;
        and_ln406_reg_1231_pp0_iter4_reg <= and_ln406_reg_1231_pp0_iter3_reg;
        and_ln486_reg_1249_pp0_iter10_reg <= and_ln486_reg_1249_pp0_iter9_reg;
        and_ln486_reg_1249_pp0_iter11_reg <= and_ln486_reg_1249_pp0_iter10_reg;
        and_ln486_reg_1249_pp0_iter12_reg <= and_ln486_reg_1249_pp0_iter11_reg;
        and_ln486_reg_1249_pp0_iter13_reg <= and_ln486_reg_1249_pp0_iter12_reg;
        and_ln486_reg_1249_pp0_iter14_reg <= and_ln486_reg_1249_pp0_iter13_reg;
        and_ln486_reg_1249_pp0_iter2_reg <= and_ln486_reg_1249_pp0_iter1_reg;
        and_ln486_reg_1249_pp0_iter3_reg <= and_ln486_reg_1249_pp0_iter2_reg;
        and_ln486_reg_1249_pp0_iter4_reg <= and_ln486_reg_1249_pp0_iter3_reg;
        and_ln486_reg_1249_pp0_iter5_reg <= and_ln486_reg_1249_pp0_iter4_reg;
        and_ln486_reg_1249_pp0_iter6_reg <= and_ln486_reg_1249_pp0_iter5_reg;
        and_ln486_reg_1249_pp0_iter7_reg <= and_ln486_reg_1249_pp0_iter6_reg;
        and_ln486_reg_1249_pp0_iter8_reg <= and_ln486_reg_1249_pp0_iter7_reg;
        and_ln486_reg_1249_pp0_iter9_reg <= and_ln486_reg_1249_pp0_iter8_reg;
        and_ln487_reg_1241_pp0_iter10_reg <= and_ln487_reg_1241_pp0_iter9_reg;
        and_ln487_reg_1241_pp0_iter11_reg <= and_ln487_reg_1241_pp0_iter10_reg;
        and_ln487_reg_1241_pp0_iter12_reg <= and_ln487_reg_1241_pp0_iter11_reg;
        and_ln487_reg_1241_pp0_iter13_reg <= and_ln487_reg_1241_pp0_iter12_reg;
        and_ln487_reg_1241_pp0_iter14_reg <= and_ln487_reg_1241_pp0_iter13_reg;
        and_ln487_reg_1241_pp0_iter2_reg <= and_ln487_reg_1241_pp0_iter1_reg;
        and_ln487_reg_1241_pp0_iter3_reg <= and_ln487_reg_1241_pp0_iter2_reg;
        and_ln487_reg_1241_pp0_iter4_reg <= and_ln487_reg_1241_pp0_iter3_reg;
        and_ln487_reg_1241_pp0_iter5_reg <= and_ln487_reg_1241_pp0_iter4_reg;
        and_ln487_reg_1241_pp0_iter6_reg <= and_ln487_reg_1241_pp0_iter5_reg;
        and_ln487_reg_1241_pp0_iter7_reg <= and_ln487_reg_1241_pp0_iter6_reg;
        and_ln487_reg_1241_pp0_iter8_reg <= and_ln487_reg_1241_pp0_iter7_reg;
        and_ln487_reg_1241_pp0_iter9_reg <= and_ln487_reg_1241_pp0_iter8_reg;
        ap_loop_exit_ready_pp0_iter10_reg <= ap_loop_exit_ready_pp0_iter9_reg;
        ap_loop_exit_ready_pp0_iter11_reg <= ap_loop_exit_ready_pp0_iter10_reg;
        ap_loop_exit_ready_pp0_iter12_reg <= ap_loop_exit_ready_pp0_iter11_reg;
        ap_loop_exit_ready_pp0_iter13_reg <= ap_loop_exit_ready_pp0_iter12_reg;
        ap_loop_exit_ready_pp0_iter14_reg <= ap_loop_exit_ready_pp0_iter13_reg;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
        ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
        ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
        ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
        icmp_ln1049_reg_1235_pp0_iter2_reg <= icmp_ln1049_reg_1235_pp0_iter1_reg;
        icmp_ln1049_reg_1235_pp0_iter3_reg <= icmp_ln1049_reg_1235_pp0_iter2_reg;
        icmp_ln1049_reg_1235_pp0_iter4_reg <= icmp_ln1049_reg_1235_pp0_iter3_reg;
        icmp_ln1049_reg_1235_pp0_iter5_reg <= icmp_ln1049_reg_1235_pp0_iter4_reg;
        icmp_ln1049_reg_1235_pp0_iter6_reg <= icmp_ln1049_reg_1235_pp0_iter5_reg;
        icmp_ln1049_reg_1235_pp0_iter7_reg <= icmp_ln1049_reg_1235_pp0_iter6_reg;
        icmp_ln1049_reg_1235_pp0_iter8_reg <= icmp_ln1049_reg_1235_pp0_iter7_reg;
        icmp_ln389_reg_1222_pp0_iter10_reg <= icmp_ln389_reg_1222_pp0_iter9_reg;
        icmp_ln389_reg_1222_pp0_iter11_reg <= icmp_ln389_reg_1222_pp0_iter10_reg;
        icmp_ln389_reg_1222_pp0_iter12_reg <= icmp_ln389_reg_1222_pp0_iter11_reg;
        icmp_ln389_reg_1222_pp0_iter13_reg <= icmp_ln389_reg_1222_pp0_iter12_reg;
        icmp_ln389_reg_1222_pp0_iter2_reg <= icmp_ln389_reg_1222_pp0_iter1_reg;
        icmp_ln389_reg_1222_pp0_iter3_reg <= icmp_ln389_reg_1222_pp0_iter2_reg;
        icmp_ln389_reg_1222_pp0_iter4_reg <= icmp_ln389_reg_1222_pp0_iter3_reg;
        icmp_ln389_reg_1222_pp0_iter5_reg <= icmp_ln389_reg_1222_pp0_iter4_reg;
        icmp_ln389_reg_1222_pp0_iter6_reg <= icmp_ln389_reg_1222_pp0_iter5_reg;
        icmp_ln389_reg_1222_pp0_iter7_reg <= icmp_ln389_reg_1222_pp0_iter6_reg;
        icmp_ln389_reg_1222_pp0_iter8_reg <= icmp_ln389_reg_1222_pp0_iter7_reg;
        icmp_ln389_reg_1222_pp0_iter9_reg <= icmp_ln389_reg_1222_pp0_iter8_reg;
        icmp_ln489_reg_1245_pp0_iter10_reg <= icmp_ln489_reg_1245_pp0_iter9_reg;
        icmp_ln489_reg_1245_pp0_iter11_reg <= icmp_ln489_reg_1245_pp0_iter10_reg;
        icmp_ln489_reg_1245_pp0_iter12_reg <= icmp_ln489_reg_1245_pp0_iter11_reg;
        icmp_ln489_reg_1245_pp0_iter13_reg <= icmp_ln489_reg_1245_pp0_iter12_reg;
        icmp_ln489_reg_1245_pp0_iter14_reg <= icmp_ln489_reg_1245_pp0_iter13_reg;
        icmp_ln489_reg_1245_pp0_iter2_reg <= icmp_ln489_reg_1245_pp0_iter1_reg;
        icmp_ln489_reg_1245_pp0_iter3_reg <= icmp_ln489_reg_1245_pp0_iter2_reg;
        icmp_ln489_reg_1245_pp0_iter4_reg <= icmp_ln489_reg_1245_pp0_iter3_reg;
        icmp_ln489_reg_1245_pp0_iter5_reg <= icmp_ln489_reg_1245_pp0_iter4_reg;
        icmp_ln489_reg_1245_pp0_iter6_reg <= icmp_ln489_reg_1245_pp0_iter5_reg;
        icmp_ln489_reg_1245_pp0_iter7_reg <= icmp_ln489_reg_1245_pp0_iter6_reg;
        icmp_ln489_reg_1245_pp0_iter8_reg <= icmp_ln489_reg_1245_pp0_iter7_reg;
        icmp_ln489_reg_1245_pp0_iter9_reg <= icmp_ln489_reg_1245_pp0_iter8_reg;
        j_1_reg_1216_pp0_iter2_reg <= j_1_reg_1216_pp0_iter1_reg;
        j_1_reg_1216_pp0_iter3_reg <= j_1_reg_1216_pp0_iter2_reg;
        j_1_reg_1216_pp0_iter4_reg <= j_1_reg_1216_pp0_iter3_reg;
        j_1_reg_1216_pp0_iter5_reg <= j_1_reg_1216_pp0_iter4_reg;
        p_Result_8_reg_1366_pp0_iter10_reg <= p_Result_8_reg_1366;
        p_Result_8_reg_1366_pp0_iter11_reg <= p_Result_8_reg_1366_pp0_iter10_reg;
        p_Result_8_reg_1366_pp0_iter12_reg <= p_Result_8_reg_1366_pp0_iter11_reg;
        p_Result_8_reg_1366_pp0_iter13_reg <= p_Result_8_reg_1366_pp0_iter12_reg;
        ret_9_reg_1371_pp0_iter10_reg <= ret_9_reg_1371;
        trunc_ln737_reg_1226_pp0_iter2_reg <= trunc_ln737_reg_1226_pp0_iter1_reg;
        trunc_ln737_reg_1226_pp0_iter3_reg <= trunc_ln737_reg_1226_pp0_iter2_reg;
        trunc_ln737_reg_1226_pp0_iter4_reg <= trunc_ln737_reg_1226_pp0_iter3_reg;
        trunc_ln737_reg_1226_pp0_iter5_reg <= trunc_ln737_reg_1226_pp0_iter4_reg;
        trunc_ln737_reg_1226_pp0_iter6_reg <= trunc_ln737_reg_1226_pp0_iter5_reg;
        trunc_ln737_reg_1226_pp0_iter7_reg <= trunc_ln737_reg_1226_pp0_iter6_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (((1'd1 == and_ln486_reg_1249_pp0_iter7_reg) & (1'd0 == and_ln487_reg_1241_pp0_iter7_reg) & (cmp273 == 1'd1)) | ((1'd1 == and_ln487_reg_1241_pp0_iter7_reg) & (icmp_ln489_reg_1245_pp0_iter7_reg == 1'd1) & (cmp273 == 1'd1))))) begin
        Wy_V_reg_1351 <= {{ret_V_fu_908_p2[23:12]}};
    end
end

always @ (posedge ap_clk) begin
    if (((cmp89_read_read_fu_220_p2 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln389_fu_633_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        and_ln406_reg_1231 <= and_ln406_fu_677_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        and_ln406_reg_1231_pp0_iter1_reg <= and_ln406_reg_1231;
        and_ln486_reg_1249_pp0_iter1_reg <= and_ln486_reg_1249;
        and_ln487_reg_1241_pp0_iter1_reg <= and_ln487_reg_1241;
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        icmp_ln1049_reg_1235_pp0_iter1_reg <= icmp_ln1049_reg_1235;
        icmp_ln389_reg_1222 <= icmp_ln389_fu_633_p2;
        icmp_ln389_reg_1222_pp0_iter1_reg <= icmp_ln389_reg_1222;
        icmp_ln489_reg_1245_pp0_iter1_reg <= icmp_ln489_reg_1245;
        j_1_reg_1216 <= ap_sig_allocacmp_j_1;
        j_1_reg_1216_pp0_iter1_reg <= j_1_reg_1216;
        trunc_ln737_reg_1226_pp0_iter1_reg <= trunc_ln737_reg_1226;
    end
end

always @ (posedge ap_clk) begin
    if (((cmp273_read_read_fu_286_p2 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln389_fu_633_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'd0 == and_ln487_fu_693_p2))) begin
        and_ln486_reg_1249 <= and_ln486_fu_711_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((cmp273_read_read_fu_286_p2 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln389_fu_633_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        and_ln487_reg_1241 <= and_ln487_fu_693_p2;
        icmp_ln1049_reg_1235 <= icmp_ln1049_fu_687_p2;
        icmp_ln489_reg_1245 <= icmp_ln489_fu_699_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter1_arrayidx17315516_load_061_reg_547 <= ap_phi_reg_pp0_iter0_arrayidx17315516_load_061_reg_547;
        ap_phi_reg_pp0_iter1_arrayidx18117515_load_065_reg_536 <= ap_phi_reg_pp0_iter0_arrayidx18117515_load_065_reg_536;
        ap_phi_reg_pp0_iter1_p_Val2_3_reg_514 <= ap_phi_reg_pp0_iter0_p_Val2_3_reg_514;
        ap_phi_reg_pp0_iter1_p_Val2_s_reg_525 <= ap_phi_reg_pp0_iter0_p_Val2_s_reg_525;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter2_arrayidx17315516_load_061_reg_547 <= ap_phi_reg_pp0_iter1_arrayidx17315516_load_061_reg_547;
        ap_phi_reg_pp0_iter2_arrayidx18117515_load_065_reg_536 <= ap_phi_reg_pp0_iter1_arrayidx18117515_load_065_reg_536;
        ap_phi_reg_pp0_iter2_flag_write_reg_498 <= ap_phi_reg_pp0_iter1_flag_write_reg_498;
        ap_phi_reg_pp0_iter2_p_Val2_3_reg_514 <= ap_phi_reg_pp0_iter1_p_Val2_3_reg_514;
        ap_phi_reg_pp0_iter2_p_Val2_s_reg_525 <= ap_phi_reg_pp0_iter1_p_Val2_s_reg_525;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter3_arrayidx17315516_load_061_reg_547 <= ap_phi_reg_pp0_iter2_arrayidx17315516_load_061_reg_547;
        ap_phi_reg_pp0_iter3_arrayidx18117515_load_065_reg_536 <= ap_phi_reg_pp0_iter2_arrayidx18117515_load_065_reg_536;
        ap_phi_reg_pp0_iter3_flag_write_reg_498 <= ap_phi_reg_pp0_iter2_flag_write_reg_498;
        ap_phi_reg_pp0_iter3_p_Val2_3_reg_514 <= ap_phi_reg_pp0_iter2_p_Val2_3_reg_514;
        ap_phi_reg_pp0_iter3_p_Val2_s_reg_525 <= ap_phi_reg_pp0_iter2_p_Val2_s_reg_525;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter4_arrayidx17315516_load_061_reg_547 <= ap_phi_reg_pp0_iter3_arrayidx17315516_load_061_reg_547;
        ap_phi_reg_pp0_iter4_arrayidx18117515_load_065_reg_536 <= ap_phi_reg_pp0_iter3_arrayidx18117515_load_065_reg_536;
        ap_phi_reg_pp0_iter4_flag_write_reg_498 <= ap_phi_reg_pp0_iter3_flag_write_reg_498;
        ap_phi_reg_pp0_iter4_p_Val2_3_reg_514 <= ap_phi_reg_pp0_iter3_p_Val2_3_reg_514;
        ap_phi_reg_pp0_iter4_p_Val2_s_reg_525 <= ap_phi_reg_pp0_iter3_p_Val2_s_reg_525;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter5_arrayidx17315516_load_061_reg_547 <= ap_phi_reg_pp0_iter4_arrayidx17315516_load_061_reg_547;
        ap_phi_reg_pp0_iter5_arrayidx18117515_load_065_reg_536 <= ap_phi_reg_pp0_iter4_arrayidx18117515_load_065_reg_536;
        ap_phi_reg_pp0_iter5_flag_write_reg_498 <= ap_phi_reg_pp0_iter4_flag_write_reg_498;
        ap_phi_reg_pp0_iter5_p_Val2_3_reg_514 <= ap_phi_reg_pp0_iter4_p_Val2_3_reg_514;
        ap_phi_reg_pp0_iter5_p_Val2_s_reg_525 <= ap_phi_reg_pp0_iter4_p_Val2_s_reg_525;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter5 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter6_arrayidx17315516_load_061_reg_547 <= ap_phi_reg_pp0_iter5_arrayidx17315516_load_061_reg_547;
        ap_phi_reg_pp0_iter6_arrayidx18117515_load_065_reg_536 <= ap_phi_reg_pp0_iter5_arrayidx18117515_load_065_reg_536;
        ap_phi_reg_pp0_iter6_p_Val2_3_reg_514 <= ap_phi_reg_pp0_iter5_p_Val2_3_reg_514;
        ap_phi_reg_pp0_iter6_p_Val2_s_reg_525 <= ap_phi_reg_pp0_iter5_p_Val2_s_reg_525;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter6 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter7_arrayidx17315516_load_061_reg_547 <= ap_phi_reg_pp0_iter6_arrayidx17315516_load_061_reg_547;
        ap_phi_reg_pp0_iter7_arrayidx18117515_load_065_reg_536 <= ap_phi_reg_pp0_iter6_arrayidx18117515_load_065_reg_536;
        ap_phi_reg_pp0_iter7_p_Val2_3_reg_514 <= ap_phi_reg_pp0_iter6_p_Val2_3_reg_514;
        ap_phi_reg_pp0_iter7_p_Val2_s_reg_525 <= ap_phi_reg_pp0_iter6_p_Val2_s_reg_525;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter7 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter8_arrayidx17315516_load_061_reg_547 <= ap_phi_reg_pp0_iter7_arrayidx17315516_load_061_reg_547;
        ap_phi_reg_pp0_iter8_arrayidx18117515_load_065_reg_536 <= ap_phi_reg_pp0_iter7_arrayidx18117515_load_065_reg_536;
        ap_phi_reg_pp0_iter8_p_Val2_3_reg_514 <= ap_phi_reg_pp0_iter7_p_Val2_3_reg_514;
        ap_phi_reg_pp0_iter8_p_Val2_s_reg_525 <= ap_phi_reg_pp0_iter7_p_Val2_s_reg_525;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln389_reg_1222_pp0_iter5_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        idx_nxt_reg_1280 <= idx_nxt_fu_866_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln389_reg_1222_pp0_iter4_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        indexx_pre_V_reg_1258 <= indexx_pre_V_fu_764_p3;
        trunc_ln712_reg_1275 <= trunc_ln712_fu_786_p1;
        trunc_ln902_reg_1270 <= trunc_ln902_fu_782_p1;
        trunc_ln_reg_1263 <= {{indexx_pre_V_fu_764_p3[38:22]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (((1'd1 == and_ln486_reg_1249_pp0_iter8_reg) & (1'd0 == and_ln487_reg_1241_pp0_iter8_reg) & (cmp273 == 1'd1)) | ((1'd1 == and_ln487_reg_1241_pp0_iter8_reg) & (icmp_ln489_reg_1245_pp0_iter8_reg == 1'd1) & (cmp273 == 1'd1))))) begin
        p_Result_8_reg_1366 <= p_Result_8_fu_930_p3;
        ret_10_reg_1376 <= ret_10_fu_992_p2;
        ret_9_reg_1371 <= ret_9_fu_980_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((((ap_enable_reg_pp0_iter7 == 1'b1) & (first_row_index_5_read_reg_1203 == 32'd0) & (icmp_ln389_reg_1222_pp0_iter6_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter7 == 1'b1) & (icmp_ln1049_reg_1235_pp0_iter6_reg == 1'd0) & (first_row_index_5_read_reg_1203 == 32'd1) & (icmp_ln389_reg_1222_pp0_iter6_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        reg_570 <= line_buffer_V_1_0_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((~(first_row_index_5_read_reg_1203 == 32'd0) & ~(first_row_index_5_read_reg_1203 == 32'd1) & (ap_enable_reg_pp0_iter7 == 1'b1) & (icmp_ln1049_reg_1235_pp0_iter6_reg == 1'd0) & (icmp_ln389_reg_1222_pp0_iter6_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter7 == 1'b1) & (first_row_index_5_read_reg_1203 == 32'd1) & (icmp_ln389_reg_1222_pp0_iter6_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        reg_576 <= line_buffer_V_2_0_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((~(first_row_index_5_read_reg_1203 == 32'd0) & ~(first_row_index_5_read_reg_1203 == 32'd1) & (ap_enable_reg_pp0_iter7 == 1'b1) & (icmp_ln389_reg_1222_pp0_iter6_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter7 == 1'b1) & (icmp_ln1049_reg_1235_pp0_iter6_reg == 1'd0) & (first_row_index_5_read_reg_1203 == 32'd0) & (icmp_ln389_reg_1222_pp0_iter6_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        reg_582 <= line_buffer_V_0_0_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (((1'd1 == and_ln486_reg_1249_pp0_iter13_reg) & (1'd0 == and_ln487_reg_1241_pp0_iter13_reg) & (cmp273 == 1'd1)) | ((1'd1 == and_ln487_reg_1241_pp0_iter13_reg) & (icmp_ln489_reg_1245_pp0_iter13_reg == 1'd1) & (cmp273 == 1'd1))))) begin
        ret_V_13_reg_1421 <= ret_V_13_fu_1095_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln389_fu_633_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        trunc_ln737_reg_1226 <= trunc_ln737_fu_667_p1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln389_fu_633_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter14_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_wait_0 & ap_sub_ext_blocking_0) == 1'b1)) begin
        ap_ext_blocking_sub_n = 1'b0;
    end else begin
        ap_ext_blocking_sub_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter15 == 1'b0) & (ap_enable_reg_pp0_iter14 == 1'b0) & (ap_enable_reg_pp0_iter13 == 1'b0) & (ap_enable_reg_pp0_iter12 == 1'b0) & (ap_enable_reg_pp0_iter11 == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_wait_0 & ap_sub_int_blocking_0) == 1'b1)) begin
        ap_int_blocking_sub_n = 1'b0;
    end else begin
        ap_int_blocking_sub_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_sig_allocacmp_j_1 = 31'd0;
    end else begin
        ap_sig_allocacmp_j_1 = j_fu_172;
    end
end

always @ (*) begin
    if (((ap_wait_0 & ap_sub_str_blocking_0) == 1'b1)) begin
        ap_str_blocking_sub_n = 1'b0;
    end else begin
        ap_str_blocking_sub_n = 1'b1;
    end
end

always @ (*) begin
    if ((grp_scaleCompute_17_42_20_48_16_1_s_fu_558_ap_ext_blocking_n == 1'b0)) begin
        ap_sub_ext_blocking_0 = 1'b1;
    end else begin
        ap_sub_ext_blocking_0 = 1'b0;
    end
end

always @ (*) begin
    if ((grp_scaleCompute_17_42_20_48_16_1_s_fu_558_ap_int_blocking_n == 1'b0)) begin
        ap_sub_int_blocking_0 = 1'b1;
    end else begin
        ap_sub_int_blocking_0 = 1'b0;
    end
end

always @ (*) begin
    if ((grp_scaleCompute_17_42_20_48_16_1_s_fu_558_ap_str_blocking_n == 1'b0)) begin
        ap_sub_str_blocking_0 = 1'b1;
    end else begin
        ap_sub_str_blocking_0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_ST_fsm_pp0_stage0 == ap_CS_fsm)) begin
        ap_wait_0 = 1'b1;
    end else begin
        ap_wait_0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_1115_ce = 1'b1;
    end else begin
        grp_fu_1115_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_1122_ce = 1'b1;
    end else begin
        grp_fu_1122_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_1129_ce = 1'b1;
    end else begin
        grp_fu_1129_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_1138_ce = 1'b1;
    end else begin
        grp_fu_1138_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001_ignoreCallOp84))) begin
        grp_scaleCompute_17_42_20_48_16_1_s_fu_558_ap_ce = 1'b1;
    end else begin
        grp_scaleCompute_17_42_20_48_16_1_s_fu_558_ap_ce = 1'b0;
    end
end

always @ (*) begin
    if (((ap_predicate_op97_read_state6 == 1'b1) & (ap_enable_reg_pp0_iter5 == 1'b1) & (1'b0 == ap_block_pp0_stage0))) begin
        in_mat_420_blk_n = in_mat_420_empty_n;
    end else begin
        in_mat_420_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_predicate_op97_read_state6 == 1'b1) & (ap_enable_reg_pp0_iter5 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        in_mat_420_read = 1'b1;
    end else begin
        in_mat_420_read = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln389_reg_1222_pp0_iter13_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        indexy_V_1_out_ap_vld = 1'b1;
    end else begin
        indexy_V_1_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter6 == 1'b1) & (1'b0 == ap_block_pp0_stage0))) begin
        if ((1'b1 == ap_condition_595)) begin
            line_buffer_V_0_0_address0 = line_buffer_V_0_0_addr_gep_fu_424_p3;
        end else if ((1'b1 == ap_condition_587)) begin
            line_buffer_V_0_0_address0 = zext_ln430_fu_872_p1;
        end else if (((ap_phi_mux_flag_write_phi_fu_503_p6 == 1'd1) & (first_row_index_5_read_reg_1203 == 32'd1))) begin
            line_buffer_V_0_0_address0 = zext_ln389_fu_795_p1;
        end else begin
            line_buffer_V_0_0_address0 = 'bx;
        end
    end else begin
        line_buffer_V_0_0_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_1480)) begin
        if ((~(first_row_index_5_read_reg_1203 == 32'd0) & ~(first_row_index_5_read_reg_1203 == 32'd1))) begin
            line_buffer_V_0_0_address1 = line_buffer_V_0_0_addr_1_gep_fu_490_p3;
        end else if (((icmp_ln1049_reg_1235_pp0_iter6_reg == 1'd0) & (first_row_index_5_read_reg_1203 == 32'd0))) begin
            line_buffer_V_0_0_address1 = zext_ln431_fu_892_p1;
        end else begin
            line_buffer_V_0_0_address1 = 'bx;
        end
    end else begin
        line_buffer_V_0_0_address1 = 'bx;
    end
end

always @ (*) begin
    if ((((ap_phi_mux_flag_write_phi_fu_503_p6 == 1'd1) & (ap_enable_reg_pp0_iter6 == 1'b1) & (first_row_index_5_read_reg_1203 == 32'd1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((icmp_ln1049_reg_1235_pp0_iter5_reg == 1'd0) & (icmp_ln389_reg_1222_pp0_iter5_reg == 1'd1) & (ap_enable_reg_pp0_iter6 == 1'b1) & (first_row_index_5_read_reg_1203 == 32'd0) & (1'b0 == ap_block_pp0_stage0_11001)) | (~(first_row_index_5_read_reg_1203 == 32'd0) & ~(first_row_index_5_read_reg_1203 == 32'd1) & (icmp_ln389_reg_1222_pp0_iter5_reg == 1'd1) & (ap_enable_reg_pp0_iter6 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        line_buffer_V_0_0_ce0 = 1'b1;
    end else begin
        line_buffer_V_0_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((~(first_row_index_5_read_reg_1203 == 32'd0) & ~(first_row_index_5_read_reg_1203 == 32'd1) & (ap_enable_reg_pp0_iter7 == 1'b1) & (icmp_ln389_reg_1222_pp0_iter6_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter7 == 1'b1) & (icmp_ln1049_reg_1235_pp0_iter6_reg == 1'd0) & (first_row_index_5_read_reg_1203 == 32'd0) & (icmp_ln389_reg_1222_pp0_iter6_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        line_buffer_V_0_0_ce1 = 1'b1;
    end else begin
        line_buffer_V_0_0_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_phi_mux_flag_write_phi_fu_503_p6 == 1'd1) & (ap_enable_reg_pp0_iter6 == 1'b1) & (first_row_index_5_read_reg_1203 == 32'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        line_buffer_V_0_0_we0 = 1'b1;
    end else begin
        line_buffer_V_0_0_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter6 == 1'b1) & (1'b0 == ap_block_pp0_stage0))) begin
        if ((1'b1 == ap_condition_901)) begin
            line_buffer_V_1_0_address0 = zext_ln389_fu_795_p1;
        end else if (((icmp_ln389_reg_1222_pp0_iter5_reg == 1'd1) & (first_row_index_5_read_reg_1203 == 32'd0))) begin
            line_buffer_V_1_0_address0 = line_buffer_V_1_0_addr_gep_fu_402_p3;
        end else if ((1'b1 == ap_condition_579)) begin
            line_buffer_V_1_0_address0 = zext_ln430_fu_872_p1;
        end else begin
            line_buffer_V_1_0_address0 = 'bx;
        end
    end else begin
        line_buffer_V_1_0_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_1480)) begin
        if ((first_row_index_5_read_reg_1203 == 32'd0)) begin
            line_buffer_V_1_0_address1 = line_buffer_V_1_0_addr_1_gep_fu_475_p3;
        end else if (((icmp_ln1049_reg_1235_pp0_iter6_reg == 1'd0) & (first_row_index_5_read_reg_1203 == 32'd1))) begin
            line_buffer_V_1_0_address1 = zext_ln431_fu_892_p1;
        end else begin
            line_buffer_V_1_0_address1 = 'bx;
        end
    end else begin
        line_buffer_V_1_0_address1 = 'bx;
    end
end

always @ (*) begin
    if ((((icmp_ln1049_reg_1235_pp0_iter5_reg == 1'd0) & (icmp_ln389_reg_1222_pp0_iter5_reg == 1'd1) & (ap_enable_reg_pp0_iter6 == 1'b1) & (first_row_index_5_read_reg_1203 == 32'd1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((icmp_ln389_reg_1222_pp0_iter5_reg == 1'd1) & (ap_enable_reg_pp0_iter6 == 1'b1) & (first_row_index_5_read_reg_1203 == 32'd0) & (1'b0 == ap_block_pp0_stage0_11001)) | (~(first_row_index_5_read_reg_1203 == 32'd0) & ~(first_row_index_5_read_reg_1203 == 32'd1) & (ap_phi_mux_flag_write_phi_fu_503_p6 == 1'd1) & (ap_enable_reg_pp0_iter6 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        line_buffer_V_1_0_ce0 = 1'b1;
    end else begin
        line_buffer_V_1_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter7 == 1'b1) & (first_row_index_5_read_reg_1203 == 32'd0) & (icmp_ln389_reg_1222_pp0_iter6_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter7 == 1'b1) & (icmp_ln1049_reg_1235_pp0_iter6_reg == 1'd0) & (first_row_index_5_read_reg_1203 == 32'd1) & (icmp_ln389_reg_1222_pp0_iter6_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        line_buffer_V_1_0_ce1 = 1'b1;
    end else begin
        line_buffer_V_1_0_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((~(first_row_index_5_read_reg_1203 == 32'd0) & ~(first_row_index_5_read_reg_1203 == 32'd1) & (ap_phi_mux_flag_write_phi_fu_503_p6 == 1'd1) & (ap_enable_reg_pp0_iter6 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        line_buffer_V_1_0_we0 = 1'b1;
    end else begin
        line_buffer_V_1_0_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter6 == 1'b1) & (1'b0 == ap_block_pp0_stage0))) begin
        if ((1'b1 == ap_condition_596)) begin
            line_buffer_V_2_0_address0 = line_buffer_V_2_0_addr_gep_fu_417_p3;
        end else if (((ap_phi_mux_flag_write_phi_fu_503_p6 == 1'd1) & (first_row_index_5_read_reg_1203 == 32'd0))) begin
            line_buffer_V_2_0_address0 = zext_ln389_fu_795_p1;
        end else if (((icmp_ln389_reg_1222_pp0_iter5_reg == 1'd1) & (first_row_index_5_read_reg_1203 == 32'd1))) begin
            line_buffer_V_2_0_address0 = zext_ln430_fu_872_p1;
        end else begin
            line_buffer_V_2_0_address0 = 'bx;
        end
    end else begin
        line_buffer_V_2_0_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_1480)) begin
        if ((1'b1 == ap_condition_1492)) begin
            line_buffer_V_2_0_address1 = line_buffer_V_2_0_addr_1_gep_fu_483_p3;
        end else if ((first_row_index_5_read_reg_1203 == 32'd1)) begin
            line_buffer_V_2_0_address1 = zext_ln431_fu_892_p1;
        end else begin
            line_buffer_V_2_0_address1 = 'bx;
        end
    end else begin
        line_buffer_V_2_0_address1 = 'bx;
    end
end

always @ (*) begin
    if ((((ap_phi_mux_flag_write_phi_fu_503_p6 == 1'd1) & (ap_enable_reg_pp0_iter6 == 1'b1) & (first_row_index_5_read_reg_1203 == 32'd0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((icmp_ln389_reg_1222_pp0_iter5_reg == 1'd1) & (ap_enable_reg_pp0_iter6 == 1'b1) & (first_row_index_5_read_reg_1203 == 32'd1) & (1'b0 == ap_block_pp0_stage0_11001)) | (~(first_row_index_5_read_reg_1203 == 32'd0) & ~(first_row_index_5_read_reg_1203 == 32'd1) & (icmp_ln1049_reg_1235_pp0_iter5_reg == 1'd0) & (icmp_ln389_reg_1222_pp0_iter5_reg == 1'd1) & (ap_enable_reg_pp0_iter6 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        line_buffer_V_2_0_ce0 = 1'b1;
    end else begin
        line_buffer_V_2_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((~(first_row_index_5_read_reg_1203 == 32'd0) & ~(first_row_index_5_read_reg_1203 == 32'd1) & (ap_enable_reg_pp0_iter7 == 1'b1) & (icmp_ln1049_reg_1235_pp0_iter6_reg == 1'd0) & (icmp_ln389_reg_1222_pp0_iter6_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter7 == 1'b1) & (first_row_index_5_read_reg_1203 == 32'd1) & (icmp_ln389_reg_1222_pp0_iter6_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        line_buffer_V_2_0_ce1 = 1'b1;
    end else begin
        line_buffer_V_2_0_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_phi_mux_flag_write_phi_fu_503_p6 == 1'd1) & (ap_enable_reg_pp0_iter6 == 1'b1) & (first_row_index_5_read_reg_1203 == 32'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        line_buffer_V_2_0_we0 = 1'b1;
    end else begin
        line_buffer_V_2_0_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln389_reg_1222_pp0_iter13_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        nextYScale_V_1_out_ap_vld = 1'b1;
    end else begin
        nextYScale_V_1_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter15 == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (ap_predicate_op237_write_state16 == 1'b1))) begin
        out_mat_421_blk_n = out_mat_421_full_n;
    end else begin
        out_mat_421_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter15 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op237_write_state16 == 1'b1))) begin
        out_mat_421_write = 1'b1;
    end else begin
        out_mat_421_write = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln389_reg_1222_pp0_iter13_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        read_pixel_1_out_ap_vld = 1'b1;
    end else begin
        read_pixel_1_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign P4_V_fu_1033_p3 = {{p_Result_8_reg_1366_pp0_iter13_reg}, {10'd0}};

assign Wxy_V_fu_1011_p1 = grp_fu_1115_p2;

assign Wxy_V_fu_1011_p4 = {{Wxy_V_fu_1011_p1[21:10]}};

assign Wy_V_fu_913_p4 = {{ret_V_fu_908_p2[23:12]}};

assign add_ln389_fu_639_p2 = (ap_sig_allocacmp_j_1 + 31'd1);

assign and_ln406_fu_677_p2 = (icmp_ln408_fu_671_p2 & icmp_ln1061_1);

assign and_ln486_fu_711_p2 = (icmp_ln489_fu_699_p2 & icmp_ln1049_1_fu_705_p2);

assign and_ln487_fu_693_p2 = (icmp_ln1049_fu_687_p2 & cmp277);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = (((ap_predicate_op97_read_state6 == 1'b1) & (in_mat_420_empty_n == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b1)) | ((ap_enable_reg_pp0_iter15 == 1'b1) & (ap_predicate_op237_write_state16 == 1'b1) & (out_mat_421_full_n == 1'b0)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((ap_predicate_op97_read_state6 == 1'b1) & (in_mat_420_empty_n == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b1)) | ((ap_enable_reg_pp0_iter15 == 1'b1) & (ap_predicate_op237_write_state16 == 1'b1) & (out_mat_421_full_n == 1'b0)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001_ignoreCallOp84 = (((ap_predicate_op97_read_state6 == 1'b1) & (in_mat_420_empty_n == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b1)) | ((ap_enable_reg_pp0_iter15 == 1'b1) & (ap_predicate_op237_write_state16 == 1'b1) & (out_mat_421_full_n == 1'b0)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((ap_predicate_op97_read_state6 == 1'b1) & (in_mat_420_empty_n == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b1)) | ((ap_enable_reg_pp0_iter15 == 1'b1) & (ap_predicate_op237_write_state16 == 1'b1) & (out_mat_421_full_n == 1'b0)));
end

assign ap_block_state10_pp0_stage0_iter9 = ~(1'b1 == 1'b1);

assign ap_block_state10_pp0_stage0_iter9_ignore_call6 = ~(1'b1 == 1'b1);

assign ap_block_state11_pp0_stage0_iter10 = ~(1'b1 == 1'b1);

assign ap_block_state11_pp0_stage0_iter10_ignore_call6 = ~(1'b1 == 1'b1);

assign ap_block_state12_pp0_stage0_iter11 = ~(1'b1 == 1'b1);

assign ap_block_state12_pp0_stage0_iter11_ignore_call6 = ~(1'b1 == 1'b1);

assign ap_block_state13_pp0_stage0_iter12 = ~(1'b1 == 1'b1);

assign ap_block_state13_pp0_stage0_iter12_ignore_call6 = ~(1'b1 == 1'b1);

assign ap_block_state14_pp0_stage0_iter13 = ~(1'b1 == 1'b1);

assign ap_block_state14_pp0_stage0_iter13_ignore_call6 = ~(1'b1 == 1'b1);

assign ap_block_state15_pp0_stage0_iter14 = ~(1'b1 == 1'b1);

assign ap_block_state15_pp0_stage0_iter14_ignore_call6 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state16_pp0_stage0_iter15 = ((ap_predicate_op237_write_state16 == 1'b1) & (out_mat_421_full_n == 1'b0));
end

always @ (*) begin
    ap_block_state16_pp0_stage0_iter15_ignore_call6 = ((ap_predicate_op237_write_state16 == 1'b1) & (out_mat_421_full_n == 1'b0));
end

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0_ignore_call6 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1_ignore_call6 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2_ignore_call6 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3_ignore_call6 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4_ignore_call6 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state6_pp0_stage0_iter5 = ((ap_predicate_op97_read_state6 == 1'b1) & (in_mat_420_empty_n == 1'b0));
end

always @ (*) begin
    ap_block_state6_pp0_stage0_iter5_ignore_call6 = ((ap_predicate_op97_read_state6 == 1'b1) & (in_mat_420_empty_n == 1'b0));
end

assign ap_block_state7_pp0_stage0_iter6 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter6_ignore_call6 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage0_iter7 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage0_iter7_ignore_call6 = ~(1'b1 == 1'b1);

assign ap_block_state9_pp0_stage0_iter8 = ~(1'b1 == 1'b1);

assign ap_block_state9_pp0_stage0_iter8_ignore_call6 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_condition_1480 = ((ap_enable_reg_pp0_iter7 == 1'b1) & (icmp_ln389_reg_1222_pp0_iter6_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0));
end

always @ (*) begin
    ap_condition_1492 = (~(first_row_index_5_read_reg_1203 == 32'd0) & ~(first_row_index_5_read_reg_1203 == 32'd1) & (icmp_ln1049_reg_1235_pp0_iter6_reg == 1'd0));
end

always @ (*) begin
    ap_condition_1495 = ((cmp89 == 1'd1) & (1'd1 == and_ln406_reg_1231_pp0_iter4_reg) & (icmp_ln389_reg_1222_pp0_iter4_reg == 1'd1) & (ap_enable_reg_pp0_iter5 == 1'b1));
end

always @ (*) begin
    ap_condition_303 = (~(first_row_index_5_read_reg_1203 == 32'd0) & ~(first_row_index_5_read_reg_1203 == 32'd1) & (icmp_ln389_reg_1222_pp0_iter7_reg == 1'd1));
end

always @ (*) begin
    ap_condition_579 = ((icmp_ln1049_reg_1235_pp0_iter5_reg == 1'd0) & (icmp_ln389_reg_1222_pp0_iter5_reg == 1'd1) & (first_row_index_5_read_reg_1203 == 32'd1));
end

always @ (*) begin
    ap_condition_587 = ((icmp_ln1049_reg_1235_pp0_iter5_reg == 1'd0) & (icmp_ln389_reg_1222_pp0_iter5_reg == 1'd1) & (first_row_index_5_read_reg_1203 == 32'd0));
end

always @ (*) begin
    ap_condition_595 = (~(first_row_index_5_read_reg_1203 == 32'd0) & ~(first_row_index_5_read_reg_1203 == 32'd1) & (icmp_ln389_reg_1222_pp0_iter5_reg == 1'd1));
end

always @ (*) begin
    ap_condition_596 = (~(first_row_index_5_read_reg_1203 == 32'd0) & ~(first_row_index_5_read_reg_1203 == 32'd1) & (icmp_ln1049_reg_1235_pp0_iter5_reg == 1'd0) & (icmp_ln389_reg_1222_pp0_iter5_reg == 1'd1));
end

always @ (*) begin
    ap_condition_901 = (~(first_row_index_5_read_reg_1203 == 32'd0) & ~(first_row_index_5_read_reg_1203 == 32'd1) & (ap_phi_mux_flag_write_phi_fu_503_p6 == 1'd1));
end

always @ (*) begin
    ap_condition_91 = ((cmp89 == 1'd1) & (1'd1 == and_ln406_reg_1231_pp0_iter4_reg) & (icmp_ln389_reg_1222_pp0_iter4_reg == 1'd1));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_ext_blocking_n = (ap_ext_blocking_sub_n & 1'b1);

assign ap_int_blocking_cur_n = (out_mat_421_blk_n & in_mat_420_blk_n);

assign ap_int_blocking_n = (ap_int_blocking_sub_n & ap_int_blocking_cur_n);

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_phi_mux_flag_write_phi_fu_503_p6 = ap_phi_reg_pp0_iter6_flag_write_reg_498;

assign ap_phi_reg_pp0_iter0_arrayidx17315516_load_061_reg_547 = 'bx;

assign ap_phi_reg_pp0_iter0_arrayidx18117515_load_065_reg_536 = 'bx;

assign ap_phi_reg_pp0_iter0_flag_write_reg_498 = 'bx;

assign ap_phi_reg_pp0_iter0_p_Val2_3_reg_514 = 'bx;

assign ap_phi_reg_pp0_iter0_p_Val2_s_reg_525 = 'bx;

always @ (*) begin
    ap_predicate_op237_write_state16 = (((1'd1 == and_ln486_reg_1249_pp0_iter14_reg) & (1'd0 == and_ln487_reg_1241_pp0_iter14_reg) & (cmp273 == 1'd1)) | ((1'd1 == and_ln487_reg_1241_pp0_iter14_reg) & (icmp_ln489_reg_1245_pp0_iter14_reg == 1'd1) & (cmp273 == 1'd1)));
end

always @ (*) begin
    ap_predicate_op97_read_state6 = ((cmp89 == 1'd1) & (1'd1 == and_ln406_reg_1231_pp0_iter4_reg) & (icmp_ln389_reg_1222_pp0_iter4_reg == 1'd1));
end

assign ap_str_blocking_n = (ap_str_blocking_sub_n & 1'b1);

assign cmp273_read_read_fu_286_p2 = cmp273;

assign cmp89_read_read_fu_220_p2 = cmp89;

assign empty_fu_853_p1 = idx_1_fu_825_p3[11:0];

assign first_row_index_5_read_reg_1203 = first_row_index_5;

assign grp_fu_1115_p0 = grp_fu_1115_p00;

assign grp_fu_1115_p00 = Wx_V_reg_1315_pp0_iter7_reg;

assign grp_fu_1115_p1 = grp_fu_1115_p10;

assign grp_fu_1115_p10 = Wy_V_fu_913_p4;

assign grp_fu_1122_p0 = grp_fu_1122_p00;

assign grp_fu_1122_p00 = Wy_V_reg_1351;

assign grp_fu_1129_p0 = grp_fu_1129_p00;

assign grp_fu_1129_p00 = Wx_V_reg_1315_pp0_iter9_reg;

assign grp_fu_1138_p0 = grp_fu_1138_p00;

assign grp_fu_1138_p00 = Wxy_V_fu_1011_p4;

assign grp_scaleCompute_17_42_20_48_16_1_s_fu_195_p_ce = grp_scaleCompute_17_42_20_48_16_1_s_fu_558_ap_ce;

assign grp_scaleCompute_17_42_20_48_16_1_s_fu_195_p_din1 = zext_ln395_fu_735_p1;

assign grp_scaleCompute_17_42_20_48_16_1_s_fu_195_p_din2 = trunc_ln3;

assign grp_scaleCompute_17_42_20_48_16_1_s_fu_558_ap_ext_blocking_n = 1'b0;

assign grp_scaleCompute_17_42_20_48_16_1_s_fu_558_ap_int_blocking_n = 1'b0;

assign grp_scaleCompute_17_42_20_48_16_1_s_fu_558_ap_str_blocking_n = 1'b0;

assign icmp_ln1049_1_fu_705_p2 = ((zext_ln1049_fu_683_p1 == op2_assign_2) ? 1'b1 : 1'b0);

assign icmp_ln1049_fu_687_p2 = ((zext_ln1049_fu_683_p1 == op2_assign) ? 1'b1 : 1'b0);

assign icmp_ln1547_fu_752_p2 = (($signed(sext_ln1548_fu_740_p1) > $signed(shl_i_i_i_i_i)) ? 1'b1 : 1'b0);

assign icmp_ln389_fu_633_p2 = (($signed(zext_ln389_1_fu_629_p1) < $signed(loop_col_count)) ? 1'b1 : 1'b0);

assign icmp_ln408_fu_671_p2 = (($signed(zext_ln389_1_fu_629_p1) < $signed(p_read1)) ? 1'b1 : 1'b0);

assign icmp_ln489_fu_699_p2 = (($signed(zext_ln389_1_fu_629_p1) < $signed(p_read3)) ? 1'b1 : 1'b0);

assign icmp_ln902_1_fu_808_p2 = ((trunc_ln902_reg_1270 == 22'd0) ? 1'b1 : 1'b0);

assign icmp_ln902_2_fu_1075_p2 = ((trunc_ln902_1_fu_1071_p1 == 10'd0) ? 1'b1 : 1'b0);

assign icmp_ln902_fu_645_p2 = ((indexy_pre_V != 22'd0) ? 1'b1 : 1'b0);

assign idx_1_fu_825_p3 = ((p_Result_1_fu_801_p3[0:0] == 1'b1) ? select_ln901_1_fu_818_p3 : trunc_ln_reg_1263);

assign idx_fu_849_p1 = idx_1_fu_825_p3;

assign idx_nxt_fu_866_p2 = (empty_fu_853_p1 + zext_ln428_fu_862_p1);

assign indexx_pre_V_3_fu_757_p2 = grp_scaleCompute_17_42_20_48_16_1_s_fu_195_p_dout0;

assign indexx_pre_V_3_fu_757_p3 = ((icmp_ln1547_fu_752_p2[0:0] == 1'b1) ? indexx_pre_V_1 : indexx_pre_V_3_fu_757_p2);

assign indexx_pre_V_fu_764_p3 = ((tmp_2_fu_744_p3[0:0] == 1'b1) ? 42'd0 : indexx_pre_V_3_fu_757_p3);

assign indexy_V_1_out = tmp_fu_168;

assign line_buffer_V_0_0_addr_1_gep_fu_490_p3 = zext_ln431_fu_892_p1;

assign line_buffer_V_0_0_addr_gep_fu_424_p3 = zext_ln430_fu_872_p1;

assign line_buffer_V_0_0_d0 = read_pixel_1_fu_176;

assign line_buffer_V_1_0_addr_1_gep_fu_475_p3 = zext_ln431_fu_892_p1;

assign line_buffer_V_1_0_addr_gep_fu_402_p3 = zext_ln430_fu_872_p1;

assign line_buffer_V_1_0_d0 = read_pixel_1_fu_176;

assign line_buffer_V_2_0_addr_1_gep_fu_483_p3 = zext_ln431_fu_892_p1;

assign line_buffer_V_2_0_addr_gep_fu_417_p3 = zext_ln430_fu_872_p1;

assign nextYScale_V_1_out = nextYScale_V_1_fu_164;

assign not_cmp_i_i173_fu_857_p2 = ((idx_fu_849_p1 != tmp_V) ? 1'b1 : 1'b0);

assign out_mat_421_din = ret_V_13_reg_1421;

assign p_Result_1_fu_801_p3 = indexx_pre_V_reg_1258[32'd41];

assign p_Result_6_fu_1063_p3 = ret_V_8_fu_1047_p2[32'd23];

assign p_Result_8_fu_930_p3 = ((icmp_ln1049_reg_1235_pp0_iter8_reg[0:0] == 1'b1) ? ap_phi_reg_pp0_iter9_p_Val2_s_reg_525 : ap_phi_reg_pp0_iter9_arrayidx17315516_load_061_reg_547);

assign p_Result_9_fu_937_p3 = ((icmp_ln1049_reg_1235_pp0_iter8_reg[0:0] == 1'b1) ? ap_phi_reg_pp0_iter9_p_Val2_3_reg_514 : ap_phi_reg_pp0_iter9_arrayidx18117515_load_065_reg_536);

assign p_Result_read_read_fu_244_p2 = p_Result_s;

assign read_pixel_1_out = read_pixel_1_fu_176;

assign ret_10_fu_992_p2 = (zext_ln225_3_fu_962_p1 - zext_ln225_fu_944_p1);

assign ret_6_fu_986_p2 = (zext_ln225_2_fu_958_p1 - zext_ln225_fu_944_p1);

assign ret_8_fu_966_p2 = (zext_ln225_3_fu_962_p1 + zext_ln225_2_fu_958_p1);

assign ret_9_fu_980_p2 = (zext_ln225_4_fu_972_p1 - zext_ln225_5_fu_976_p1);

assign ret_V_11_fu_659_p0 = p_Result_s;

assign ret_V_11_fu_659_p3 = ((ret_V_11_fu_659_p0[0:0] == 1'b1) ? select_ln901_fu_651_p3 : ret_V_3_cast);

assign ret_V_13_fu_1095_p3 = ((p_Result_6_fu_1063_p3[0:0] == 1'b1) ? select_ln901_3_fu_1087_p3 : trunc_ln882_1_fu_1053_p4);

assign ret_V_4_fu_813_p2 = (trunc_ln_reg_1263 + 17'd1);

assign ret_V_6_fu_844_p2 = (trunc_ln712_reg_1275 - rhs_1_fu_836_p3);

assign ret_V_8_fu_1047_p2 = ($signed(sext_ln1245_3_fu_1040_p1) + $signed(zext_ln1245_fu_1043_p1));

assign ret_V_9_fu_1081_p2 = (trunc_ln882_1_fu_1053_p4 + 8'd1);

assign ret_V_fu_908_p2 = (indexy_pre_V_cast - rhs_fu_901_p3);

assign ret_fu_952_p2 = (zext_ln225_1_fu_948_p1 + zext_ln225_fu_944_p1);

assign rhs_1_fu_836_p3 = {{trunc_ln737_1_fu_832_p1}, {22'd0}};

assign rhs_fu_901_p3 = {{trunc_ln737_reg_1226_pp0_iter7_reg}, {22'd0}};

assign select_ln901_1_fu_818_p3 = ((icmp_ln902_1_fu_808_p2[0:0] == 1'b1) ? trunc_ln_reg_1263 : ret_V_4_fu_813_p2);

assign select_ln901_3_fu_1087_p3 = ((icmp_ln902_2_fu_1075_p2[0:0] == 1'b1) ? trunc_ln882_1_fu_1053_p4 : ret_V_9_fu_1081_p2);

assign select_ln901_fu_651_p3 = ((icmp_ln902_fu_645_p2[0:0] == 1'b1) ? add_i_i_i_i_i199_i : ret_V_3_cast);

assign sext_ln1245_3_fu_1040_p1 = grp_fu_1138_p3;

assign sext_ln1548_fu_740_p0 = grp_scaleCompute_17_42_20_48_16_1_s_fu_195_p_dout0;

assign sext_ln1548_fu_740_p1 = sext_ln1548_fu_740_p0;

assign tmp_2_fu_744_p1 = grp_scaleCompute_17_42_20_48_16_1_s_fu_195_p_dout0;

assign tmp_2_fu_744_p3 = tmp_2_fu_744_p1[32'd41];

assign trunc_ln395_fu_732_p1 = j_1_reg_1216[19:0];

assign trunc_ln712_fu_786_p1 = indexx_pre_V_fu_764_p3[23:0];

assign trunc_ln737_1_fu_832_p1 = idx_1_fu_825_p3[1:0];

assign trunc_ln737_fu_667_p1 = ret_V_11_fu_659_p3[1:0];

assign trunc_ln882_1_fu_1053_p4 = {{ret_V_8_fu_1047_p2[17:10]}};

assign trunc_ln902_1_fu_1071_p1 = ret_V_8_fu_1047_p2[9:0];

assign trunc_ln902_fu_782_p1 = indexx_pre_V_fu_764_p3[21:0];

assign zext_ln1049_fu_683_p1 = ret_V_11_fu_659_p3;

assign zext_ln1245_fu_1043_p1 = P4_V_fu_1033_p3;

assign zext_ln225_1_fu_948_p1 = ap_phi_reg_pp0_iter9_p_Val2_3_reg_514;

assign zext_ln225_2_fu_958_p1 = ap_phi_reg_pp0_iter9_p_Val2_s_reg_525;

assign zext_ln225_3_fu_962_p1 = p_Result_9_fu_937_p3;

assign zext_ln225_4_fu_972_p1 = ret_fu_952_p2;

assign zext_ln225_5_fu_976_p1 = ret_8_fu_966_p2;

assign zext_ln225_fu_944_p1 = p_Result_8_fu_930_p3;

assign zext_ln389_1_fu_629_p1 = ap_sig_allocacmp_j_1;

assign zext_ln389_fu_795_p1 = j_1_reg_1216_pp0_iter5_reg;

assign zext_ln395_fu_735_p1 = trunc_ln395_fu_732_p1;

assign zext_ln428_fu_862_p1 = not_cmp_i_i173_fu_857_p2;

assign zext_ln430_fu_872_p1 = idx_1_fu_825_p3;

assign zext_ln431_fu_892_p1 = idx_nxt_reg_1280;

endmodule //resize_accel_resizeNNBilinear_0_2160_3840_1_1080_1920_1_2_Pipeline_VITIS_LOOP_389_5
