// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.1 (64-bit)
// Version: 2021.1
// Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="resize_accel_resize_accel,hls_ip_2021_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xcvu9p-flgb2104-2-i,HLS_INPUT_CLOCK=4.000000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=2.920000,HLS_SYN_LAT=4147279,HLS_SYN_TPT=4147279,HLS_SYN_MEM=22,HLS_SYN_DSP=0,HLS_SYN_FF=8780,HLS_SYN_LUT=15531,HLS_VERSION=2021_1}" *)

module resize_accel (
        s_axi_control_AWVALID,
        s_axi_control_AWREADY,
        s_axi_control_AWADDR,
        s_axi_control_WVALID,
        s_axi_control_WREADY,
        s_axi_control_WDATA,
        s_axi_control_WSTRB,
        s_axi_control_ARVALID,
        s_axi_control_ARREADY,
        s_axi_control_ARADDR,
        s_axi_control_RVALID,
        s_axi_control_RREADY,
        s_axi_control_RDATA,
        s_axi_control_RRESP,
        s_axi_control_BVALID,
        s_axi_control_BREADY,
        s_axi_control_BRESP,
        ap_clk,
        ap_rst_n,
        event_done,
        interrupt,
        event_start,
        m_axi_gmem1_AWVALID,
        m_axi_gmem1_AWREADY,
        m_axi_gmem1_AWADDR,
        m_axi_gmem1_AWID,
        m_axi_gmem1_AWLEN,
        m_axi_gmem1_AWSIZE,
        m_axi_gmem1_AWBURST,
        m_axi_gmem1_AWLOCK,
        m_axi_gmem1_AWCACHE,
        m_axi_gmem1_AWPROT,
        m_axi_gmem1_AWQOS,
        m_axi_gmem1_AWREGION,
        m_axi_gmem1_AWUSER,
        m_axi_gmem1_WVALID,
        m_axi_gmem1_WREADY,
        m_axi_gmem1_WDATA,
        m_axi_gmem1_WSTRB,
        m_axi_gmem1_WLAST,
        m_axi_gmem1_WID,
        m_axi_gmem1_WUSER,
        m_axi_gmem1_ARVALID,
        m_axi_gmem1_ARREADY,
        m_axi_gmem1_ARADDR,
        m_axi_gmem1_ARID,
        m_axi_gmem1_ARLEN,
        m_axi_gmem1_ARSIZE,
        m_axi_gmem1_ARBURST,
        m_axi_gmem1_ARLOCK,
        m_axi_gmem1_ARCACHE,
        m_axi_gmem1_ARPROT,
        m_axi_gmem1_ARQOS,
        m_axi_gmem1_ARREGION,
        m_axi_gmem1_ARUSER,
        m_axi_gmem1_RVALID,
        m_axi_gmem1_RREADY,
        m_axi_gmem1_RDATA,
        m_axi_gmem1_RLAST,
        m_axi_gmem1_RID,
        m_axi_gmem1_RUSER,
        m_axi_gmem1_RRESP,
        m_axi_gmem1_BVALID,
        m_axi_gmem1_BREADY,
        m_axi_gmem1_BRESP,
        m_axi_gmem1_BID,
        m_axi_gmem1_BUSER,
        m_axi_gmem2_AWVALID,
        m_axi_gmem2_AWREADY,
        m_axi_gmem2_AWADDR,
        m_axi_gmem2_AWID,
        m_axi_gmem2_AWLEN,
        m_axi_gmem2_AWSIZE,
        m_axi_gmem2_AWBURST,
        m_axi_gmem2_AWLOCK,
        m_axi_gmem2_AWCACHE,
        m_axi_gmem2_AWPROT,
        m_axi_gmem2_AWQOS,
        m_axi_gmem2_AWREGION,
        m_axi_gmem2_AWUSER,
        m_axi_gmem2_WVALID,
        m_axi_gmem2_WREADY,
        m_axi_gmem2_WDATA,
        m_axi_gmem2_WSTRB,
        m_axi_gmem2_WLAST,
        m_axi_gmem2_WID,
        m_axi_gmem2_WUSER,
        m_axi_gmem2_ARVALID,
        m_axi_gmem2_ARREADY,
        m_axi_gmem2_ARADDR,
        m_axi_gmem2_ARID,
        m_axi_gmem2_ARLEN,
        m_axi_gmem2_ARSIZE,
        m_axi_gmem2_ARBURST,
        m_axi_gmem2_ARLOCK,
        m_axi_gmem2_ARCACHE,
        m_axi_gmem2_ARPROT,
        m_axi_gmem2_ARQOS,
        m_axi_gmem2_ARREGION,
        m_axi_gmem2_ARUSER,
        m_axi_gmem2_RVALID,
        m_axi_gmem2_RREADY,
        m_axi_gmem2_RDATA,
        m_axi_gmem2_RLAST,
        m_axi_gmem2_RID,
        m_axi_gmem2_RUSER,
        m_axi_gmem2_RRESP,
        m_axi_gmem2_BVALID,
        m_axi_gmem2_BREADY,
        m_axi_gmem2_BRESP,
        m_axi_gmem2_BID,
        m_axi_gmem2_BUSER,
        stall_start_ext,
        stall_done_ext,
        stall_start_str,
        stall_done_str,
        stall_start_int,
        stall_done_int
);

parameter    C_S_AXI_CONTROL_DATA_WIDTH = 32;
parameter    C_S_AXI_CONTROL_ADDR_WIDTH = 7;
parameter    C_S_AXI_DATA_WIDTH = 32;
parameter    C_M_AXI_GMEM1_ID_WIDTH = 1;
parameter    C_M_AXI_GMEM1_ADDR_WIDTH = 64;
parameter    C_M_AXI_GMEM1_DATA_WIDTH = 128;
parameter    C_M_AXI_GMEM1_AWUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM1_ARUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM1_WUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM1_RUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM1_BUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM1_USER_VALUE = 0;
parameter    C_M_AXI_GMEM1_PROT_VALUE = 0;
parameter    C_M_AXI_GMEM1_CACHE_VALUE = 3;
parameter    C_M_AXI_DATA_WIDTH = 32;
parameter    C_M_AXI_GMEM2_ID_WIDTH = 1;
parameter    C_M_AXI_GMEM2_ADDR_WIDTH = 64;
parameter    C_M_AXI_GMEM2_DATA_WIDTH = 128;
parameter    C_M_AXI_GMEM2_AWUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM2_ARUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM2_WUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM2_RUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM2_BUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM2_USER_VALUE = 0;
parameter    C_M_AXI_GMEM2_PROT_VALUE = 0;
parameter    C_M_AXI_GMEM2_CACHE_VALUE = 3;

parameter C_S_AXI_CONTROL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_GMEM1_WSTRB_WIDTH = (128 / 8);
parameter C_M_AXI_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_GMEM2_WSTRB_WIDTH = (128 / 8);

input   s_axi_control_AWVALID;
output   s_axi_control_AWREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_AWADDR;
input   s_axi_control_WVALID;
output   s_axi_control_WREADY;
input  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_WDATA;
input  [C_S_AXI_CONTROL_WSTRB_WIDTH - 1:0] s_axi_control_WSTRB;
input   s_axi_control_ARVALID;
output   s_axi_control_ARREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_ARADDR;
output   s_axi_control_RVALID;
input   s_axi_control_RREADY;
output  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_RDATA;
output  [1:0] s_axi_control_RRESP;
output   s_axi_control_BVALID;
input   s_axi_control_BREADY;
output  [1:0] s_axi_control_BRESP;
input   ap_clk;
input   ap_rst_n;
output   event_done;
output   interrupt;
output   event_start;
output   m_axi_gmem1_AWVALID;
input   m_axi_gmem1_AWREADY;
output  [C_M_AXI_GMEM1_ADDR_WIDTH - 1:0] m_axi_gmem1_AWADDR;
output  [C_M_AXI_GMEM1_ID_WIDTH - 1:0] m_axi_gmem1_AWID;
output  [7:0] m_axi_gmem1_AWLEN;
output  [2:0] m_axi_gmem1_AWSIZE;
output  [1:0] m_axi_gmem1_AWBURST;
output  [1:0] m_axi_gmem1_AWLOCK;
output  [3:0] m_axi_gmem1_AWCACHE;
output  [2:0] m_axi_gmem1_AWPROT;
output  [3:0] m_axi_gmem1_AWQOS;
output  [3:0] m_axi_gmem1_AWREGION;
output  [C_M_AXI_GMEM1_AWUSER_WIDTH - 1:0] m_axi_gmem1_AWUSER;
output   m_axi_gmem1_WVALID;
input   m_axi_gmem1_WREADY;
output  [C_M_AXI_GMEM1_DATA_WIDTH - 1:0] m_axi_gmem1_WDATA;
output  [C_M_AXI_GMEM1_WSTRB_WIDTH - 1:0] m_axi_gmem1_WSTRB;
output   m_axi_gmem1_WLAST;
output  [C_M_AXI_GMEM1_ID_WIDTH - 1:0] m_axi_gmem1_WID;
output  [C_M_AXI_GMEM1_WUSER_WIDTH - 1:0] m_axi_gmem1_WUSER;
output   m_axi_gmem1_ARVALID;
input   m_axi_gmem1_ARREADY;
output  [C_M_AXI_GMEM1_ADDR_WIDTH - 1:0] m_axi_gmem1_ARADDR;
output  [C_M_AXI_GMEM1_ID_WIDTH - 1:0] m_axi_gmem1_ARID;
output  [7:0] m_axi_gmem1_ARLEN;
output  [2:0] m_axi_gmem1_ARSIZE;
output  [1:0] m_axi_gmem1_ARBURST;
output  [1:0] m_axi_gmem1_ARLOCK;
output  [3:0] m_axi_gmem1_ARCACHE;
output  [2:0] m_axi_gmem1_ARPROT;
output  [3:0] m_axi_gmem1_ARQOS;
output  [3:0] m_axi_gmem1_ARREGION;
output  [C_M_AXI_GMEM1_ARUSER_WIDTH - 1:0] m_axi_gmem1_ARUSER;
input   m_axi_gmem1_RVALID;
output   m_axi_gmem1_RREADY;
input  [C_M_AXI_GMEM1_DATA_WIDTH - 1:0] m_axi_gmem1_RDATA;
input   m_axi_gmem1_RLAST;
input  [C_M_AXI_GMEM1_ID_WIDTH - 1:0] m_axi_gmem1_RID;
input  [C_M_AXI_GMEM1_RUSER_WIDTH - 1:0] m_axi_gmem1_RUSER;
input  [1:0] m_axi_gmem1_RRESP;
input   m_axi_gmem1_BVALID;
output   m_axi_gmem1_BREADY;
input  [1:0] m_axi_gmem1_BRESP;
input  [C_M_AXI_GMEM1_ID_WIDTH - 1:0] m_axi_gmem1_BID;
input  [C_M_AXI_GMEM1_BUSER_WIDTH - 1:0] m_axi_gmem1_BUSER;
output   m_axi_gmem2_AWVALID;
input   m_axi_gmem2_AWREADY;
output  [C_M_AXI_GMEM2_ADDR_WIDTH - 1:0] m_axi_gmem2_AWADDR;
output  [C_M_AXI_GMEM2_ID_WIDTH - 1:0] m_axi_gmem2_AWID;
output  [7:0] m_axi_gmem2_AWLEN;
output  [2:0] m_axi_gmem2_AWSIZE;
output  [1:0] m_axi_gmem2_AWBURST;
output  [1:0] m_axi_gmem2_AWLOCK;
output  [3:0] m_axi_gmem2_AWCACHE;
output  [2:0] m_axi_gmem2_AWPROT;
output  [3:0] m_axi_gmem2_AWQOS;
output  [3:0] m_axi_gmem2_AWREGION;
output  [C_M_AXI_GMEM2_AWUSER_WIDTH - 1:0] m_axi_gmem2_AWUSER;
output   m_axi_gmem2_WVALID;
input   m_axi_gmem2_WREADY;
output  [C_M_AXI_GMEM2_DATA_WIDTH - 1:0] m_axi_gmem2_WDATA;
output  [C_M_AXI_GMEM2_WSTRB_WIDTH - 1:0] m_axi_gmem2_WSTRB;
output   m_axi_gmem2_WLAST;
output  [C_M_AXI_GMEM2_ID_WIDTH - 1:0] m_axi_gmem2_WID;
output  [C_M_AXI_GMEM2_WUSER_WIDTH - 1:0] m_axi_gmem2_WUSER;
output   m_axi_gmem2_ARVALID;
input   m_axi_gmem2_ARREADY;
output  [C_M_AXI_GMEM2_ADDR_WIDTH - 1:0] m_axi_gmem2_ARADDR;
output  [C_M_AXI_GMEM2_ID_WIDTH - 1:0] m_axi_gmem2_ARID;
output  [7:0] m_axi_gmem2_ARLEN;
output  [2:0] m_axi_gmem2_ARSIZE;
output  [1:0] m_axi_gmem2_ARBURST;
output  [1:0] m_axi_gmem2_ARLOCK;
output  [3:0] m_axi_gmem2_ARCACHE;
output  [2:0] m_axi_gmem2_ARPROT;
output  [3:0] m_axi_gmem2_ARQOS;
output  [3:0] m_axi_gmem2_ARREGION;
output  [C_M_AXI_GMEM2_ARUSER_WIDTH - 1:0] m_axi_gmem2_ARUSER;
input   m_axi_gmem2_RVALID;
output   m_axi_gmem2_RREADY;
input  [C_M_AXI_GMEM2_DATA_WIDTH - 1:0] m_axi_gmem2_RDATA;
input   m_axi_gmem2_RLAST;
input  [C_M_AXI_GMEM2_ID_WIDTH - 1:0] m_axi_gmem2_RID;
input  [C_M_AXI_GMEM2_RUSER_WIDTH - 1:0] m_axi_gmem2_RUSER;
input  [1:0] m_axi_gmem2_RRESP;
input   m_axi_gmem2_BVALID;
output   m_axi_gmem2_BREADY;
input  [1:0] m_axi_gmem2_BRESP;
input  [C_M_AXI_GMEM2_ID_WIDTH - 1:0] m_axi_gmem2_BID;
input  [C_M_AXI_GMEM2_BUSER_WIDTH - 1:0] m_axi_gmem2_BUSER;
output   stall_start_ext;
output   stall_done_ext;
output   stall_start_str;
output   stall_done_str;
output   stall_start_int;
output   stall_done_int;

reg stall_start_ext;
reg stall_done_ext;
reg stall_start_str;
reg stall_done_str;
reg stall_start_int;
reg stall_done_int;

(* shreg_extract = "no" *) reg    ap_rst_reg_2;
(* shreg_extract = "no" *) reg    ap_rst_reg_1;
(* shreg_extract = "no" *) reg    ap_rst_n_inv;
wire   [63:0] img_inp;
wire   [63:0] img_out;
wire   [31:0] rows_in;
wire   [31:0] cols_in;
wire   [31:0] rows_out;
wire   [31:0] cols_out;
wire    ap_start;
wire    ap_ready;
wire    ap_done;
wire    ap_continue;
wire    ap_idle;
wire    gmem1_AWREADY;
wire    gmem1_WREADY;
wire    gmem1_ARREADY;
wire    gmem1_RVALID;
wire   [127:0] gmem1_RDATA;
wire    gmem1_RLAST;
wire   [0:0] gmem1_RID;
wire   [0:0] gmem1_RUSER;
wire   [1:0] gmem1_RRESP;
wire    gmem1_BVALID;
wire   [1:0] gmem1_BRESP;
wire   [0:0] gmem1_BID;
wire   [0:0] gmem1_BUSER;
wire    gmem2_AWREADY;
wire    gmem2_WREADY;
wire    gmem2_ARREADY;
wire    gmem2_RVALID;
wire   [127:0] gmem2_RDATA;
wire    gmem2_RLAST;
wire   [0:0] gmem2_RID;
wire   [0:0] gmem2_RUSER;
wire   [1:0] gmem2_RRESP;
wire    gmem2_BVALID;
wire   [1:0] gmem2_BRESP;
wire   [0:0] gmem2_BID;
wire   [0:0] gmem2_BUSER;
wire    entry_proc7_U0_ap_start;
wire    entry_proc7_U0_ap_done;
wire    entry_proc7_U0_ap_continue;
wire    entry_proc7_U0_ap_idle;
wire    entry_proc7_U0_ap_ready;
wire   [63:0] entry_proc7_U0_ap_return_0;
wire   [63:0] entry_proc7_U0_ap_return_1;
wire    entry_proc7_U0_ap_ext_blocking_n;
wire    entry_proc7_U0_ap_str_blocking_n;
wire    entry_proc7_U0_ap_int_blocking_n;
wire    ap_channel_done_img_out_c_channel;
wire    img_out_c_channel_full_n;
reg    ap_sync_reg_channel_write_img_out_c_channel;
wire    ap_sync_channel_write_img_out_c_channel;
wire    ap_channel_done_img_inp_c_channel;
wire    img_inp_c_channel_full_n;
reg    ap_sync_reg_channel_write_img_inp_c_channel;
wire    ap_sync_channel_write_img_inp_c_channel;
wire    Block_ZN2xf2cv3MatILi0ELi2160ELi3840ELi1ELi2EEC2Eii_exit1_proc_U0_ap_start;
wire    Block_ZN2xf2cv3MatILi0ELi2160ELi3840ELi1ELi2EEC2Eii_exit1_proc_U0_ap_done;
wire    Block_ZN2xf2cv3MatILi0ELi2160ELi3840ELi1ELi2EEC2Eii_exit1_proc_U0_ap_continue;
wire    Block_ZN2xf2cv3MatILi0ELi2160ELi3840ELi1ELi2EEC2Eii_exit1_proc_U0_ap_idle;
wire    Block_ZN2xf2cv3MatILi0ELi2160ELi3840ELi1ELi2EEC2Eii_exit1_proc_U0_ap_ready;
wire   [31:0] Block_ZN2xf2cv3MatILi0ELi2160ELi3840ELi1ELi2EEC2Eii_exit1_proc_U0_ap_return_0;
wire   [31:0] Block_ZN2xf2cv3MatILi0ELi2160ELi3840ELi1ELi2EEC2Eii_exit1_proc_U0_ap_return_1;
wire   [31:0] Block_ZN2xf2cv3MatILi0ELi2160ELi3840ELi1ELi2EEC2Eii_exit1_proc_U0_ap_return_2;
wire   [31:0] Block_ZN2xf2cv3MatILi0ELi2160ELi3840ELi1ELi2EEC2Eii_exit1_proc_U0_ap_return_3;
wire    Block_ZN2xf2cv3MatILi0ELi2160ELi3840ELi1ELi2EEC2Eii_exit1_proc_U0_ap_ext_blocking_n;
wire    Block_ZN2xf2cv3MatILi0ELi2160ELi3840ELi1ELi2EEC2Eii_exit1_proc_U0_ap_str_blocking_n;
wire    Block_ZN2xf2cv3MatILi0ELi2160ELi3840ELi1ELi2EEC2Eii_exit1_proc_U0_ap_int_blocking_n;
wire    ap_channel_done_out_mat_cols_c12_channel;
wire    out_mat_cols_c12_channel_full_n;
reg    ap_sync_reg_channel_write_out_mat_cols_c12_channel;
wire    ap_sync_channel_write_out_mat_cols_c12_channel;
wire    ap_channel_done_out_mat_rows_c11_channel;
wire    out_mat_rows_c11_channel_full_n;
reg    ap_sync_reg_channel_write_out_mat_rows_c11_channel;
wire    ap_sync_channel_write_out_mat_rows_c11_channel;
wire    ap_channel_done_in_mat_cols_c10_channel;
wire    in_mat_cols_c10_channel_full_n;
reg    ap_sync_reg_channel_write_in_mat_cols_c10_channel;
wire    ap_sync_channel_write_in_mat_cols_c10_channel;
wire    ap_channel_done_in_mat_rows_c9_channel;
wire    in_mat_rows_c9_channel_full_n;
reg    ap_sync_reg_channel_write_in_mat_rows_c9_channel;
wire    ap_sync_channel_write_in_mat_rows_c9_channel;
wire    Array2xfMat_128_0_2160_3840_1_U0_ap_start;
wire    Array2xfMat_128_0_2160_3840_1_U0_ap_done;
wire    Array2xfMat_128_0_2160_3840_1_U0_ap_continue;
wire    Array2xfMat_128_0_2160_3840_1_U0_ap_idle;
wire    Array2xfMat_128_0_2160_3840_1_U0_ap_ready;
wire    Array2xfMat_128_0_2160_3840_1_U0_m_axi_gmem1_AWVALID;
wire   [63:0] Array2xfMat_128_0_2160_3840_1_U0_m_axi_gmem1_AWADDR;
wire   [0:0] Array2xfMat_128_0_2160_3840_1_U0_m_axi_gmem1_AWID;
wire   [31:0] Array2xfMat_128_0_2160_3840_1_U0_m_axi_gmem1_AWLEN;
wire   [2:0] Array2xfMat_128_0_2160_3840_1_U0_m_axi_gmem1_AWSIZE;
wire   [1:0] Array2xfMat_128_0_2160_3840_1_U0_m_axi_gmem1_AWBURST;
wire   [1:0] Array2xfMat_128_0_2160_3840_1_U0_m_axi_gmem1_AWLOCK;
wire   [3:0] Array2xfMat_128_0_2160_3840_1_U0_m_axi_gmem1_AWCACHE;
wire   [2:0] Array2xfMat_128_0_2160_3840_1_U0_m_axi_gmem1_AWPROT;
wire   [3:0] Array2xfMat_128_0_2160_3840_1_U0_m_axi_gmem1_AWQOS;
wire   [3:0] Array2xfMat_128_0_2160_3840_1_U0_m_axi_gmem1_AWREGION;
wire   [0:0] Array2xfMat_128_0_2160_3840_1_U0_m_axi_gmem1_AWUSER;
wire    Array2xfMat_128_0_2160_3840_1_U0_m_axi_gmem1_WVALID;
wire   [127:0] Array2xfMat_128_0_2160_3840_1_U0_m_axi_gmem1_WDATA;
wire   [15:0] Array2xfMat_128_0_2160_3840_1_U0_m_axi_gmem1_WSTRB;
wire    Array2xfMat_128_0_2160_3840_1_U0_m_axi_gmem1_WLAST;
wire   [0:0] Array2xfMat_128_0_2160_3840_1_U0_m_axi_gmem1_WID;
wire   [0:0] Array2xfMat_128_0_2160_3840_1_U0_m_axi_gmem1_WUSER;
wire    Array2xfMat_128_0_2160_3840_1_U0_m_axi_gmem1_ARVALID;
wire   [63:0] Array2xfMat_128_0_2160_3840_1_U0_m_axi_gmem1_ARADDR;
wire   [0:0] Array2xfMat_128_0_2160_3840_1_U0_m_axi_gmem1_ARID;
wire   [31:0] Array2xfMat_128_0_2160_3840_1_U0_m_axi_gmem1_ARLEN;
wire   [2:0] Array2xfMat_128_0_2160_3840_1_U0_m_axi_gmem1_ARSIZE;
wire   [1:0] Array2xfMat_128_0_2160_3840_1_U0_m_axi_gmem1_ARBURST;
wire   [1:0] Array2xfMat_128_0_2160_3840_1_U0_m_axi_gmem1_ARLOCK;
wire   [3:0] Array2xfMat_128_0_2160_3840_1_U0_m_axi_gmem1_ARCACHE;
wire   [2:0] Array2xfMat_128_0_2160_3840_1_U0_m_axi_gmem1_ARPROT;
wire   [3:0] Array2xfMat_128_0_2160_3840_1_U0_m_axi_gmem1_ARQOS;
wire   [3:0] Array2xfMat_128_0_2160_3840_1_U0_m_axi_gmem1_ARREGION;
wire   [0:0] Array2xfMat_128_0_2160_3840_1_U0_m_axi_gmem1_ARUSER;
wire    Array2xfMat_128_0_2160_3840_1_U0_m_axi_gmem1_RREADY;
wire    Array2xfMat_128_0_2160_3840_1_U0_m_axi_gmem1_BREADY;
wire   [7:0] Array2xfMat_128_0_2160_3840_1_U0_in_mat_420_din;
wire    Array2xfMat_128_0_2160_3840_1_U0_in_mat_420_write;
wire   [31:0] Array2xfMat_128_0_2160_3840_1_U0_in_mat_rows_c_din;
wire    Array2xfMat_128_0_2160_3840_1_U0_in_mat_rows_c_write;
wire   [31:0] Array2xfMat_128_0_2160_3840_1_U0_in_mat_cols_c_din;
wire    Array2xfMat_128_0_2160_3840_1_U0_in_mat_cols_c_write;
wire    Array2xfMat_128_0_2160_3840_1_U0_ap_ext_blocking_n;
wire    Array2xfMat_128_0_2160_3840_1_U0_ap_str_blocking_n;
wire    Array2xfMat_128_0_2160_3840_1_U0_ap_int_blocking_n;
wire    resize_1_0_2160_3840_1080_1920_1_2_U0_ap_start;
wire    resize_1_0_2160_3840_1080_1920_1_2_U0_ap_done;
wire    resize_1_0_2160_3840_1080_1920_1_2_U0_ap_continue;
wire    resize_1_0_2160_3840_1080_1920_1_2_U0_ap_idle;
wire    resize_1_0_2160_3840_1080_1920_1_2_U0_ap_ready;
wire    resize_1_0_2160_3840_1080_1920_1_2_U0_p_src_rows_read;
wire    resize_1_0_2160_3840_1080_1920_1_2_U0_p_src_cols_read;
wire    resize_1_0_2160_3840_1080_1920_1_2_U0_in_mat_420_read;
wire   [7:0] resize_1_0_2160_3840_1080_1920_1_2_U0_out_mat_421_din;
wire    resize_1_0_2160_3840_1080_1920_1_2_U0_out_mat_421_write;
wire   [31:0] resize_1_0_2160_3840_1080_1920_1_2_U0_out_mat_rows_c_din;
wire    resize_1_0_2160_3840_1080_1920_1_2_U0_out_mat_rows_c_write;
wire   [31:0] resize_1_0_2160_3840_1080_1920_1_2_U0_out_mat_cols_c_din;
wire    resize_1_0_2160_3840_1080_1920_1_2_U0_out_mat_cols_c_write;
wire    resize_1_0_2160_3840_1080_1920_1_2_U0_ap_ext_blocking_n;
wire    resize_1_0_2160_3840_1080_1920_1_2_U0_ap_str_blocking_n;
wire    resize_1_0_2160_3840_1080_1920_1_2_U0_ap_int_blocking_n;
wire    xfMat2Array_128_0_1080_1920_1_1_U0_ap_start;
wire    xfMat2Array_128_0_1080_1920_1_1_U0_ap_done;
wire    xfMat2Array_128_0_1080_1920_1_1_U0_ap_continue;
wire    xfMat2Array_128_0_1080_1920_1_1_U0_ap_idle;
wire    xfMat2Array_128_0_1080_1920_1_1_U0_ap_ready;
wire    xfMat2Array_128_0_1080_1920_1_1_U0_srcMat_rows_read;
wire    xfMat2Array_128_0_1080_1920_1_1_U0_srcMat_cols_read;
wire    xfMat2Array_128_0_1080_1920_1_1_U0_out_mat_421_read;
wire    xfMat2Array_128_0_1080_1920_1_1_U0_m_axi_gmem2_AWVALID;
wire   [63:0] xfMat2Array_128_0_1080_1920_1_1_U0_m_axi_gmem2_AWADDR;
wire   [0:0] xfMat2Array_128_0_1080_1920_1_1_U0_m_axi_gmem2_AWID;
wire   [31:0] xfMat2Array_128_0_1080_1920_1_1_U0_m_axi_gmem2_AWLEN;
wire   [2:0] xfMat2Array_128_0_1080_1920_1_1_U0_m_axi_gmem2_AWSIZE;
wire   [1:0] xfMat2Array_128_0_1080_1920_1_1_U0_m_axi_gmem2_AWBURST;
wire   [1:0] xfMat2Array_128_0_1080_1920_1_1_U0_m_axi_gmem2_AWLOCK;
wire   [3:0] xfMat2Array_128_0_1080_1920_1_1_U0_m_axi_gmem2_AWCACHE;
wire   [2:0] xfMat2Array_128_0_1080_1920_1_1_U0_m_axi_gmem2_AWPROT;
wire   [3:0] xfMat2Array_128_0_1080_1920_1_1_U0_m_axi_gmem2_AWQOS;
wire   [3:0] xfMat2Array_128_0_1080_1920_1_1_U0_m_axi_gmem2_AWREGION;
wire   [0:0] xfMat2Array_128_0_1080_1920_1_1_U0_m_axi_gmem2_AWUSER;
wire    xfMat2Array_128_0_1080_1920_1_1_U0_m_axi_gmem2_WVALID;
wire   [127:0] xfMat2Array_128_0_1080_1920_1_1_U0_m_axi_gmem2_WDATA;
wire   [15:0] xfMat2Array_128_0_1080_1920_1_1_U0_m_axi_gmem2_WSTRB;
wire    xfMat2Array_128_0_1080_1920_1_1_U0_m_axi_gmem2_WLAST;
wire   [0:0] xfMat2Array_128_0_1080_1920_1_1_U0_m_axi_gmem2_WID;
wire   [0:0] xfMat2Array_128_0_1080_1920_1_1_U0_m_axi_gmem2_WUSER;
wire    xfMat2Array_128_0_1080_1920_1_1_U0_m_axi_gmem2_ARVALID;
wire   [63:0] xfMat2Array_128_0_1080_1920_1_1_U0_m_axi_gmem2_ARADDR;
wire   [0:0] xfMat2Array_128_0_1080_1920_1_1_U0_m_axi_gmem2_ARID;
wire   [31:0] xfMat2Array_128_0_1080_1920_1_1_U0_m_axi_gmem2_ARLEN;
wire   [2:0] xfMat2Array_128_0_1080_1920_1_1_U0_m_axi_gmem2_ARSIZE;
wire   [1:0] xfMat2Array_128_0_1080_1920_1_1_U0_m_axi_gmem2_ARBURST;
wire   [1:0] xfMat2Array_128_0_1080_1920_1_1_U0_m_axi_gmem2_ARLOCK;
wire   [3:0] xfMat2Array_128_0_1080_1920_1_1_U0_m_axi_gmem2_ARCACHE;
wire   [2:0] xfMat2Array_128_0_1080_1920_1_1_U0_m_axi_gmem2_ARPROT;
wire   [3:0] xfMat2Array_128_0_1080_1920_1_1_U0_m_axi_gmem2_ARQOS;
wire   [3:0] xfMat2Array_128_0_1080_1920_1_1_U0_m_axi_gmem2_ARREGION;
wire   [0:0] xfMat2Array_128_0_1080_1920_1_1_U0_m_axi_gmem2_ARUSER;
wire    xfMat2Array_128_0_1080_1920_1_1_U0_m_axi_gmem2_RREADY;
wire    xfMat2Array_128_0_1080_1920_1_1_U0_m_axi_gmem2_BREADY;
wire    xfMat2Array_128_0_1080_1920_1_1_U0_ap_ext_blocking_n;
wire    xfMat2Array_128_0_1080_1920_1_1_U0_ap_str_blocking_n;
wire    xfMat2Array_128_0_1080_1920_1_1_U0_ap_int_blocking_n;
wire   [63:0] img_inp_c_channel_dout;
wire    img_inp_c_channel_empty_n;
wire   [63:0] img_out_c_channel_dout;
wire    img_out_c_channel_empty_n;
wire   [31:0] in_mat_rows_c9_channel_dout;
wire    in_mat_rows_c9_channel_empty_n;
wire   [31:0] in_mat_cols_c10_channel_dout;
wire    in_mat_cols_c10_channel_empty_n;
wire   [31:0] out_mat_rows_c11_channel_dout;
wire    out_mat_rows_c11_channel_empty_n;
wire   [31:0] out_mat_cols_c12_channel_dout;
wire    out_mat_cols_c12_channel_empty_n;
wire    in_mat_data_full_n;
wire   [7:0] in_mat_data_dout;
wire    in_mat_data_empty_n;
wire    in_mat_rows_c_full_n;
wire   [31:0] in_mat_rows_c_dout;
wire    in_mat_rows_c_empty_n;
wire    in_mat_cols_c_full_n;
wire   [31:0] in_mat_cols_c_dout;
wire    in_mat_cols_c_empty_n;
wire    out_mat_data_full_n;
wire   [7:0] out_mat_data_dout;
wire    out_mat_data_empty_n;
wire    out_mat_rows_c_full_n;
wire   [31:0] out_mat_rows_c_dout;
wire    out_mat_rows_c_empty_n;
wire    out_mat_cols_c_full_n;
wire   [31:0] out_mat_cols_c_dout;
wire    out_mat_cols_c_empty_n;
wire    ap_sync_ready;
reg    ap_sync_reg_entry_proc7_U0_ap_ready;
wire    ap_sync_entry_proc7_U0_ap_ready;
reg    ap_sync_reg_Block_ZN2xf2cv3MatILi0ELi2160ELi3840ELi1ELi2EEC2Eii_exit1_proc_U0_ap_ready;
wire    ap_sync_Block_ZN2xf2cv3MatILi0ELi2160ELi3840ELi1ELi2EEC2Eii_exit1_proc_U0_ap_ready;
reg    ap_sync_reg_Array2xfMat_128_0_2160_3840_1_U0_ap_ready;
wire    ap_sync_Array2xfMat_128_0_2160_3840_1_U0_ap_ready;
wire    ap_ext_blocking_cur_n;
wire    ap_str_blocking_cur_n;
wire    ap_int_blocking_cur_n;
wire    ap_ext_blocking_sub_n;
wire    ap_str_blocking_sub_n;
wire    ap_int_blocking_sub_n;
wire    ap_ext_blocking_n;
wire    ap_str_blocking_n;
wire    ap_int_blocking_n;
reg    ap_ext_blocking_n_reg;
reg    ap_str_blocking_n_reg;
reg    ap_int_blocking_n_reg;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_rst_reg_2 = 1'b1;
#0 ap_rst_reg_1 = 1'b1;
#0 ap_rst_n_inv = 1'b1;
#0 ap_sync_reg_channel_write_img_out_c_channel = 1'b0;
#0 ap_sync_reg_channel_write_img_inp_c_channel = 1'b0;
#0 ap_sync_reg_channel_write_out_mat_cols_c12_channel = 1'b0;
#0 ap_sync_reg_channel_write_out_mat_rows_c11_channel = 1'b0;
#0 ap_sync_reg_channel_write_in_mat_cols_c10_channel = 1'b0;
#0 ap_sync_reg_channel_write_in_mat_rows_c9_channel = 1'b0;
#0 ap_sync_reg_entry_proc7_U0_ap_ready = 1'b0;
#0 ap_sync_reg_Block_ZN2xf2cv3MatILi0ELi2160ELi3840ELi1ELi2EEC2Eii_exit1_proc_U0_ap_ready = 1'b0;
#0 ap_sync_reg_Array2xfMat_128_0_2160_3840_1_U0_ap_ready = 1'b0;
end

resize_accel_control_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CONTROL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CONTROL_DATA_WIDTH ))
control_s_axi_U(
    .AWVALID(s_axi_control_AWVALID),
    .AWREADY(s_axi_control_AWREADY),
    .AWADDR(s_axi_control_AWADDR),
    .WVALID(s_axi_control_WVALID),
    .WREADY(s_axi_control_WREADY),
    .WDATA(s_axi_control_WDATA),
    .WSTRB(s_axi_control_WSTRB),
    .ARVALID(s_axi_control_ARVALID),
    .ARREADY(s_axi_control_ARREADY),
    .ARADDR(s_axi_control_ARADDR),
    .RVALID(s_axi_control_RVALID),
    .RREADY(s_axi_control_RREADY),
    .RDATA(s_axi_control_RDATA),
    .RRESP(s_axi_control_RRESP),
    .BVALID(s_axi_control_BVALID),
    .BREADY(s_axi_control_BREADY),
    .BRESP(s_axi_control_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .img_inp(img_inp),
    .img_out(img_out),
    .rows_in(rows_in),
    .cols_in(cols_in),
    .rows_out(rows_out),
    .cols_out(cols_out),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .event_start(event_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_continue(ap_continue),
    .ap_idle(ap_idle)
);

resize_accel_gmem1_m_axi #(
    .CONSERVATIVE( 1 ),
    .USER_DW( 128 ),
    .USER_AW( 64 ),
    .USER_MAXREQS( 69 ),
    .NUM_READ_OUTSTANDING( 16 ),
    .NUM_WRITE_OUTSTANDING( 16 ),
    .MAX_READ_BURST_LENGTH( 16 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_GMEM1_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_GMEM1_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_GMEM1_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_GMEM1_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_GMEM1_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_GMEM1_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_GMEM1_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_GMEM1_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_GMEM1_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_GMEM1_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_GMEM1_CACHE_VALUE ))
gmem1_m_axi_U(
    .AWVALID(m_axi_gmem1_AWVALID),
    .AWREADY(m_axi_gmem1_AWREADY),
    .AWADDR(m_axi_gmem1_AWADDR),
    .AWID(m_axi_gmem1_AWID),
    .AWLEN(m_axi_gmem1_AWLEN),
    .AWSIZE(m_axi_gmem1_AWSIZE),
    .AWBURST(m_axi_gmem1_AWBURST),
    .AWLOCK(m_axi_gmem1_AWLOCK),
    .AWCACHE(m_axi_gmem1_AWCACHE),
    .AWPROT(m_axi_gmem1_AWPROT),
    .AWQOS(m_axi_gmem1_AWQOS),
    .AWREGION(m_axi_gmem1_AWREGION),
    .AWUSER(m_axi_gmem1_AWUSER),
    .WVALID(m_axi_gmem1_WVALID),
    .WREADY(m_axi_gmem1_WREADY),
    .WDATA(m_axi_gmem1_WDATA),
    .WSTRB(m_axi_gmem1_WSTRB),
    .WLAST(m_axi_gmem1_WLAST),
    .WID(m_axi_gmem1_WID),
    .WUSER(m_axi_gmem1_WUSER),
    .ARVALID(m_axi_gmem1_ARVALID),
    .ARREADY(m_axi_gmem1_ARREADY),
    .ARADDR(m_axi_gmem1_ARADDR),
    .ARID(m_axi_gmem1_ARID),
    .ARLEN(m_axi_gmem1_ARLEN),
    .ARSIZE(m_axi_gmem1_ARSIZE),
    .ARBURST(m_axi_gmem1_ARBURST),
    .ARLOCK(m_axi_gmem1_ARLOCK),
    .ARCACHE(m_axi_gmem1_ARCACHE),
    .ARPROT(m_axi_gmem1_ARPROT),
    .ARQOS(m_axi_gmem1_ARQOS),
    .ARREGION(m_axi_gmem1_ARREGION),
    .ARUSER(m_axi_gmem1_ARUSER),
    .RVALID(m_axi_gmem1_RVALID),
    .RREADY(m_axi_gmem1_RREADY),
    .RDATA(m_axi_gmem1_RDATA),
    .RLAST(m_axi_gmem1_RLAST),
    .RID(m_axi_gmem1_RID),
    .RUSER(m_axi_gmem1_RUSER),
    .RRESP(m_axi_gmem1_RRESP),
    .BVALID(m_axi_gmem1_BVALID),
    .BREADY(m_axi_gmem1_BREADY),
    .BRESP(m_axi_gmem1_BRESP),
    .BID(m_axi_gmem1_BID),
    .BUSER(m_axi_gmem1_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_ARVALID(Array2xfMat_128_0_2160_3840_1_U0_m_axi_gmem1_ARVALID),
    .I_ARREADY(gmem1_ARREADY),
    .I_ARADDR(Array2xfMat_128_0_2160_3840_1_U0_m_axi_gmem1_ARADDR),
    .I_ARID(Array2xfMat_128_0_2160_3840_1_U0_m_axi_gmem1_ARID),
    .I_ARLEN(Array2xfMat_128_0_2160_3840_1_U0_m_axi_gmem1_ARLEN),
    .I_ARSIZE(Array2xfMat_128_0_2160_3840_1_U0_m_axi_gmem1_ARSIZE),
    .I_ARLOCK(Array2xfMat_128_0_2160_3840_1_U0_m_axi_gmem1_ARLOCK),
    .I_ARCACHE(Array2xfMat_128_0_2160_3840_1_U0_m_axi_gmem1_ARCACHE),
    .I_ARQOS(Array2xfMat_128_0_2160_3840_1_U0_m_axi_gmem1_ARQOS),
    .I_ARPROT(Array2xfMat_128_0_2160_3840_1_U0_m_axi_gmem1_ARPROT),
    .I_ARUSER(Array2xfMat_128_0_2160_3840_1_U0_m_axi_gmem1_ARUSER),
    .I_ARBURST(Array2xfMat_128_0_2160_3840_1_U0_m_axi_gmem1_ARBURST),
    .I_ARREGION(Array2xfMat_128_0_2160_3840_1_U0_m_axi_gmem1_ARREGION),
    .I_RVALID(gmem1_RVALID),
    .I_RREADY(Array2xfMat_128_0_2160_3840_1_U0_m_axi_gmem1_RREADY),
    .I_RDATA(gmem1_RDATA),
    .I_RID(gmem1_RID),
    .I_RUSER(gmem1_RUSER),
    .I_RRESP(gmem1_RRESP),
    .I_RLAST(gmem1_RLAST),
    .I_AWVALID(1'b0),
    .I_AWREADY(gmem1_AWREADY),
    .I_AWADDR(64'd0),
    .I_AWID(1'd0),
    .I_AWLEN(32'd0),
    .I_AWSIZE(3'd0),
    .I_AWLOCK(2'd0),
    .I_AWCACHE(4'd0),
    .I_AWQOS(4'd0),
    .I_AWPROT(3'd0),
    .I_AWUSER(1'd0),
    .I_AWBURST(2'd0),
    .I_AWREGION(4'd0),
    .I_WVALID(1'b0),
    .I_WREADY(gmem1_WREADY),
    .I_WDATA(128'd0),
    .I_WID(1'd0),
    .I_WUSER(1'd0),
    .I_WLAST(1'b0),
    .I_WSTRB(16'd0),
    .I_BVALID(gmem1_BVALID),
    .I_BREADY(1'b0),
    .I_BRESP(gmem1_BRESP),
    .I_BID(gmem1_BID),
    .I_BUSER(gmem1_BUSER)
);

resize_accel_gmem2_m_axi #(
    .CONSERVATIVE( 1 ),
    .USER_DW( 128 ),
    .USER_AW( 64 ),
    .USER_MAXREQS( 69 ),
    .NUM_READ_OUTSTANDING( 16 ),
    .NUM_WRITE_OUTSTANDING( 16 ),
    .MAX_READ_BURST_LENGTH( 16 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_GMEM2_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_GMEM2_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_GMEM2_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_GMEM2_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_GMEM2_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_GMEM2_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_GMEM2_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_GMEM2_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_GMEM2_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_GMEM2_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_GMEM2_CACHE_VALUE ))
gmem2_m_axi_U(
    .AWVALID(m_axi_gmem2_AWVALID),
    .AWREADY(m_axi_gmem2_AWREADY),
    .AWADDR(m_axi_gmem2_AWADDR),
    .AWID(m_axi_gmem2_AWID),
    .AWLEN(m_axi_gmem2_AWLEN),
    .AWSIZE(m_axi_gmem2_AWSIZE),
    .AWBURST(m_axi_gmem2_AWBURST),
    .AWLOCK(m_axi_gmem2_AWLOCK),
    .AWCACHE(m_axi_gmem2_AWCACHE),
    .AWPROT(m_axi_gmem2_AWPROT),
    .AWQOS(m_axi_gmem2_AWQOS),
    .AWREGION(m_axi_gmem2_AWREGION),
    .AWUSER(m_axi_gmem2_AWUSER),
    .WVALID(m_axi_gmem2_WVALID),
    .WREADY(m_axi_gmem2_WREADY),
    .WDATA(m_axi_gmem2_WDATA),
    .WSTRB(m_axi_gmem2_WSTRB),
    .WLAST(m_axi_gmem2_WLAST),
    .WID(m_axi_gmem2_WID),
    .WUSER(m_axi_gmem2_WUSER),
    .ARVALID(m_axi_gmem2_ARVALID),
    .ARREADY(m_axi_gmem2_ARREADY),
    .ARADDR(m_axi_gmem2_ARADDR),
    .ARID(m_axi_gmem2_ARID),
    .ARLEN(m_axi_gmem2_ARLEN),
    .ARSIZE(m_axi_gmem2_ARSIZE),
    .ARBURST(m_axi_gmem2_ARBURST),
    .ARLOCK(m_axi_gmem2_ARLOCK),
    .ARCACHE(m_axi_gmem2_ARCACHE),
    .ARPROT(m_axi_gmem2_ARPROT),
    .ARQOS(m_axi_gmem2_ARQOS),
    .ARREGION(m_axi_gmem2_ARREGION),
    .ARUSER(m_axi_gmem2_ARUSER),
    .RVALID(m_axi_gmem2_RVALID),
    .RREADY(m_axi_gmem2_RREADY),
    .RDATA(m_axi_gmem2_RDATA),
    .RLAST(m_axi_gmem2_RLAST),
    .RID(m_axi_gmem2_RID),
    .RUSER(m_axi_gmem2_RUSER),
    .RRESP(m_axi_gmem2_RRESP),
    .BVALID(m_axi_gmem2_BVALID),
    .BREADY(m_axi_gmem2_BREADY),
    .BRESP(m_axi_gmem2_BRESP),
    .BID(m_axi_gmem2_BID),
    .BUSER(m_axi_gmem2_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_ARVALID(1'b0),
    .I_ARREADY(gmem2_ARREADY),
    .I_ARADDR(64'd0),
    .I_ARID(1'd0),
    .I_ARLEN(32'd0),
    .I_ARSIZE(3'd0),
    .I_ARLOCK(2'd0),
    .I_ARCACHE(4'd0),
    .I_ARQOS(4'd0),
    .I_ARPROT(3'd0),
    .I_ARUSER(1'd0),
    .I_ARBURST(2'd0),
    .I_ARREGION(4'd0),
    .I_RVALID(gmem2_RVALID),
    .I_RREADY(1'b0),
    .I_RDATA(gmem2_RDATA),
    .I_RID(gmem2_RID),
    .I_RUSER(gmem2_RUSER),
    .I_RRESP(gmem2_RRESP),
    .I_RLAST(gmem2_RLAST),
    .I_AWVALID(xfMat2Array_128_0_1080_1920_1_1_U0_m_axi_gmem2_AWVALID),
    .I_AWREADY(gmem2_AWREADY),
    .I_AWADDR(xfMat2Array_128_0_1080_1920_1_1_U0_m_axi_gmem2_AWADDR),
    .I_AWID(xfMat2Array_128_0_1080_1920_1_1_U0_m_axi_gmem2_AWID),
    .I_AWLEN(xfMat2Array_128_0_1080_1920_1_1_U0_m_axi_gmem2_AWLEN),
    .I_AWSIZE(xfMat2Array_128_0_1080_1920_1_1_U0_m_axi_gmem2_AWSIZE),
    .I_AWLOCK(xfMat2Array_128_0_1080_1920_1_1_U0_m_axi_gmem2_AWLOCK),
    .I_AWCACHE(xfMat2Array_128_0_1080_1920_1_1_U0_m_axi_gmem2_AWCACHE),
    .I_AWQOS(xfMat2Array_128_0_1080_1920_1_1_U0_m_axi_gmem2_AWQOS),
    .I_AWPROT(xfMat2Array_128_0_1080_1920_1_1_U0_m_axi_gmem2_AWPROT),
    .I_AWUSER(xfMat2Array_128_0_1080_1920_1_1_U0_m_axi_gmem2_AWUSER),
    .I_AWBURST(xfMat2Array_128_0_1080_1920_1_1_U0_m_axi_gmem2_AWBURST),
    .I_AWREGION(xfMat2Array_128_0_1080_1920_1_1_U0_m_axi_gmem2_AWREGION),
    .I_WVALID(xfMat2Array_128_0_1080_1920_1_1_U0_m_axi_gmem2_WVALID),
    .I_WREADY(gmem2_WREADY),
    .I_WDATA(xfMat2Array_128_0_1080_1920_1_1_U0_m_axi_gmem2_WDATA),
    .I_WID(xfMat2Array_128_0_1080_1920_1_1_U0_m_axi_gmem2_WID),
    .I_WUSER(xfMat2Array_128_0_1080_1920_1_1_U0_m_axi_gmem2_WUSER),
    .I_WLAST(xfMat2Array_128_0_1080_1920_1_1_U0_m_axi_gmem2_WLAST),
    .I_WSTRB(xfMat2Array_128_0_1080_1920_1_1_U0_m_axi_gmem2_WSTRB),
    .I_BVALID(gmem2_BVALID),
    .I_BREADY(xfMat2Array_128_0_1080_1920_1_1_U0_m_axi_gmem2_BREADY),
    .I_BRESP(gmem2_BRESP),
    .I_BID(gmem2_BID),
    .I_BUSER(gmem2_BUSER)
);

resize_accel_entry_proc7 entry_proc7_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(entry_proc7_U0_ap_start),
    .ap_done(entry_proc7_U0_ap_done),
    .ap_continue(entry_proc7_U0_ap_continue),
    .ap_idle(entry_proc7_U0_ap_idle),
    .ap_ready(entry_proc7_U0_ap_ready),
    .img_inp(img_inp),
    .img_out(img_out),
    .ap_return_0(entry_proc7_U0_ap_return_0),
    .ap_return_1(entry_proc7_U0_ap_return_1),
    .ap_ext_blocking_n(entry_proc7_U0_ap_ext_blocking_n),
    .ap_str_blocking_n(entry_proc7_U0_ap_str_blocking_n),
    .ap_int_blocking_n(entry_proc7_U0_ap_int_blocking_n)
);

resize_accel_Block_ZN2xf2cv3MatILi0ELi2160ELi3840ELi1ELi2EEC2Eii_exit1_proc Block_ZN2xf2cv3MatILi0ELi2160ELi3840ELi1ELi2EEC2Eii_exit1_proc_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(Block_ZN2xf2cv3MatILi0ELi2160ELi3840ELi1ELi2EEC2Eii_exit1_proc_U0_ap_start),
    .ap_done(Block_ZN2xf2cv3MatILi0ELi2160ELi3840ELi1ELi2EEC2Eii_exit1_proc_U0_ap_done),
    .ap_continue(Block_ZN2xf2cv3MatILi0ELi2160ELi3840ELi1ELi2EEC2Eii_exit1_proc_U0_ap_continue),
    .ap_idle(Block_ZN2xf2cv3MatILi0ELi2160ELi3840ELi1ELi2EEC2Eii_exit1_proc_U0_ap_idle),
    .ap_ready(Block_ZN2xf2cv3MatILi0ELi2160ELi3840ELi1ELi2EEC2Eii_exit1_proc_U0_ap_ready),
    .rows_in(rows_in),
    .cols_in(cols_in),
    .rows_out(rows_out),
    .cols_out(cols_out),
    .ap_return_0(Block_ZN2xf2cv3MatILi0ELi2160ELi3840ELi1ELi2EEC2Eii_exit1_proc_U0_ap_return_0),
    .ap_return_1(Block_ZN2xf2cv3MatILi0ELi2160ELi3840ELi1ELi2EEC2Eii_exit1_proc_U0_ap_return_1),
    .ap_return_2(Block_ZN2xf2cv3MatILi0ELi2160ELi3840ELi1ELi2EEC2Eii_exit1_proc_U0_ap_return_2),
    .ap_return_3(Block_ZN2xf2cv3MatILi0ELi2160ELi3840ELi1ELi2EEC2Eii_exit1_proc_U0_ap_return_3),
    .ap_ext_blocking_n(Block_ZN2xf2cv3MatILi0ELi2160ELi3840ELi1ELi2EEC2Eii_exit1_proc_U0_ap_ext_blocking_n),
    .ap_str_blocking_n(Block_ZN2xf2cv3MatILi0ELi2160ELi3840ELi1ELi2EEC2Eii_exit1_proc_U0_ap_str_blocking_n),
    .ap_int_blocking_n(Block_ZN2xf2cv3MatILi0ELi2160ELi3840ELi1ELi2EEC2Eii_exit1_proc_U0_ap_int_blocking_n)
);

resize_accel_Array2xfMat_128_0_2160_3840_1_s Array2xfMat_128_0_2160_3840_1_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(Array2xfMat_128_0_2160_3840_1_U0_ap_start),
    .ap_done(Array2xfMat_128_0_2160_3840_1_U0_ap_done),
    .ap_continue(Array2xfMat_128_0_2160_3840_1_U0_ap_continue),
    .ap_idle(Array2xfMat_128_0_2160_3840_1_U0_ap_idle),
    .ap_ready(Array2xfMat_128_0_2160_3840_1_U0_ap_ready),
    .m_axi_gmem1_AWVALID(Array2xfMat_128_0_2160_3840_1_U0_m_axi_gmem1_AWVALID),
    .m_axi_gmem1_AWREADY(1'b0),
    .m_axi_gmem1_AWADDR(Array2xfMat_128_0_2160_3840_1_U0_m_axi_gmem1_AWADDR),
    .m_axi_gmem1_AWID(Array2xfMat_128_0_2160_3840_1_U0_m_axi_gmem1_AWID),
    .m_axi_gmem1_AWLEN(Array2xfMat_128_0_2160_3840_1_U0_m_axi_gmem1_AWLEN),
    .m_axi_gmem1_AWSIZE(Array2xfMat_128_0_2160_3840_1_U0_m_axi_gmem1_AWSIZE),
    .m_axi_gmem1_AWBURST(Array2xfMat_128_0_2160_3840_1_U0_m_axi_gmem1_AWBURST),
    .m_axi_gmem1_AWLOCK(Array2xfMat_128_0_2160_3840_1_U0_m_axi_gmem1_AWLOCK),
    .m_axi_gmem1_AWCACHE(Array2xfMat_128_0_2160_3840_1_U0_m_axi_gmem1_AWCACHE),
    .m_axi_gmem1_AWPROT(Array2xfMat_128_0_2160_3840_1_U0_m_axi_gmem1_AWPROT),
    .m_axi_gmem1_AWQOS(Array2xfMat_128_0_2160_3840_1_U0_m_axi_gmem1_AWQOS),
    .m_axi_gmem1_AWREGION(Array2xfMat_128_0_2160_3840_1_U0_m_axi_gmem1_AWREGION),
    .m_axi_gmem1_AWUSER(Array2xfMat_128_0_2160_3840_1_U0_m_axi_gmem1_AWUSER),
    .m_axi_gmem1_WVALID(Array2xfMat_128_0_2160_3840_1_U0_m_axi_gmem1_WVALID),
    .m_axi_gmem1_WREADY(1'b0),
    .m_axi_gmem1_WDATA(Array2xfMat_128_0_2160_3840_1_U0_m_axi_gmem1_WDATA),
    .m_axi_gmem1_WSTRB(Array2xfMat_128_0_2160_3840_1_U0_m_axi_gmem1_WSTRB),
    .m_axi_gmem1_WLAST(Array2xfMat_128_0_2160_3840_1_U0_m_axi_gmem1_WLAST),
    .m_axi_gmem1_WID(Array2xfMat_128_0_2160_3840_1_U0_m_axi_gmem1_WID),
    .m_axi_gmem1_WUSER(Array2xfMat_128_0_2160_3840_1_U0_m_axi_gmem1_WUSER),
    .m_axi_gmem1_ARVALID(Array2xfMat_128_0_2160_3840_1_U0_m_axi_gmem1_ARVALID),
    .m_axi_gmem1_ARREADY(gmem1_ARREADY),
    .m_axi_gmem1_ARADDR(Array2xfMat_128_0_2160_3840_1_U0_m_axi_gmem1_ARADDR),
    .m_axi_gmem1_ARID(Array2xfMat_128_0_2160_3840_1_U0_m_axi_gmem1_ARID),
    .m_axi_gmem1_ARLEN(Array2xfMat_128_0_2160_3840_1_U0_m_axi_gmem1_ARLEN),
    .m_axi_gmem1_ARSIZE(Array2xfMat_128_0_2160_3840_1_U0_m_axi_gmem1_ARSIZE),
    .m_axi_gmem1_ARBURST(Array2xfMat_128_0_2160_3840_1_U0_m_axi_gmem1_ARBURST),
    .m_axi_gmem1_ARLOCK(Array2xfMat_128_0_2160_3840_1_U0_m_axi_gmem1_ARLOCK),
    .m_axi_gmem1_ARCACHE(Array2xfMat_128_0_2160_3840_1_U0_m_axi_gmem1_ARCACHE),
    .m_axi_gmem1_ARPROT(Array2xfMat_128_0_2160_3840_1_U0_m_axi_gmem1_ARPROT),
    .m_axi_gmem1_ARQOS(Array2xfMat_128_0_2160_3840_1_U0_m_axi_gmem1_ARQOS),
    .m_axi_gmem1_ARREGION(Array2xfMat_128_0_2160_3840_1_U0_m_axi_gmem1_ARREGION),
    .m_axi_gmem1_ARUSER(Array2xfMat_128_0_2160_3840_1_U0_m_axi_gmem1_ARUSER),
    .m_axi_gmem1_RVALID(gmem1_RVALID),
    .m_axi_gmem1_RREADY(Array2xfMat_128_0_2160_3840_1_U0_m_axi_gmem1_RREADY),
    .m_axi_gmem1_RDATA(gmem1_RDATA),
    .m_axi_gmem1_RLAST(gmem1_RLAST),
    .m_axi_gmem1_RID(gmem1_RID),
    .m_axi_gmem1_RUSER(gmem1_RUSER),
    .m_axi_gmem1_RRESP(gmem1_RRESP),
    .m_axi_gmem1_BVALID(1'b0),
    .m_axi_gmem1_BREADY(Array2xfMat_128_0_2160_3840_1_U0_m_axi_gmem1_BREADY),
    .m_axi_gmem1_BRESP(2'd0),
    .m_axi_gmem1_BID(1'd0),
    .m_axi_gmem1_BUSER(1'd0),
    .p_read(img_inp_c_channel_dout),
    .p_read1(in_mat_rows_c9_channel_dout),
    .p_read2(in_mat_cols_c10_channel_dout),
    .in_mat_420_din(Array2xfMat_128_0_2160_3840_1_U0_in_mat_420_din),
    .in_mat_420_full_n(in_mat_data_full_n),
    .in_mat_420_write(Array2xfMat_128_0_2160_3840_1_U0_in_mat_420_write),
    .in_mat_rows_c_din(Array2xfMat_128_0_2160_3840_1_U0_in_mat_rows_c_din),
    .in_mat_rows_c_full_n(in_mat_rows_c_full_n),
    .in_mat_rows_c_write(Array2xfMat_128_0_2160_3840_1_U0_in_mat_rows_c_write),
    .in_mat_cols_c_din(Array2xfMat_128_0_2160_3840_1_U0_in_mat_cols_c_din),
    .in_mat_cols_c_full_n(in_mat_cols_c_full_n),
    .in_mat_cols_c_write(Array2xfMat_128_0_2160_3840_1_U0_in_mat_cols_c_write),
    .ap_ext_blocking_n(Array2xfMat_128_0_2160_3840_1_U0_ap_ext_blocking_n),
    .ap_str_blocking_n(Array2xfMat_128_0_2160_3840_1_U0_ap_str_blocking_n),
    .ap_int_blocking_n(Array2xfMat_128_0_2160_3840_1_U0_ap_int_blocking_n)
);

resize_accel_resize_1_0_2160_3840_1080_1920_1_2_s resize_1_0_2160_3840_1080_1920_1_2_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(resize_1_0_2160_3840_1080_1920_1_2_U0_ap_start),
    .ap_done(resize_1_0_2160_3840_1080_1920_1_2_U0_ap_done),
    .ap_continue(resize_1_0_2160_3840_1080_1920_1_2_U0_ap_continue),
    .ap_idle(resize_1_0_2160_3840_1080_1920_1_2_U0_ap_idle),
    .ap_ready(resize_1_0_2160_3840_1080_1920_1_2_U0_ap_ready),
    .p_src_rows_dout(in_mat_rows_c_dout),
    .p_src_rows_empty_n(in_mat_rows_c_empty_n),
    .p_src_rows_read(resize_1_0_2160_3840_1080_1920_1_2_U0_p_src_rows_read),
    .p_src_cols_dout(in_mat_cols_c_dout),
    .p_src_cols_empty_n(in_mat_cols_c_empty_n),
    .p_src_cols_read(resize_1_0_2160_3840_1080_1920_1_2_U0_p_src_cols_read),
    .in_mat_420_dout(in_mat_data_dout),
    .in_mat_420_empty_n(in_mat_data_empty_n),
    .in_mat_420_read(resize_1_0_2160_3840_1080_1920_1_2_U0_in_mat_420_read),
    .p_read(out_mat_rows_c11_channel_dout),
    .p_read1(out_mat_cols_c12_channel_dout),
    .out_mat_421_din(resize_1_0_2160_3840_1080_1920_1_2_U0_out_mat_421_din),
    .out_mat_421_full_n(out_mat_data_full_n),
    .out_mat_421_write(resize_1_0_2160_3840_1080_1920_1_2_U0_out_mat_421_write),
    .out_mat_rows_c_din(resize_1_0_2160_3840_1080_1920_1_2_U0_out_mat_rows_c_din),
    .out_mat_rows_c_full_n(out_mat_rows_c_full_n),
    .out_mat_rows_c_write(resize_1_0_2160_3840_1080_1920_1_2_U0_out_mat_rows_c_write),
    .out_mat_cols_c_din(resize_1_0_2160_3840_1080_1920_1_2_U0_out_mat_cols_c_din),
    .out_mat_cols_c_full_n(out_mat_cols_c_full_n),
    .out_mat_cols_c_write(resize_1_0_2160_3840_1080_1920_1_2_U0_out_mat_cols_c_write),
    .ap_ext_blocking_n(resize_1_0_2160_3840_1080_1920_1_2_U0_ap_ext_blocking_n),
    .ap_str_blocking_n(resize_1_0_2160_3840_1080_1920_1_2_U0_ap_str_blocking_n),
    .ap_int_blocking_n(resize_1_0_2160_3840_1080_1920_1_2_U0_ap_int_blocking_n)
);

resize_accel_xfMat2Array_128_0_1080_1920_1_1_s xfMat2Array_128_0_1080_1920_1_1_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(xfMat2Array_128_0_1080_1920_1_1_U0_ap_start),
    .ap_done(xfMat2Array_128_0_1080_1920_1_1_U0_ap_done),
    .ap_continue(xfMat2Array_128_0_1080_1920_1_1_U0_ap_continue),
    .ap_idle(xfMat2Array_128_0_1080_1920_1_1_U0_ap_idle),
    .ap_ready(xfMat2Array_128_0_1080_1920_1_1_U0_ap_ready),
    .srcMat_rows_dout(out_mat_rows_c_dout),
    .srcMat_rows_empty_n(out_mat_rows_c_empty_n),
    .srcMat_rows_read(xfMat2Array_128_0_1080_1920_1_1_U0_srcMat_rows_read),
    .srcMat_cols_dout(out_mat_cols_c_dout),
    .srcMat_cols_empty_n(out_mat_cols_c_empty_n),
    .srcMat_cols_read(xfMat2Array_128_0_1080_1920_1_1_U0_srcMat_cols_read),
    .out_mat_421_dout(out_mat_data_dout),
    .out_mat_421_empty_n(out_mat_data_empty_n),
    .out_mat_421_read(xfMat2Array_128_0_1080_1920_1_1_U0_out_mat_421_read),
    .m_axi_gmem2_AWVALID(xfMat2Array_128_0_1080_1920_1_1_U0_m_axi_gmem2_AWVALID),
    .m_axi_gmem2_AWREADY(gmem2_AWREADY),
    .m_axi_gmem2_AWADDR(xfMat2Array_128_0_1080_1920_1_1_U0_m_axi_gmem2_AWADDR),
    .m_axi_gmem2_AWID(xfMat2Array_128_0_1080_1920_1_1_U0_m_axi_gmem2_AWID),
    .m_axi_gmem2_AWLEN(xfMat2Array_128_0_1080_1920_1_1_U0_m_axi_gmem2_AWLEN),
    .m_axi_gmem2_AWSIZE(xfMat2Array_128_0_1080_1920_1_1_U0_m_axi_gmem2_AWSIZE),
    .m_axi_gmem2_AWBURST(xfMat2Array_128_0_1080_1920_1_1_U0_m_axi_gmem2_AWBURST),
    .m_axi_gmem2_AWLOCK(xfMat2Array_128_0_1080_1920_1_1_U0_m_axi_gmem2_AWLOCK),
    .m_axi_gmem2_AWCACHE(xfMat2Array_128_0_1080_1920_1_1_U0_m_axi_gmem2_AWCACHE),
    .m_axi_gmem2_AWPROT(xfMat2Array_128_0_1080_1920_1_1_U0_m_axi_gmem2_AWPROT),
    .m_axi_gmem2_AWQOS(xfMat2Array_128_0_1080_1920_1_1_U0_m_axi_gmem2_AWQOS),
    .m_axi_gmem2_AWREGION(xfMat2Array_128_0_1080_1920_1_1_U0_m_axi_gmem2_AWREGION),
    .m_axi_gmem2_AWUSER(xfMat2Array_128_0_1080_1920_1_1_U0_m_axi_gmem2_AWUSER),
    .m_axi_gmem2_WVALID(xfMat2Array_128_0_1080_1920_1_1_U0_m_axi_gmem2_WVALID),
    .m_axi_gmem2_WREADY(gmem2_WREADY),
    .m_axi_gmem2_WDATA(xfMat2Array_128_0_1080_1920_1_1_U0_m_axi_gmem2_WDATA),
    .m_axi_gmem2_WSTRB(xfMat2Array_128_0_1080_1920_1_1_U0_m_axi_gmem2_WSTRB),
    .m_axi_gmem2_WLAST(xfMat2Array_128_0_1080_1920_1_1_U0_m_axi_gmem2_WLAST),
    .m_axi_gmem2_WID(xfMat2Array_128_0_1080_1920_1_1_U0_m_axi_gmem2_WID),
    .m_axi_gmem2_WUSER(xfMat2Array_128_0_1080_1920_1_1_U0_m_axi_gmem2_WUSER),
    .m_axi_gmem2_ARVALID(xfMat2Array_128_0_1080_1920_1_1_U0_m_axi_gmem2_ARVALID),
    .m_axi_gmem2_ARREADY(1'b0),
    .m_axi_gmem2_ARADDR(xfMat2Array_128_0_1080_1920_1_1_U0_m_axi_gmem2_ARADDR),
    .m_axi_gmem2_ARID(xfMat2Array_128_0_1080_1920_1_1_U0_m_axi_gmem2_ARID),
    .m_axi_gmem2_ARLEN(xfMat2Array_128_0_1080_1920_1_1_U0_m_axi_gmem2_ARLEN),
    .m_axi_gmem2_ARSIZE(xfMat2Array_128_0_1080_1920_1_1_U0_m_axi_gmem2_ARSIZE),
    .m_axi_gmem2_ARBURST(xfMat2Array_128_0_1080_1920_1_1_U0_m_axi_gmem2_ARBURST),
    .m_axi_gmem2_ARLOCK(xfMat2Array_128_0_1080_1920_1_1_U0_m_axi_gmem2_ARLOCK),
    .m_axi_gmem2_ARCACHE(xfMat2Array_128_0_1080_1920_1_1_U0_m_axi_gmem2_ARCACHE),
    .m_axi_gmem2_ARPROT(xfMat2Array_128_0_1080_1920_1_1_U0_m_axi_gmem2_ARPROT),
    .m_axi_gmem2_ARQOS(xfMat2Array_128_0_1080_1920_1_1_U0_m_axi_gmem2_ARQOS),
    .m_axi_gmem2_ARREGION(xfMat2Array_128_0_1080_1920_1_1_U0_m_axi_gmem2_ARREGION),
    .m_axi_gmem2_ARUSER(xfMat2Array_128_0_1080_1920_1_1_U0_m_axi_gmem2_ARUSER),
    .m_axi_gmem2_RVALID(1'b0),
    .m_axi_gmem2_RREADY(xfMat2Array_128_0_1080_1920_1_1_U0_m_axi_gmem2_RREADY),
    .m_axi_gmem2_RDATA(128'd0),
    .m_axi_gmem2_RLAST(1'b0),
    .m_axi_gmem2_RID(1'd0),
    .m_axi_gmem2_RUSER(1'd0),
    .m_axi_gmem2_RRESP(2'd0),
    .m_axi_gmem2_BVALID(gmem2_BVALID),
    .m_axi_gmem2_BREADY(xfMat2Array_128_0_1080_1920_1_1_U0_m_axi_gmem2_BREADY),
    .m_axi_gmem2_BRESP(gmem2_BRESP),
    .m_axi_gmem2_BID(gmem2_BID),
    .m_axi_gmem2_BUSER(gmem2_BUSER),
    .p_read(img_out_c_channel_dout),
    .ap_ext_blocking_n(xfMat2Array_128_0_1080_1920_1_1_U0_ap_ext_blocking_n),
    .ap_str_blocking_n(xfMat2Array_128_0_1080_1920_1_1_U0_ap_str_blocking_n),
    .ap_int_blocking_n(xfMat2Array_128_0_1080_1920_1_1_U0_ap_int_blocking_n)
);

resize_accel_fifo_w64_d2_S img_inp_c_channel_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(entry_proc7_U0_ap_return_0),
    .if_full_n(img_inp_c_channel_full_n),
    .if_write(ap_channel_done_img_inp_c_channel),
    .if_dout(img_inp_c_channel_dout),
    .if_empty_n(img_inp_c_channel_empty_n),
    .if_read(Array2xfMat_128_0_2160_3840_1_U0_ap_ready)
);

resize_accel_fifo_w64_d4_S img_out_c_channel_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(entry_proc7_U0_ap_return_1),
    .if_full_n(img_out_c_channel_full_n),
    .if_write(ap_channel_done_img_out_c_channel),
    .if_dout(img_out_c_channel_dout),
    .if_empty_n(img_out_c_channel_empty_n),
    .if_read(xfMat2Array_128_0_1080_1920_1_1_U0_ap_ready)
);

resize_accel_fifo_w32_d2_S in_mat_rows_c9_channel_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Block_ZN2xf2cv3MatILi0ELi2160ELi3840ELi1ELi2EEC2Eii_exit1_proc_U0_ap_return_0),
    .if_full_n(in_mat_rows_c9_channel_full_n),
    .if_write(ap_channel_done_in_mat_rows_c9_channel),
    .if_dout(in_mat_rows_c9_channel_dout),
    .if_empty_n(in_mat_rows_c9_channel_empty_n),
    .if_read(Array2xfMat_128_0_2160_3840_1_U0_ap_ready)
);

resize_accel_fifo_w32_d2_S in_mat_cols_c10_channel_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Block_ZN2xf2cv3MatILi0ELi2160ELi3840ELi1ELi2EEC2Eii_exit1_proc_U0_ap_return_1),
    .if_full_n(in_mat_cols_c10_channel_full_n),
    .if_write(ap_channel_done_in_mat_cols_c10_channel),
    .if_dout(in_mat_cols_c10_channel_dout),
    .if_empty_n(in_mat_cols_c10_channel_empty_n),
    .if_read(Array2xfMat_128_0_2160_3840_1_U0_ap_ready)
);

resize_accel_fifo_w32_d3_S out_mat_rows_c11_channel_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Block_ZN2xf2cv3MatILi0ELi2160ELi3840ELi1ELi2EEC2Eii_exit1_proc_U0_ap_return_2),
    .if_full_n(out_mat_rows_c11_channel_full_n),
    .if_write(ap_channel_done_out_mat_rows_c11_channel),
    .if_dout(out_mat_rows_c11_channel_dout),
    .if_empty_n(out_mat_rows_c11_channel_empty_n),
    .if_read(resize_1_0_2160_3840_1080_1920_1_2_U0_ap_ready)
);

resize_accel_fifo_w32_d3_S out_mat_cols_c12_channel_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Block_ZN2xf2cv3MatILi0ELi2160ELi3840ELi1ELi2EEC2Eii_exit1_proc_U0_ap_return_3),
    .if_full_n(out_mat_cols_c12_channel_full_n),
    .if_write(ap_channel_done_out_mat_cols_c12_channel),
    .if_dout(out_mat_cols_c12_channel_dout),
    .if_empty_n(out_mat_cols_c12_channel_empty_n),
    .if_read(resize_1_0_2160_3840_1080_1920_1_2_U0_ap_ready)
);

resize_accel_fifo_w8_d2_S in_mat_data_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Array2xfMat_128_0_2160_3840_1_U0_in_mat_420_din),
    .if_full_n(in_mat_data_full_n),
    .if_write(Array2xfMat_128_0_2160_3840_1_U0_in_mat_420_write),
    .if_dout(in_mat_data_dout),
    .if_empty_n(in_mat_data_empty_n),
    .if_read(resize_1_0_2160_3840_1080_1920_1_2_U0_in_mat_420_read)
);

resize_accel_fifo_w32_d2_S in_mat_rows_c_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Array2xfMat_128_0_2160_3840_1_U0_in_mat_rows_c_din),
    .if_full_n(in_mat_rows_c_full_n),
    .if_write(Array2xfMat_128_0_2160_3840_1_U0_in_mat_rows_c_write),
    .if_dout(in_mat_rows_c_dout),
    .if_empty_n(in_mat_rows_c_empty_n),
    .if_read(resize_1_0_2160_3840_1080_1920_1_2_U0_p_src_rows_read)
);

resize_accel_fifo_w32_d2_S in_mat_cols_c_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Array2xfMat_128_0_2160_3840_1_U0_in_mat_cols_c_din),
    .if_full_n(in_mat_cols_c_full_n),
    .if_write(Array2xfMat_128_0_2160_3840_1_U0_in_mat_cols_c_write),
    .if_dout(in_mat_cols_c_dout),
    .if_empty_n(in_mat_cols_c_empty_n),
    .if_read(resize_1_0_2160_3840_1080_1920_1_2_U0_p_src_cols_read)
);

resize_accel_fifo_w8_d2_S out_mat_data_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(resize_1_0_2160_3840_1080_1920_1_2_U0_out_mat_421_din),
    .if_full_n(out_mat_data_full_n),
    .if_write(resize_1_0_2160_3840_1080_1920_1_2_U0_out_mat_421_write),
    .if_dout(out_mat_data_dout),
    .if_empty_n(out_mat_data_empty_n),
    .if_read(xfMat2Array_128_0_1080_1920_1_1_U0_out_mat_421_read)
);

resize_accel_fifo_w32_d2_S out_mat_rows_c_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(resize_1_0_2160_3840_1080_1920_1_2_U0_out_mat_rows_c_din),
    .if_full_n(out_mat_rows_c_full_n),
    .if_write(resize_1_0_2160_3840_1080_1920_1_2_U0_out_mat_rows_c_write),
    .if_dout(out_mat_rows_c_dout),
    .if_empty_n(out_mat_rows_c_empty_n),
    .if_read(xfMat2Array_128_0_1080_1920_1_1_U0_srcMat_rows_read)
);

resize_accel_fifo_w32_d2_S out_mat_cols_c_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(resize_1_0_2160_3840_1080_1920_1_2_U0_out_mat_cols_c_din),
    .if_full_n(out_mat_cols_c_full_n),
    .if_write(resize_1_0_2160_3840_1080_1920_1_2_U0_out_mat_cols_c_write),
    .if_dout(out_mat_cols_c_dout),
    .if_empty_n(out_mat_cols_c_empty_n),
    .if_read(xfMat2Array_128_0_1080_1920_1_1_U0_srcMat_cols_read)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_Array2xfMat_128_0_2160_3840_1_U0_ap_ready <= 1'b0;
    end else begin
        if (((ap_sync_ready & ap_start) == 1'b1)) begin
            ap_sync_reg_Array2xfMat_128_0_2160_3840_1_U0_ap_ready <= 1'b0;
        end else begin
            ap_sync_reg_Array2xfMat_128_0_2160_3840_1_U0_ap_ready <= ap_sync_Array2xfMat_128_0_2160_3840_1_U0_ap_ready;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_Block_ZN2xf2cv3MatILi0ELi2160ELi3840ELi1ELi2EEC2Eii_exit1_proc_U0_ap_ready <= 1'b0;
    end else begin
        if (((ap_sync_ready & ap_start) == 1'b1)) begin
            ap_sync_reg_Block_ZN2xf2cv3MatILi0ELi2160ELi3840ELi1ELi2EEC2Eii_exit1_proc_U0_ap_ready <= 1'b0;
        end else begin
            ap_sync_reg_Block_ZN2xf2cv3MatILi0ELi2160ELi3840ELi1ELi2EEC2Eii_exit1_proc_U0_ap_ready <= ap_sync_Block_ZN2xf2cv3MatILi0ELi2160ELi3840ELi1ELi2EEC2Eii_exit1_proc_U0_ap_ready;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_channel_write_img_inp_c_channel <= 1'b0;
    end else begin
        if (((entry_proc7_U0_ap_done & entry_proc7_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_img_inp_c_channel <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_img_inp_c_channel <= ap_sync_channel_write_img_inp_c_channel;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_channel_write_img_out_c_channel <= 1'b0;
    end else begin
        if (((entry_proc7_U0_ap_done & entry_proc7_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_img_out_c_channel <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_img_out_c_channel <= ap_sync_channel_write_img_out_c_channel;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_channel_write_in_mat_cols_c10_channel <= 1'b0;
    end else begin
        if (((Block_ZN2xf2cv3MatILi0ELi2160ELi3840ELi1ELi2EEC2Eii_exit1_proc_U0_ap_done & Block_ZN2xf2cv3MatILi0ELi2160ELi3840ELi1ELi2EEC2Eii_exit1_proc_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_in_mat_cols_c10_channel <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_in_mat_cols_c10_channel <= ap_sync_channel_write_in_mat_cols_c10_channel;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_channel_write_in_mat_rows_c9_channel <= 1'b0;
    end else begin
        if (((Block_ZN2xf2cv3MatILi0ELi2160ELi3840ELi1ELi2EEC2Eii_exit1_proc_U0_ap_done & Block_ZN2xf2cv3MatILi0ELi2160ELi3840ELi1ELi2EEC2Eii_exit1_proc_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_in_mat_rows_c9_channel <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_in_mat_rows_c9_channel <= ap_sync_channel_write_in_mat_rows_c9_channel;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_channel_write_out_mat_cols_c12_channel <= 1'b0;
    end else begin
        if (((Block_ZN2xf2cv3MatILi0ELi2160ELi3840ELi1ELi2EEC2Eii_exit1_proc_U0_ap_done & Block_ZN2xf2cv3MatILi0ELi2160ELi3840ELi1ELi2EEC2Eii_exit1_proc_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_out_mat_cols_c12_channel <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_out_mat_cols_c12_channel <= ap_sync_channel_write_out_mat_cols_c12_channel;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_channel_write_out_mat_rows_c11_channel <= 1'b0;
    end else begin
        if (((Block_ZN2xf2cv3MatILi0ELi2160ELi3840ELi1ELi2EEC2Eii_exit1_proc_U0_ap_done & Block_ZN2xf2cv3MatILi0ELi2160ELi3840ELi1ELi2EEC2Eii_exit1_proc_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_out_mat_rows_c11_channel <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_out_mat_rows_c11_channel <= ap_sync_channel_write_out_mat_rows_c11_channel;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_entry_proc7_U0_ap_ready <= 1'b0;
    end else begin
        if (((ap_sync_ready & ap_start) == 1'b1)) begin
            ap_sync_reg_entry_proc7_U0_ap_ready <= 1'b0;
        end else begin
            ap_sync_reg_entry_proc7_U0_ap_ready <= ap_sync_entry_proc7_U0_ap_ready;
        end
    end
end

always @ (posedge ap_clk) begin
    ap_ext_blocking_n_reg <= ap_ext_blocking_n;
end

always @ (posedge ap_clk) begin
    ap_int_blocking_n_reg <= ap_int_blocking_n;
end

always @ (posedge ap_clk) begin
    ap_rst_n_inv <= ap_rst_reg_1;
end

always @ (posedge ap_clk) begin
    ap_rst_reg_1 <= ap_rst_reg_2;
end

always @ (posedge ap_clk) begin
    ap_rst_reg_2 <= ~ap_rst_n;
end

always @ (posedge ap_clk) begin
    ap_str_blocking_n_reg <= ap_str_blocking_n;
end

always @ (*) begin
    if (((ap_ext_blocking_n_reg == 1'b0) & (ap_ext_blocking_n == 1'b1))) begin
        stall_done_ext = 1'b1;
    end else begin
        stall_done_ext = 1'b0;
    end
end

always @ (*) begin
    if (((ap_int_blocking_n_reg == 1'b0) & (ap_int_blocking_n == 1'b1))) begin
        stall_done_int = 1'b1;
    end else begin
        stall_done_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_str_blocking_n_reg == 1'b0) & (ap_str_blocking_n == 1'b1))) begin
        stall_done_str = 1'b1;
    end else begin
        stall_done_str = 1'b0;
    end
end

always @ (*) begin
    if (((ap_ext_blocking_n_reg == 1'b1) & (ap_ext_blocking_n == 1'b0))) begin
        stall_start_ext = 1'b1;
    end else begin
        stall_start_ext = 1'b0;
    end
end

always @ (*) begin
    if (((ap_int_blocking_n_reg == 1'b1) & (ap_int_blocking_n == 1'b0))) begin
        stall_start_int = 1'b1;
    end else begin
        stall_start_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_str_blocking_n_reg == 1'b1) & (ap_str_blocking_n == 1'b0))) begin
        stall_start_str = 1'b1;
    end else begin
        stall_start_str = 1'b0;
    end
end

assign Array2xfMat_128_0_2160_3840_1_U0_ap_continue = 1'b1;

assign Array2xfMat_128_0_2160_3840_1_U0_ap_start = (in_mat_rows_c9_channel_empty_n & in_mat_cols_c10_channel_empty_n & img_inp_c_channel_empty_n & (ap_sync_reg_Array2xfMat_128_0_2160_3840_1_U0_ap_ready ^ 1'b1) & ap_start);

assign Block_ZN2xf2cv3MatILi0ELi2160ELi3840ELi1ELi2EEC2Eii_exit1_proc_U0_ap_continue = (ap_sync_channel_write_out_mat_rows_c11_channel & ap_sync_channel_write_out_mat_cols_c12_channel & ap_sync_channel_write_in_mat_rows_c9_channel & ap_sync_channel_write_in_mat_cols_c10_channel);

assign Block_ZN2xf2cv3MatILi0ELi2160ELi3840ELi1ELi2EEC2Eii_exit1_proc_U0_ap_start = ((ap_sync_reg_Block_ZN2xf2cv3MatILi0ELi2160ELi3840ELi1ELi2EEC2Eii_exit1_proc_U0_ap_ready ^ 1'b1) & ap_start);

assign ap_channel_done_img_inp_c_channel = ((ap_sync_reg_channel_write_img_inp_c_channel ^ 1'b1) & entry_proc7_U0_ap_done);

assign ap_channel_done_img_out_c_channel = ((ap_sync_reg_channel_write_img_out_c_channel ^ 1'b1) & entry_proc7_U0_ap_done);

assign ap_channel_done_in_mat_cols_c10_channel = ((ap_sync_reg_channel_write_in_mat_cols_c10_channel ^ 1'b1) & Block_ZN2xf2cv3MatILi0ELi2160ELi3840ELi1ELi2EEC2Eii_exit1_proc_U0_ap_done);

assign ap_channel_done_in_mat_rows_c9_channel = ((ap_sync_reg_channel_write_in_mat_rows_c9_channel ^ 1'b1) & Block_ZN2xf2cv3MatILi0ELi2160ELi3840ELi1ELi2EEC2Eii_exit1_proc_U0_ap_done);

assign ap_channel_done_out_mat_cols_c12_channel = ((ap_sync_reg_channel_write_out_mat_cols_c12_channel ^ 1'b1) & Block_ZN2xf2cv3MatILi0ELi2160ELi3840ELi1ELi2EEC2Eii_exit1_proc_U0_ap_done);

assign ap_channel_done_out_mat_rows_c11_channel = ((ap_sync_reg_channel_write_out_mat_rows_c11_channel ^ 1'b1) & Block_ZN2xf2cv3MatILi0ELi2160ELi3840ELi1ELi2EEC2Eii_exit1_proc_U0_ap_done);

assign ap_done = xfMat2Array_128_0_1080_1920_1_1_U0_ap_done;

assign ap_ext_blocking_cur_n = 1'b1;

assign ap_ext_blocking_n = (ap_ext_blocking_sub_n & ap_ext_blocking_cur_n);

assign ap_ext_blocking_sub_n = (xfMat2Array_128_0_1080_1920_1_1_U0_ap_ext_blocking_n & resize_1_0_2160_3840_1080_1920_1_2_U0_ap_ext_blocking_n & entry_proc7_U0_ap_ext_blocking_n & Block_ZN2xf2cv3MatILi0ELi2160ELi3840ELi1ELi2EEC2Eii_exit1_proc_U0_ap_ext_blocking_n & Array2xfMat_128_0_2160_3840_1_U0_ap_ext_blocking_n);

assign ap_idle = (xfMat2Array_128_0_1080_1920_1_1_U0_ap_idle & resize_1_0_2160_3840_1080_1920_1_2_U0_ap_idle & (out_mat_cols_c12_channel_empty_n ^ 1'b1) & (out_mat_rows_c11_channel_empty_n ^ 1'b1) & (in_mat_cols_c10_channel_empty_n ^ 1'b1) & (in_mat_rows_c9_channel_empty_n ^ 1'b1) & (img_out_c_channel_empty_n ^ 1'b1) & (img_inp_c_channel_empty_n ^ 1'b1) & entry_proc7_U0_ap_idle & Block_ZN2xf2cv3MatILi0ELi2160ELi3840ELi1ELi2EEC2Eii_exit1_proc_U0_ap_idle & Array2xfMat_128_0_2160_3840_1_U0_ap_idle);

assign ap_int_blocking_cur_n = 1'b1;

assign ap_int_blocking_n = (ap_int_blocking_sub_n & ap_int_blocking_cur_n);

assign ap_int_blocking_sub_n = (xfMat2Array_128_0_1080_1920_1_1_U0_ap_int_blocking_n & resize_1_0_2160_3840_1080_1920_1_2_U0_ap_int_blocking_n & entry_proc7_U0_ap_int_blocking_n & Block_ZN2xf2cv3MatILi0ELi2160ELi3840ELi1ELi2EEC2Eii_exit1_proc_U0_ap_int_blocking_n & Array2xfMat_128_0_2160_3840_1_U0_ap_int_blocking_n);

assign ap_ready = ap_sync_ready;

assign ap_str_blocking_cur_n = 1'b1;

assign ap_str_blocking_n = (ap_str_blocking_sub_n & ap_str_blocking_cur_n);

assign ap_str_blocking_sub_n = (xfMat2Array_128_0_1080_1920_1_1_U0_ap_str_blocking_n & resize_1_0_2160_3840_1080_1920_1_2_U0_ap_str_blocking_n & entry_proc7_U0_ap_str_blocking_n & Block_ZN2xf2cv3MatILi0ELi2160ELi3840ELi1ELi2EEC2Eii_exit1_proc_U0_ap_str_blocking_n & Array2xfMat_128_0_2160_3840_1_U0_ap_str_blocking_n);

assign ap_sync_Array2xfMat_128_0_2160_3840_1_U0_ap_ready = (ap_sync_reg_Array2xfMat_128_0_2160_3840_1_U0_ap_ready | Array2xfMat_128_0_2160_3840_1_U0_ap_ready);

assign ap_sync_Block_ZN2xf2cv3MatILi0ELi2160ELi3840ELi1ELi2EEC2Eii_exit1_proc_U0_ap_ready = (ap_sync_reg_Block_ZN2xf2cv3MatILi0ELi2160ELi3840ELi1ELi2EEC2Eii_exit1_proc_U0_ap_ready | Block_ZN2xf2cv3MatILi0ELi2160ELi3840ELi1ELi2EEC2Eii_exit1_proc_U0_ap_ready);

assign ap_sync_channel_write_img_inp_c_channel = ((img_inp_c_channel_full_n & ap_channel_done_img_inp_c_channel) | ap_sync_reg_channel_write_img_inp_c_channel);

assign ap_sync_channel_write_img_out_c_channel = ((img_out_c_channel_full_n & ap_channel_done_img_out_c_channel) | ap_sync_reg_channel_write_img_out_c_channel);

assign ap_sync_channel_write_in_mat_cols_c10_channel = ((in_mat_cols_c10_channel_full_n & ap_channel_done_in_mat_cols_c10_channel) | ap_sync_reg_channel_write_in_mat_cols_c10_channel);

assign ap_sync_channel_write_in_mat_rows_c9_channel = ((in_mat_rows_c9_channel_full_n & ap_channel_done_in_mat_rows_c9_channel) | ap_sync_reg_channel_write_in_mat_rows_c9_channel);

assign ap_sync_channel_write_out_mat_cols_c12_channel = ((out_mat_cols_c12_channel_full_n & ap_channel_done_out_mat_cols_c12_channel) | ap_sync_reg_channel_write_out_mat_cols_c12_channel);

assign ap_sync_channel_write_out_mat_rows_c11_channel = ((out_mat_rows_c11_channel_full_n & ap_channel_done_out_mat_rows_c11_channel) | ap_sync_reg_channel_write_out_mat_rows_c11_channel);

assign ap_sync_entry_proc7_U0_ap_ready = (entry_proc7_U0_ap_ready | ap_sync_reg_entry_proc7_U0_ap_ready);

assign ap_sync_ready = (ap_sync_entry_proc7_U0_ap_ready & ap_sync_Block_ZN2xf2cv3MatILi0ELi2160ELi3840ELi1ELi2EEC2Eii_exit1_proc_U0_ap_ready & ap_sync_Array2xfMat_128_0_2160_3840_1_U0_ap_ready);

assign entry_proc7_U0_ap_continue = (ap_sync_channel_write_img_out_c_channel & ap_sync_channel_write_img_inp_c_channel);

assign entry_proc7_U0_ap_start = ((ap_sync_reg_entry_proc7_U0_ap_ready ^ 1'b1) & ap_start);

assign event_done = ap_done;

assign resize_1_0_2160_3840_1080_1920_1_2_U0_ap_continue = 1'b1;

assign resize_1_0_2160_3840_1080_1920_1_2_U0_ap_start = (out_mat_rows_c11_channel_empty_n & out_mat_cols_c12_channel_empty_n);

assign xfMat2Array_128_0_1080_1920_1_1_U0_ap_continue = ap_continue;

assign xfMat2Array_128_0_1080_1920_1_1_U0_ap_start = img_out_c_channel_empty_n;

endmodule //resize_accel
