-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.1 (64-bit)
-- Version: 2021.1
-- Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity resize_accel_MatStream2AxiStream_2_Pipeline_MMIterOutRow_MMIterOutCol is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    out_mat_421_dout : IN STD_LOGIC_VECTOR (7 downto 0);
    out_mat_421_empty_n : IN STD_LOGIC;
    out_mat_421_read : OUT STD_LOGIC;
    ldata1_din : OUT STD_LOGIC_VECTOR (127 downto 0);
    ldata1_full_n : IN STD_LOGIC;
    ldata1_write : OUT STD_LOGIC;
    bound : IN STD_LOGIC_VECTOR (31 downto 0);
    cols_bound_per_npc_cast : IN STD_LOGIC_VECTOR (15 downto 0);
    op2_assign : IN STD_LOGIC_VECTOR (31 downto 0);
    last_blk_width_load : IN STD_LOGIC_VECTOR (3 downto 0);
    cols_bound_per_npc : IN STD_LOGIC_VECTOR (31 downto 0);
    filled_V_out : OUT STD_LOGIC_VECTOR (7 downto 0);
    filled_V_out_ap_vld : OUT STD_LOGIC;
    localbuffer_V_3_out : OUT STD_LOGIC_VECTOR (127 downto 0);
    localbuffer_V_3_out_ap_vld : OUT STD_LOGIC;
    ap_ext_blocking_n : OUT STD_LOGIC;
    ap_str_blocking_n : OUT STD_LOGIC;
    ap_int_blocking_n : OUT STD_LOGIC );
end;


architecture behav of resize_accel_MatStream2AxiStream_2_Pipeline_MMIterOutRow_MMIterOutCol is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv128_lc_1 : STD_LOGIC_VECTOR (127 downto 0) := "00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv16_1 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000001";
    constant ap_const_lv4_8 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_lv8_80 : STD_LOGIC_VECTOR (7 downto 0) := "10000000";
    constant ap_const_lv9_80 : STD_LOGIC_VECTOR (8 downto 0) := "010000000";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal icmp_ln1242_reg_461 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1057_reg_470 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_predicate_op42_read_state3 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter2 : BOOLEAN;
    signal icmp_ln1242_reg_461_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1057_1_reg_485 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_predicate_op62_write_state4 : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter3 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln1242_fu_198_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter1_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal out_mat_421_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal ldata1_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal bLast_fu_229_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal bLast_reg_465 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1057_fu_234_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal filled_V_load_2_reg_479 : STD_LOGIC_VECTOR (7 downto 0);
    signal icmp_ln1057_1_fu_275_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_mux_conv_i9_i_i673_pn_phi_fu_158_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal or_ln_fu_281_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter2_conv_i9_i_i673_pn_reg_155 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln1254_fu_261_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter0_val_V_1_reg_164 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter1_val_V_1_reg_164 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter2_val_V_1_reg_164 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter3_val_V_1_reg_164 : STD_LOGIC_VECTOR (7 downto 0);
    signal localbuffer_V_fu_82 : STD_LOGIC_VECTOR (127 downto 0);
    signal localbuffer_V_3_fu_378_p3 : STD_LOGIC_VECTOR (127 downto 0);
    signal ret_fu_320_p2 : STD_LOGIC_VECTOR (127 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal filled_V_fu_86 : STD_LOGIC_VECTOR (7 downto 0);
    signal filled_V_2_fu_293_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal j_V_fu_90 : STD_LOGIC_VECTOR (15 downto 0);
    signal j_V_1_fu_239_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal indvar_flatten_fu_94 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln1242_fu_203_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal icmp_ln1247_fu_212_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln1236_fu_217_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln1057_fu_225_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal xf_bits_per_clock_fu_255_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal sub_ln1265_fu_269_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln1255_fu_307_p1 : STD_LOGIC_VECTOR (127 downto 0);
    signal zext_ln960_fu_311_p1 : STD_LOGIC_VECTOR (127 downto 0);
    signal r_3_fu_314_p2 : STD_LOGIC_VECTOR (127 downto 0);
    signal zext_ln1526_fu_327_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal ret_11_fu_330_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal trunc_ln968_fu_348_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal sub_ln585_fu_352_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal zext_ln960_1_fu_358_p1 : STD_LOGIC_VECTOR (127 downto 0);
    signal trunc_ln494_fu_344_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln978_fu_368_p1 : STD_LOGIC_VECTOR (127 downto 0);
    signal p_Result_s_fu_336_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal r_fu_362_p2 : STD_LOGIC_VECTOR (127 downto 0);
    signal r_2_fu_372_p2 : STD_LOGIC_VECTOR (127 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_int_blocking_cur_n : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_condition_168 : BOOLEAN;
    signal ap_condition_383 : BOOLEAN;
    signal ap_condition_386 : BOOLEAN;
    signal ap_ce_reg : STD_LOGIC;

    component resize_accel_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_sequential_init_U : component resize_accel_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter1_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter2_reg = ap_const_logic_1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter1_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter1_stage0)) then 
                    ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_phi_reg_pp0_iter2_val_V_1_reg_164_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_168)) then
                if (((icmp_ln1242_fu_198_p2 = ap_const_lv1_0) and (icmp_ln1057_fu_234_p2 = ap_const_lv1_0))) then 
                    ap_phi_reg_pp0_iter2_val_V_1_reg_164 <= ap_const_lv8_0;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    ap_phi_reg_pp0_iter2_val_V_1_reg_164 <= ap_phi_reg_pp0_iter1_val_V_1_reg_164;
                end if;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter3_val_V_1_reg_164_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then
                if (((icmp_ln1057_reg_470 = ap_const_lv1_1) and (icmp_ln1242_reg_461 = ap_const_lv1_0))) then 
                    ap_phi_reg_pp0_iter3_val_V_1_reg_164 <= out_mat_421_dout;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    ap_phi_reg_pp0_iter3_val_V_1_reg_164 <= ap_phi_reg_pp0_iter2_val_V_1_reg_164;
                end if;
            end if; 
        end if;
    end process;

    filled_V_fu_86_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
                    filled_V_fu_86 <= ap_const_lv8_0;
                elsif ((ap_enable_reg_pp0_iter2 = ap_const_logic_1)) then 
                    filled_V_fu_86 <= filled_V_2_fu_293_p2;
                end if;
            end if; 
        end if;
    end process;

    indvar_flatten_fu_94_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten_fu_94 <= ap_const_lv32_0;
                elsif (((icmp_ln1242_fu_198_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                    indvar_flatten_fu_94 <= add_ln1242_fu_203_p2;
                end if;
            end if; 
        end if;
    end process;

    j_V_fu_90_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    j_V_fu_90 <= ap_const_lv16_0;
                elsif (((icmp_ln1242_fu_198_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                    j_V_fu_90 <= j_V_1_fu_239_p2;
                end if;
            end if; 
        end if;
    end process;

    localbuffer_V_fu_82_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
                    localbuffer_V_fu_82 <= ap_const_lv128_lc_1;
                elsif ((ap_const_boolean_1 = ap_condition_386)) then 
                    localbuffer_V_fu_82 <= ret_fu_320_p2;
                elsif ((ap_const_boolean_1 = ap_condition_383)) then 
                    localbuffer_V_fu_82 <= localbuffer_V_3_fu_378_p3;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready;
                icmp_ln1242_reg_461 <= icmp_ln1242_fu_198_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ap_phi_reg_pp0_iter1_val_V_1_reg_164 <= ap_phi_reg_pp0_iter0_val_V_1_reg_164;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln1242_fu_198_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                bLast_reg_465 <= bLast_fu_229_p2;
                icmp_ln1057_reg_470 <= icmp_ln1057_fu_234_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                filled_V_load_2_reg_479 <= filled_V_fu_86;
                icmp_ln1057_1_reg_485 <= icmp_ln1057_1_fu_275_p2;
                icmp_ln1242_reg_461_pp0_iter2_reg <= icmp_ln1242_reg_461;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln1242_fu_203_p2 <= std_logic_vector(unsigned(indvar_flatten_fu_94) + unsigned(ap_const_lv32_1));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_assign_proc : process(ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, out_mat_421_empty_n, ap_predicate_op42_read_state3, ldata1_full_n, ap_predicate_op62_write_state4)
    begin
                ap_block_pp0_stage0_01001 <= (((ap_predicate_op62_write_state4 = ap_const_boolean_1) and (ldata1_full_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1)) or ((ap_predicate_op42_read_state3 = ap_const_boolean_1) and (out_mat_421_empty_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1)));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, out_mat_421_empty_n, ap_predicate_op42_read_state3, ldata1_full_n, ap_predicate_op62_write_state4)
    begin
                ap_block_pp0_stage0_11001 <= (((ap_predicate_op62_write_state4 = ap_const_boolean_1) and (ldata1_full_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1)) or ((ap_predicate_op42_read_state3 = ap_const_boolean_1) and (out_mat_421_empty_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1)));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, out_mat_421_empty_n, ap_predicate_op42_read_state3, ldata1_full_n, ap_predicate_op62_write_state4)
    begin
                ap_block_pp0_stage0_subdone <= (((ap_predicate_op62_write_state4 = ap_const_boolean_1) and (ldata1_full_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1)) or ((ap_predicate_op42_read_state3 = ap_const_boolean_1) and (out_mat_421_empty_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1)));
    end process;

        ap_block_state1_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state3_pp0_stage0_iter2_assign_proc : process(out_mat_421_empty_n, ap_predicate_op42_read_state3)
    begin
                ap_block_state3_pp0_stage0_iter2 <= ((ap_predicate_op42_read_state3 = ap_const_boolean_1) and (out_mat_421_empty_n = ap_const_logic_0));
    end process;


    ap_block_state4_pp0_stage0_iter3_assign_proc : process(ldata1_full_n, ap_predicate_op62_write_state4)
    begin
                ap_block_state4_pp0_stage0_iter3 <= ((ap_predicate_op62_write_state4 = ap_const_boolean_1) and (ldata1_full_n = ap_const_logic_0));
    end process;


    ap_condition_168_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
                ap_condition_168 <= ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0));
    end process;


    ap_condition_383_assign_proc : process(ap_enable_reg_pp0_iter3, icmp_ln1242_reg_461_pp0_iter2_reg, icmp_ln1057_1_reg_485)
    begin
                ap_condition_383 <= ((icmp_ln1057_1_reg_485 = ap_const_lv1_0) and (icmp_ln1242_reg_461_pp0_iter2_reg = ap_const_lv1_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1));
    end process;


    ap_condition_386_assign_proc : process(ap_enable_reg_pp0_iter3, icmp_ln1242_reg_461_pp0_iter2_reg, icmp_ln1057_1_reg_485)
    begin
                ap_condition_386 <= ((icmp_ln1057_1_reg_485 = ap_const_lv1_1) and (icmp_ln1242_reg_461_pp0_iter2_reg = ap_const_lv1_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1));
    end process;


    ap_condition_exit_pp0_iter1_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_subdone, icmp_ln1242_fu_198_p2)
    begin
        if (((icmp_ln1242_fu_198_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter1_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter1_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter2_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter2_reg = ap_const_logic_1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;
    ap_ext_blocking_n <= (ap_const_logic_1 and ap_const_logic_1);

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3)
    begin
        if (((ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_int_blocking_cur_n <= (out_mat_421_blk_n and ldata1_blk_n);
    ap_int_blocking_n <= (ap_int_blocking_cur_n and ap_const_logic_1);
    ap_loop_exit_ready <= ap_condition_exit_pp0_iter1_stage0;

    ap_phi_mux_conv_i9_i_i673_pn_phi_fu_158_p4_assign_proc : process(icmp_ln1242_reg_461, icmp_ln1057_1_fu_275_p2, or_ln_fu_281_p3, ap_phi_reg_pp0_iter2_conv_i9_i_i673_pn_reg_155, zext_ln1254_fu_261_p1)
    begin
        if ((icmp_ln1242_reg_461 = ap_const_lv1_0)) then
            if ((icmp_ln1057_1_fu_275_p2 = ap_const_lv1_1)) then 
                ap_phi_mux_conv_i9_i_i673_pn_phi_fu_158_p4 <= zext_ln1254_fu_261_p1;
            elsif ((icmp_ln1057_1_fu_275_p2 = ap_const_lv1_0)) then 
                ap_phi_mux_conv_i9_i_i673_pn_phi_fu_158_p4 <= or_ln_fu_281_p3;
            else 
                ap_phi_mux_conv_i9_i_i673_pn_phi_fu_158_p4 <= ap_phi_reg_pp0_iter2_conv_i9_i_i673_pn_reg_155;
            end if;
        else 
            ap_phi_mux_conv_i9_i_i673_pn_phi_fu_158_p4 <= ap_phi_reg_pp0_iter2_conv_i9_i_i673_pn_reg_155;
        end if; 
    end process;

    ap_phi_reg_pp0_iter0_val_V_1_reg_164 <= "XXXXXXXX";
    ap_phi_reg_pp0_iter2_conv_i9_i_i673_pn_reg_155 <= "XXXXXXXX";

    ap_predicate_op42_read_state3_assign_proc : process(icmp_ln1242_reg_461, icmp_ln1057_reg_470)
    begin
                ap_predicate_op42_read_state3 <= ((icmp_ln1057_reg_470 = ap_const_lv1_1) and (icmp_ln1242_reg_461 = ap_const_lv1_0));
    end process;


    ap_predicate_op62_write_state4_assign_proc : process(icmp_ln1242_reg_461_pp0_iter2_reg, icmp_ln1057_1_reg_485)
    begin
                ap_predicate_op62_write_state4 <= ((icmp_ln1057_1_reg_485 = ap_const_lv1_0) and (icmp_ln1242_reg_461_pp0_iter2_reg = ap_const_lv1_0));
    end process;


    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;

    ap_str_blocking_n <= (ap_const_logic_1 and ap_const_logic_1);
    bLast_fu_229_p2 <= "1" when (zext_ln1057_fu_225_p1 = op2_assign) else "0";
    filled_V_2_fu_293_p2 <= std_logic_vector(unsigned(ap_phi_mux_conv_i9_i_i673_pn_phi_fu_158_p4) + unsigned(filled_V_fu_86));
    filled_V_out <= filled_V_fu_86;

    filled_V_out_ap_vld_assign_proc : process(icmp_ln1242_reg_461, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln1242_reg_461 = ap_const_lv1_1))) then 
            filled_V_out_ap_vld <= ap_const_logic_1;
        else 
            filled_V_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    icmp_ln1057_1_fu_275_p2 <= "1" when (unsigned(filled_V_fu_86) < unsigned(sub_ln1265_fu_269_p2)) else "0";
    icmp_ln1057_fu_234_p2 <= "1" when (signed(zext_ln1057_fu_225_p1) < signed(cols_bound_per_npc)) else "0";
    icmp_ln1242_fu_198_p2 <= "1" when (indvar_flatten_fu_94 = bound) else "0";
    icmp_ln1247_fu_212_p2 <= "1" when (j_V_fu_90 = cols_bound_per_npc_cast) else "0";
    j_V_1_fu_239_p2 <= std_logic_vector(unsigned(select_ln1236_fu_217_p3) + unsigned(ap_const_lv16_1));

    ldata1_blk_n_assign_proc : process(ap_enable_reg_pp0_iter3, ldata1_full_n, ap_predicate_op62_write_state4, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_predicate_op62_write_state4 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            ldata1_blk_n <= ldata1_full_n;
        else 
            ldata1_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    ldata1_din <= (r_3_fu_314_p2 or localbuffer_V_fu_82);

    ldata1_write_assign_proc : process(ap_enable_reg_pp0_iter3, ap_predicate_op62_write_state4, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_predicate_op62_write_state4 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            ldata1_write <= ap_const_logic_1;
        else 
            ldata1_write <= ap_const_logic_0;
        end if; 
    end process;

    localbuffer_V_3_fu_378_p3 <= 
        r_fu_362_p2 when (p_Result_s_fu_336_p3(0) = '1') else 
        r_2_fu_372_p2;
    localbuffer_V_3_out <= localbuffer_V_fu_82;

    localbuffer_V_3_out_ap_vld_assign_proc : process(icmp_ln1242_reg_461, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln1242_reg_461 = ap_const_lv1_1))) then 
            localbuffer_V_3_out_ap_vld <= ap_const_logic_1;
        else 
            localbuffer_V_3_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    or_ln_fu_281_p3 <= (ap_const_lv4_8 & xf_bits_per_clock_fu_255_p3);

    out_mat_421_blk_n_assign_proc : process(ap_enable_reg_pp0_iter2, out_mat_421_empty_n, ap_predicate_op42_read_state3, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_predicate_op42_read_state3 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            out_mat_421_blk_n <= out_mat_421_empty_n;
        else 
            out_mat_421_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    out_mat_421_read_assign_proc : process(ap_enable_reg_pp0_iter2, ap_predicate_op42_read_state3, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_predicate_op42_read_state3 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            out_mat_421_read <= ap_const_logic_1;
        else 
            out_mat_421_read <= ap_const_logic_0;
        end if; 
    end process;

    p_Result_s_fu_336_p3 <= ret_11_fu_330_p2(8 downto 8);
    r_2_fu_372_p2 <= std_logic_vector(shift_right(unsigned(zext_ln1255_fu_307_p1),to_integer(unsigned('0' & zext_ln978_fu_368_p1(31-1 downto 0)))));
    r_3_fu_314_p2 <= std_logic_vector(shift_left(unsigned(zext_ln1255_fu_307_p1),to_integer(unsigned('0' & zext_ln960_fu_311_p1(31-1 downto 0)))));
    r_fu_362_p2 <= std_logic_vector(shift_left(unsigned(zext_ln1255_fu_307_p1),to_integer(unsigned('0' & zext_ln960_1_fu_358_p1(31-1 downto 0)))));
    ret_11_fu_330_p2 <= std_logic_vector(unsigned(ap_const_lv9_80) - unsigned(zext_ln1526_fu_327_p1));
    ret_fu_320_p2 <= (r_3_fu_314_p2 or localbuffer_V_fu_82);
    select_ln1236_fu_217_p3 <= 
        ap_const_lv16_0 when (icmp_ln1247_fu_212_p2(0) = '1') else 
        j_V_fu_90;
    sub_ln1265_fu_269_p2 <= std_logic_vector(signed(ap_const_lv8_80) - signed(zext_ln1254_fu_261_p1));
    sub_ln585_fu_352_p2 <= std_logic_vector(unsigned(ap_const_lv7_0) - unsigned(trunc_ln968_fu_348_p1));
    trunc_ln494_fu_344_p1 <= ret_11_fu_330_p2(8 - 1 downto 0);
    trunc_ln968_fu_348_p1 <= ret_11_fu_330_p2(7 - 1 downto 0);
    xf_bits_per_clock_fu_255_p3 <= 
        last_blk_width_load when (bLast_reg_465(0) = '1') else 
        ap_const_lv4_8;
    zext_ln1057_fu_225_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln1236_fu_217_p3),32));
    zext_ln1254_fu_261_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(xf_bits_per_clock_fu_255_p3),8));
    zext_ln1255_fu_307_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_phi_reg_pp0_iter3_val_V_1_reg_164),128));
    zext_ln1526_fu_327_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(filled_V_load_2_reg_479),9));
    zext_ln960_1_fu_358_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sub_ln585_fu_352_p2),128));
    zext_ln960_fu_311_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(filled_V_load_2_reg_479),128));
    zext_ln978_fu_368_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(trunc_ln494_fu_344_p1),128));
end behav;
