// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.1 (64-bit)
// Version: 2021.1
// Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module resize_accel_resizeNNBilinear_0_2160_3840_1_1080_1920_1_2_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        p_read,
        p_read1,
        in_mat_420_dout,
        in_mat_420_empty_n,
        in_mat_420_read,
        p_read2,
        p_read3,
        out_mat_421_din,
        out_mat_421_full_n,
        out_mat_421_write,
        ap_ext_blocking_n,
        ap_str_blocking_n,
        ap_int_blocking_n
);

parameter    ap_ST_fsm_state1 = 14'd1;
parameter    ap_ST_fsm_state2 = 14'd2;
parameter    ap_ST_fsm_state3 = 14'd4;
parameter    ap_ST_fsm_state4 = 14'd8;
parameter    ap_ST_fsm_state5 = 14'd16;
parameter    ap_ST_fsm_state6 = 14'd32;
parameter    ap_ST_fsm_state7 = 14'd64;
parameter    ap_ST_fsm_state8 = 14'd128;
parameter    ap_ST_fsm_state9 = 14'd256;
parameter    ap_ST_fsm_state10 = 14'd512;
parameter    ap_ST_fsm_state11 = 14'd1024;
parameter    ap_ST_fsm_state12 = 14'd2048;
parameter    ap_ST_fsm_state13 = 14'd4096;
parameter    ap_ST_fsm_state14 = 14'd8192;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] p_read;
input  [31:0] p_read1;
input  [7:0] in_mat_420_dout;
input   in_mat_420_empty_n;
output   in_mat_420_read;
input  [31:0] p_read2;
input  [31:0] p_read3;
output  [7:0] out_mat_421_din;
input   out_mat_421_full_n;
output   out_mat_421_write;
output   ap_ext_blocking_n;
output   ap_str_blocking_n;
output   ap_int_blocking_n;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg in_mat_420_read;
reg out_mat_421_write;

(* fsm_encoding = "none" *) reg   [13:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [15:0] trunc_ln300_fu_256_p1;
reg   [15:0] trunc_ln300_reg_890;
wire   [15:0] trunc_ln301_fu_260_p1;
reg   [15:0] trunc_ln301_reg_895;
wire   [32:0] tmp_fu_294_p3;
reg   [32:0] tmp_reg_900;
wire    ap_CS_fsm_state2;
wire   [63:0] xnew_fu_302_p3;
reg   [63:0] xnew_reg_905;
wire   [47:0] trunc_ln712_fu_310_p1;
reg   [47:0] trunc_ln712_reg_910;
wire    ap_CS_fsm_state3;
wire   [63:0] ynew_fu_314_p3;
reg   [63:0] ynew_reg_915;
wire   [47:0] trunc_ln712_1_fu_322_p1;
reg   [47:0] trunc_ln712_1_reg_920;
wire    ap_CS_fsm_state4;
wire   [31:0] loop_row_count_fu_330_p3;
reg   [31:0] loop_row_count_reg_925;
wire   [31:0] loop_col_count_fu_340_p3;
reg   [31:0] loop_col_count_reg_930;
wire   [31:0] sub272_fu_346_p2;
reg   [31:0] sub272_reg_935;
wire   [31:0] tmp_V_fu_351_p2;
reg   [31:0] tmp_V_reg_940;
wire   [42:0] conv_i_i10_i309_i2_cast_fu_376_p1;
reg   [42:0] conv_i_i10_i309_i2_cast_reg_945;
wire   [53:0] shl_i_i_i_i233_i_fu_385_p3;
reg   [53:0] shl_i_i_i_i233_i_reg_950;
wire   [53:0] shl_i_i_i_i_i_fu_393_p3;
reg   [53:0] shl_i_i_i_i_i_reg_955;
wire   [41:0] indexx_pre_V_1_fu_405_p3;
reg   [41:0] indexx_pre_V_1_reg_960;
wire   [41:0] shl_i_i_i216_i_fu_417_p3;
reg   [41:0] shl_i_i_i216_i_reg_965;
wire   [21:0] sub_ln902_fu_425_p2;
reg   [21:0] sub_ln902_reg_970;
wire   [0:0] slt_fu_454_p2;
reg   [0:0] slt_reg_981;
wire    ap_CS_fsm_state6;
wire   [41:0] grp_scaleCompute_17_42_20_48_16_1_s_fu_195_ap_return;
reg  signed [41:0] indexy_pre_comp_V_reg_986;
wire    ap_CS_fsm_state10;
wire   [21:0] empty_59_fu_495_p1;
reg   [21:0] empty_59_reg_991;
reg   [16:0] ret_V_3_cast_reg_996;
reg   [0:0] tmp_7_reg_1002;
wire   [23:0] empty_60_fu_517_p1;
reg   [23:0] empty_60_reg_1007;
wire   [0:0] icmp_ln902_fu_521_p2;
reg   [0:0] icmp_ln902_reg_1012;
wire   [31:0] op2_assign_fu_529_p2;
reg   [31:0] op2_assign_reg_1020;
wire    ap_CS_fsm_state11;
wire   [16:0] ret_V_17_fu_574_p3;
reg   [16:0] ret_V_17_reg_1027;
wire   [0:0] icmp_ln1061_1_fu_586_p2;
reg   [0:0] icmp_ln1061_1_reg_1032;
wire   [0:0] cmp89_fu_608_p2;
reg   [0:0] cmp89_reg_1049;
wire    ap_CS_fsm_state12;
wire   [0:0] rev125_fu_613_p2;
reg   [0:0] rev125_reg_1057;
wire   [0:0] cmp277_fu_619_p2;
reg   [0:0] cmp277_reg_1063;
wire   [31:0] op2_assign_2_fu_624_p2;
reg   [31:0] op2_assign_2_reg_1069;
wire   [16:0] add_i_i_i_i_i199_i_fu_630_p2;
reg   [16:0] add_i_i_i_i_i199_i_reg_1075;
wire   [0:0] xor_ln1061_fu_636_p2;
reg   [0:0] xor_ln1061_reg_1080;
reg   [11:0] line_buffer_V_0_0_address0;
reg    line_buffer_V_0_0_ce0;
reg    line_buffer_V_0_0_we0;
reg   [7:0] line_buffer_V_0_0_d0;
wire   [7:0] line_buffer_V_0_0_q0;
reg    line_buffer_V_0_0_ce1;
wire   [7:0] line_buffer_V_0_0_q1;
reg   [11:0] line_buffer_V_1_0_address0;
reg    line_buffer_V_1_0_ce0;
reg    line_buffer_V_1_0_we0;
reg   [7:0] line_buffer_V_1_0_d0;
wire   [7:0] line_buffer_V_1_0_q0;
reg    line_buffer_V_1_0_ce1;
wire   [7:0] line_buffer_V_1_0_q1;
wire    grp_xfUDivResize_fu_178_ap_start;
wire    grp_xfUDivResize_fu_178_ap_done;
wire    grp_xfUDivResize_fu_178_ap_idle;
wire    grp_xfUDivResize_fu_178_ap_ready;
reg   [63:0] grp_xfUDivResize_fu_178_in_n;
reg   [15:0] grp_xfUDivResize_fu_178_in_d;
wire   [63:0] grp_xfUDivResize_fu_178_ap_return;
wire    grp_xfUDivResize_fu_178_ap_ext_blocking_n;
wire    grp_xfUDivResize_fu_178_ap_str_blocking_n;
wire    grp_xfUDivResize_fu_178_ap_int_blocking_n;
reg   [31:0] grp_scaleCompute_17_42_20_48_16_1_s_fu_195_currindex;
reg   [47:0] grp_scaleCompute_17_42_20_48_16_1_s_fu_195_inscale;
reg    grp_scaleCompute_17_42_20_48_16_1_s_fu_195_ap_ce;
wire    grp_scaleCompute_17_42_20_48_16_1_s_fu_195_ap_ext_blocking_n;
wire    grp_scaleCompute_17_42_20_48_16_1_s_fu_195_ap_str_blocking_n;
wire    grp_scaleCompute_17_42_20_48_16_1_s_fu_195_ap_int_blocking_n;
wire    ap_CS_fsm_state7;
wire    ap_CS_fsm_state8;
wire    ap_CS_fsm_state9;
wire    grp_resizeNNBilinear_0_2160_3840_1_1080_1920_1_2_Pipeline_VITIS_LOOP_332_1_VITIS_LOOP_337_2_fu_210_ap_start;
wire    grp_resizeNNBilinear_0_2160_3840_1_1080_1920_1_2_Pipeline_VITIS_LOOP_332_1_VITIS_LOOP_337_2_fu_210_ap_done;
wire    grp_resizeNNBilinear_0_2160_3840_1_1080_1920_1_2_Pipeline_VITIS_LOOP_332_1_VITIS_LOOP_337_2_fu_210_ap_idle;
wire    grp_resizeNNBilinear_0_2160_3840_1_1080_1920_1_2_Pipeline_VITIS_LOOP_332_1_VITIS_LOOP_337_2_fu_210_ap_ready;
wire    grp_resizeNNBilinear_0_2160_3840_1_1080_1920_1_2_Pipeline_VITIS_LOOP_332_1_VITIS_LOOP_337_2_fu_210_in_mat_420_read;
wire   [11:0] grp_resizeNNBilinear_0_2160_3840_1_1080_1920_1_2_Pipeline_VITIS_LOOP_332_1_VITIS_LOOP_337_2_fu_210_line_buffer_V_0_0_address0;
wire    grp_resizeNNBilinear_0_2160_3840_1_1080_1920_1_2_Pipeline_VITIS_LOOP_332_1_VITIS_LOOP_337_2_fu_210_line_buffer_V_0_0_ce0;
wire    grp_resizeNNBilinear_0_2160_3840_1_1080_1920_1_2_Pipeline_VITIS_LOOP_332_1_VITIS_LOOP_337_2_fu_210_line_buffer_V_0_0_we0;
wire   [7:0] grp_resizeNNBilinear_0_2160_3840_1_1080_1920_1_2_Pipeline_VITIS_LOOP_332_1_VITIS_LOOP_337_2_fu_210_line_buffer_V_0_0_d0;
wire   [11:0] grp_resizeNNBilinear_0_2160_3840_1_1080_1920_1_2_Pipeline_VITIS_LOOP_332_1_VITIS_LOOP_337_2_fu_210_line_buffer_V_1_0_address0;
wire    grp_resizeNNBilinear_0_2160_3840_1_1080_1920_1_2_Pipeline_VITIS_LOOP_332_1_VITIS_LOOP_337_2_fu_210_line_buffer_V_1_0_ce0;
wire    grp_resizeNNBilinear_0_2160_3840_1_1080_1920_1_2_Pipeline_VITIS_LOOP_332_1_VITIS_LOOP_337_2_fu_210_line_buffer_V_1_0_we0;
wire   [7:0] grp_resizeNNBilinear_0_2160_3840_1_1080_1920_1_2_Pipeline_VITIS_LOOP_332_1_VITIS_LOOP_337_2_fu_210_line_buffer_V_1_0_d0;
wire    grp_resizeNNBilinear_0_2160_3840_1_1080_1920_1_2_Pipeline_VITIS_LOOP_332_1_VITIS_LOOP_337_2_fu_210_ap_ext_blocking_n;
wire    grp_resizeNNBilinear_0_2160_3840_1_1080_1920_1_2_Pipeline_VITIS_LOOP_332_1_VITIS_LOOP_337_2_fu_210_ap_str_blocking_n;
wire    grp_resizeNNBilinear_0_2160_3840_1_1080_1920_1_2_Pipeline_VITIS_LOOP_332_1_VITIS_LOOP_337_2_fu_210_ap_int_blocking_n;
wire    grp_resizeNNBilinear_0_2160_3840_1_1080_1920_1_2_Pipeline_VITIS_LOOP_389_5_fu_220_ap_start;
wire    grp_resizeNNBilinear_0_2160_3840_1_1080_1920_1_2_Pipeline_VITIS_LOOP_389_5_fu_220_ap_done;
wire    grp_resizeNNBilinear_0_2160_3840_1_1080_1920_1_2_Pipeline_VITIS_LOOP_389_5_fu_220_ap_idle;
wire    grp_resizeNNBilinear_0_2160_3840_1_1080_1920_1_2_Pipeline_VITIS_LOOP_389_5_fu_220_ap_ready;
wire    grp_resizeNNBilinear_0_2160_3840_1_1080_1920_1_2_Pipeline_VITIS_LOOP_389_5_fu_220_in_mat_420_read;
wire   [7:0] grp_resizeNNBilinear_0_2160_3840_1_1080_1920_1_2_Pipeline_VITIS_LOOP_389_5_fu_220_out_mat_421_din;
wire    grp_resizeNNBilinear_0_2160_3840_1_1080_1920_1_2_Pipeline_VITIS_LOOP_389_5_fu_220_out_mat_421_write;
wire   [11:0] grp_resizeNNBilinear_0_2160_3840_1_1080_1920_1_2_Pipeline_VITIS_LOOP_389_5_fu_220_line_buffer_V_0_0_address0;
wire    grp_resizeNNBilinear_0_2160_3840_1_1080_1920_1_2_Pipeline_VITIS_LOOP_389_5_fu_220_line_buffer_V_0_0_ce0;
wire    grp_resizeNNBilinear_0_2160_3840_1_1080_1920_1_2_Pipeline_VITIS_LOOP_389_5_fu_220_line_buffer_V_0_0_we0;
wire   [7:0] grp_resizeNNBilinear_0_2160_3840_1_1080_1920_1_2_Pipeline_VITIS_LOOP_389_5_fu_220_line_buffer_V_0_0_d0;
wire   [11:0] grp_resizeNNBilinear_0_2160_3840_1_1080_1920_1_2_Pipeline_VITIS_LOOP_389_5_fu_220_line_buffer_V_0_0_address1;
wire    grp_resizeNNBilinear_0_2160_3840_1_1080_1920_1_2_Pipeline_VITIS_LOOP_389_5_fu_220_line_buffer_V_0_0_ce1;
wire   [11:0] grp_resizeNNBilinear_0_2160_3840_1_1080_1920_1_2_Pipeline_VITIS_LOOP_389_5_fu_220_line_buffer_V_1_0_address0;
wire    grp_resizeNNBilinear_0_2160_3840_1_1080_1920_1_2_Pipeline_VITIS_LOOP_389_5_fu_220_line_buffer_V_1_0_ce0;
wire    grp_resizeNNBilinear_0_2160_3840_1_1080_1920_1_2_Pipeline_VITIS_LOOP_389_5_fu_220_line_buffer_V_1_0_we0;
wire   [7:0] grp_resizeNNBilinear_0_2160_3840_1_1080_1920_1_2_Pipeline_VITIS_LOOP_389_5_fu_220_line_buffer_V_1_0_d0;
wire   [11:0] grp_resizeNNBilinear_0_2160_3840_1_1080_1920_1_2_Pipeline_VITIS_LOOP_389_5_fu_220_line_buffer_V_1_0_address1;
wire    grp_resizeNNBilinear_0_2160_3840_1_1080_1920_1_2_Pipeline_VITIS_LOOP_389_5_fu_220_line_buffer_V_1_0_ce1;
wire    grp_resizeNNBilinear_0_2160_3840_1_1080_1920_1_2_Pipeline_VITIS_LOOP_389_5_fu_220_p_Result_s;
wire   [7:0] grp_resizeNNBilinear_0_2160_3840_1_1080_1920_1_2_Pipeline_VITIS_LOOP_389_5_fu_220_read_pixel_1_out;
wire    grp_resizeNNBilinear_0_2160_3840_1_1080_1920_1_2_Pipeline_VITIS_LOOP_389_5_fu_220_read_pixel_1_out_ap_vld;
wire   [16:0] grp_resizeNNBilinear_0_2160_3840_1_1080_1920_1_2_Pipeline_VITIS_LOOP_389_5_fu_220_indexy_V_1_out;
wire    grp_resizeNNBilinear_0_2160_3840_1_1080_1920_1_2_Pipeline_VITIS_LOOP_389_5_fu_220_indexy_V_1_out_ap_vld;
wire   [16:0] grp_resizeNNBilinear_0_2160_3840_1_1080_1920_1_2_Pipeline_VITIS_LOOP_389_5_fu_220_nextYScale_V_1_out;
wire    grp_resizeNNBilinear_0_2160_3840_1_1080_1920_1_2_Pipeline_VITIS_LOOP_389_5_fu_220_nextYScale_V_1_out_ap_vld;
wire    grp_resizeNNBilinear_0_2160_3840_1_1080_1920_1_2_Pipeline_VITIS_LOOP_389_5_fu_220_ap_ext_blocking_n;
wire    grp_resizeNNBilinear_0_2160_3840_1_1080_1920_1_2_Pipeline_VITIS_LOOP_389_5_fu_220_ap_str_blocking_n;
wire    grp_resizeNNBilinear_0_2160_3840_1_1080_1920_1_2_Pipeline_VITIS_LOOP_389_5_fu_220_ap_int_blocking_n;
wire   [31:0] grp_resizeNNBilinear_0_2160_3840_1_1080_1920_1_2_Pipeline_VITIS_LOOP_389_5_fu_220_grp_scaleCompute_17_42_20_48_16_1_s_fu_195_p_din1;
wire   [47:0] grp_resizeNNBilinear_0_2160_3840_1_1080_1920_1_2_Pipeline_VITIS_LOOP_389_5_fu_220_grp_scaleCompute_17_42_20_48_16_1_s_fu_195_p_din2;
wire    grp_resizeNNBilinear_0_2160_3840_1_1080_1920_1_2_Pipeline_VITIS_LOOP_389_5_fu_220_grp_scaleCompute_17_42_20_48_16_1_s_fu_195_p_ce;
reg    grp_xfUDivResize_fu_178_ap_start_reg;
reg    ap_block_state3_on_subcall_done;
reg    grp_resizeNNBilinear_0_2160_3840_1_1080_1920_1_2_Pipeline_VITIS_LOOP_332_1_VITIS_LOOP_337_2_fu_210_ap_start_reg;
reg    grp_resizeNNBilinear_0_2160_3840_1_1080_1920_1_2_Pipeline_VITIS_LOOP_389_5_fu_220_ap_start_reg;
wire    ap_CS_fsm_state13;
reg   [7:0] read_pixel_fu_106;
wire    ap_CS_fsm_state14;
reg   [31:0] read_rows_count_fu_110;
wire   [31:0] read_rows_count_2_fu_738_p3;
reg   [31:0] output_rows_count_fu_114;
wire   [31:0] output_rows_count_1_fu_688_p3;
reg   [31:0] first_row_index_1_fu_118;
wire   [31:0] first_row_index_4_fu_751_p3;
reg   [31:0] i_fu_122;
wire   [31:0] i_2_fu_439_p2;
wire    ap_CS_fsm_state5;
wire   [0:0] icmp_ln382_fu_434_p2;
reg   [16:0] nextYScale_V_fu_126;
reg   [16:0] indexy_V_fu_130;
wire   [0:0] icmp_ln354_fu_326_p2;
wire   [0:0] icmp_ln356_fu_336_p2;
wire   [37:0] conv_i_i10_i309_i2_fu_366_p4;
wire   [31:0] i_op_assign_fu_380_p2;
wire   [19:0] empty_57_fu_401_p1;
wire   [19:0] empty_58_fu_413_p1;
wire   [21:0] conv_i_i_i322_i_cast_fu_356_p4;
wire  signed [41:0] trunc_ln387_fu_459_p0;
wire  signed [41:0] conv_i_i255_i_fu_463_p0;
wire  signed [41:0] tmp_6_fu_467_p1;
wire  signed [53:0] conv_i_i255_i_fu_463_p1;
wire   [0:0] cmp_i_i235_i_fu_475_p2;
wire  signed [41:0] spec_select151_fu_480_p2;
wire   [0:0] tmp_6_fu_467_p3;
wire   [41:0] spec_select151_fu_480_p3;
wire   [41:0] indexy_pre_V_fu_487_p3;
wire   [21:0] trunc_ln387_fu_459_p1;
wire  signed [42:0] conv_i_i_i300_i_fu_535_p1;
wire   [42:0] p_Val2_s_fu_538_p2;
wire   [16:0] ret_V_cast_fu_543_p4;
wire   [16:0] add_i_i_i_i_i286_i_fu_561_p2;
wire   [0:0] tmp_5_fu_553_p3;
wire   [16:0] select_ln901_fu_567_p3;
wire   [31:0] zext_ln1061_1_fu_582_p1;
wire   [31:0] zext_ln1049_fu_651_p1;
wire   [0:0] icmp_ln1049_fu_655_p2;
wire   [0:0] and_ln509_fu_660_p2;
wire   [0:0] icmp_ln1049_1_fu_665_p2;
wire   [0:0] or_ln509_fu_670_p2;
wire   [31:0] add_ln511_fu_676_p2;
wire   [31:0] select_ln509_fu_681_p3;
wire   [31:0] zext_ln1061_fu_694_p1;
wire   [31:0] first_row_index_fu_703_p2;
wire   [0:0] icmp_ln522_fu_708_p2;
wire   [31:0] read_rows_count_1_fu_722_p2;
wire   [0:0] icmp_ln1061_fu_698_p2;
wire   [0:0] and_ln1061_fu_733_p2;
wire   [31:0] sel_tmp1_fu_727_p3;
wire   [31:0] first_row_index_2_fu_714_p3;
wire   [31:0] first_row_index_3_fu_745_p3;
reg   [13:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
wire    ap_ST_fsm_state11_blk;
wire    ap_ST_fsm_state12_blk;
reg    ap_ST_fsm_state13_blk;
wire    ap_ST_fsm_state14_blk;
reg    ap_ext_blocking_sub_n;
reg    ap_wait_0;
reg    ap_sub_ext_blocking_0;
reg    ap_wait_1;
reg    ap_sub_ext_blocking_1;
reg    ap_wait_2;
reg    ap_sub_ext_blocking_2;
reg    ap_wait_3;
reg    ap_sub_ext_blocking_3;
reg    ap_str_blocking_sub_n;
reg    ap_sub_str_blocking_0;
reg    ap_sub_str_blocking_1;
reg    ap_sub_str_blocking_2;
reg    ap_sub_str_blocking_3;
reg    ap_int_blocking_sub_n;
reg    ap_sub_int_blocking_0;
reg    ap_sub_int_blocking_1;
reg    ap_sub_int_blocking_2;
reg    ap_sub_int_blocking_3;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 14'd1;
#0 grp_xfUDivResize_fu_178_ap_start_reg = 1'b0;
#0 grp_resizeNNBilinear_0_2160_3840_1_1080_1920_1_2_Pipeline_VITIS_LOOP_332_1_VITIS_LOOP_337_2_fu_210_ap_start_reg = 1'b0;
#0 grp_resizeNNBilinear_0_2160_3840_1_1080_1920_1_2_Pipeline_VITIS_LOOP_389_5_fu_220_ap_start_reg = 1'b0;
end

resize_accel_resizeNNBilinear_0_2160_3840_1_1080_1920_1_2_Pipeline_VITIS_LOOP_389_5_line_bbkb #(
    .DataWidth( 8 ),
    .AddressRange( 3840 ),
    .AddressWidth( 12 ))
line_buffer_V_0_0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(line_buffer_V_0_0_address0),
    .ce0(line_buffer_V_0_0_ce0),
    .we0(line_buffer_V_0_0_we0),
    .d0(line_buffer_V_0_0_d0),
    .q0(line_buffer_V_0_0_q0),
    .address1(grp_resizeNNBilinear_0_2160_3840_1_1080_1920_1_2_Pipeline_VITIS_LOOP_389_5_fu_220_line_buffer_V_0_0_address1),
    .ce1(line_buffer_V_0_0_ce1),
    .q1(line_buffer_V_0_0_q1)
);

resize_accel_resizeNNBilinear_0_2160_3840_1_1080_1920_1_2_Pipeline_VITIS_LOOP_389_5_line_bbkb #(
    .DataWidth( 8 ),
    .AddressRange( 3840 ),
    .AddressWidth( 12 ))
line_buffer_V_1_0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(line_buffer_V_1_0_address0),
    .ce0(line_buffer_V_1_0_ce0),
    .we0(line_buffer_V_1_0_we0),
    .d0(line_buffer_V_1_0_d0),
    .q0(line_buffer_V_1_0_q0),
    .address1(grp_resizeNNBilinear_0_2160_3840_1_1080_1920_1_2_Pipeline_VITIS_LOOP_389_5_fu_220_line_buffer_V_1_0_address1),
    .ce1(line_buffer_V_1_0_ce1),
    .q1(line_buffer_V_1_0_q1)
);

resize_accel_xfUDivResize grp_xfUDivResize_fu_178(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_xfUDivResize_fu_178_ap_start),
    .ap_done(grp_xfUDivResize_fu_178_ap_done),
    .ap_idle(grp_xfUDivResize_fu_178_ap_idle),
    .ap_ready(grp_xfUDivResize_fu_178_ap_ready),
    .in_n(grp_xfUDivResize_fu_178_in_n),
    .in_d(grp_xfUDivResize_fu_178_in_d),
    .ap_return(grp_xfUDivResize_fu_178_ap_return),
    .ap_ext_blocking_n(grp_xfUDivResize_fu_178_ap_ext_blocking_n),
    .ap_str_blocking_n(grp_xfUDivResize_fu_178_ap_str_blocking_n),
    .ap_int_blocking_n(grp_xfUDivResize_fu_178_ap_int_blocking_n)
);

resize_accel_scaleCompute_17_42_20_48_16_1_s grp_scaleCompute_17_42_20_48_16_1_s_fu_195(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .currindex(grp_scaleCompute_17_42_20_48_16_1_s_fu_195_currindex),
    .inscale(grp_scaleCompute_17_42_20_48_16_1_s_fu_195_inscale),
    .ap_return(grp_scaleCompute_17_42_20_48_16_1_s_fu_195_ap_return),
    .ap_ce(grp_scaleCompute_17_42_20_48_16_1_s_fu_195_ap_ce),
    .ap_ext_blocking_n(grp_scaleCompute_17_42_20_48_16_1_s_fu_195_ap_ext_blocking_n),
    .ap_str_blocking_n(grp_scaleCompute_17_42_20_48_16_1_s_fu_195_ap_str_blocking_n),
    .ap_int_blocking_n(grp_scaleCompute_17_42_20_48_16_1_s_fu_195_ap_int_blocking_n)
);

resize_accel_resizeNNBilinear_0_2160_3840_1_1080_1920_1_2_Pipeline_VITIS_LOOP_332_1_VITIS_LOOP_337_2 grp_resizeNNBilinear_0_2160_3840_1_1080_1920_1_2_Pipeline_VITIS_LOOP_332_1_VITIS_LOOP_337_2_fu_210(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_resizeNNBilinear_0_2160_3840_1_1080_1920_1_2_Pipeline_VITIS_LOOP_332_1_VITIS_LOOP_337_2_fu_210_ap_start),
    .ap_done(grp_resizeNNBilinear_0_2160_3840_1_1080_1920_1_2_Pipeline_VITIS_LOOP_332_1_VITIS_LOOP_337_2_fu_210_ap_done),
    .ap_idle(grp_resizeNNBilinear_0_2160_3840_1_1080_1920_1_2_Pipeline_VITIS_LOOP_332_1_VITIS_LOOP_337_2_fu_210_ap_idle),
    .ap_ready(grp_resizeNNBilinear_0_2160_3840_1_1080_1920_1_2_Pipeline_VITIS_LOOP_332_1_VITIS_LOOP_337_2_fu_210_ap_ready),
    .in_mat_420_dout(in_mat_420_dout),
    .in_mat_420_empty_n(in_mat_420_empty_n),
    .in_mat_420_read(grp_resizeNNBilinear_0_2160_3840_1_1080_1920_1_2_Pipeline_VITIS_LOOP_332_1_VITIS_LOOP_337_2_fu_210_in_mat_420_read),
    .bound(tmp_reg_900),
    .p_read1(p_read1),
    .line_buffer_V_0_0_address0(grp_resizeNNBilinear_0_2160_3840_1_1080_1920_1_2_Pipeline_VITIS_LOOP_332_1_VITIS_LOOP_337_2_fu_210_line_buffer_V_0_0_address0),
    .line_buffer_V_0_0_ce0(grp_resizeNNBilinear_0_2160_3840_1_1080_1920_1_2_Pipeline_VITIS_LOOP_332_1_VITIS_LOOP_337_2_fu_210_line_buffer_V_0_0_ce0),
    .line_buffer_V_0_0_we0(grp_resizeNNBilinear_0_2160_3840_1_1080_1920_1_2_Pipeline_VITIS_LOOP_332_1_VITIS_LOOP_337_2_fu_210_line_buffer_V_0_0_we0),
    .line_buffer_V_0_0_d0(grp_resizeNNBilinear_0_2160_3840_1_1080_1920_1_2_Pipeline_VITIS_LOOP_332_1_VITIS_LOOP_337_2_fu_210_line_buffer_V_0_0_d0),
    .line_buffer_V_1_0_address0(grp_resizeNNBilinear_0_2160_3840_1_1080_1920_1_2_Pipeline_VITIS_LOOP_332_1_VITIS_LOOP_337_2_fu_210_line_buffer_V_1_0_address0),
    .line_buffer_V_1_0_ce0(grp_resizeNNBilinear_0_2160_3840_1_1080_1920_1_2_Pipeline_VITIS_LOOP_332_1_VITIS_LOOP_337_2_fu_210_line_buffer_V_1_0_ce0),
    .line_buffer_V_1_0_we0(grp_resizeNNBilinear_0_2160_3840_1_1080_1920_1_2_Pipeline_VITIS_LOOP_332_1_VITIS_LOOP_337_2_fu_210_line_buffer_V_1_0_we0),
    .line_buffer_V_1_0_d0(grp_resizeNNBilinear_0_2160_3840_1_1080_1920_1_2_Pipeline_VITIS_LOOP_332_1_VITIS_LOOP_337_2_fu_210_line_buffer_V_1_0_d0),
    .ap_ext_blocking_n(grp_resizeNNBilinear_0_2160_3840_1_1080_1920_1_2_Pipeline_VITIS_LOOP_332_1_VITIS_LOOP_337_2_fu_210_ap_ext_blocking_n),
    .ap_str_blocking_n(grp_resizeNNBilinear_0_2160_3840_1_1080_1920_1_2_Pipeline_VITIS_LOOP_332_1_VITIS_LOOP_337_2_fu_210_ap_str_blocking_n),
    .ap_int_blocking_n(grp_resizeNNBilinear_0_2160_3840_1_1080_1920_1_2_Pipeline_VITIS_LOOP_332_1_VITIS_LOOP_337_2_fu_210_ap_int_blocking_n)
);

resize_accel_resizeNNBilinear_0_2160_3840_1_1080_1920_1_2_Pipeline_VITIS_LOOP_389_5 grp_resizeNNBilinear_0_2160_3840_1_1080_1920_1_2_Pipeline_VITIS_LOOP_389_5_fu_220(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_resizeNNBilinear_0_2160_3840_1_1080_1920_1_2_Pipeline_VITIS_LOOP_389_5_fu_220_ap_start),
    .ap_done(grp_resizeNNBilinear_0_2160_3840_1_1080_1920_1_2_Pipeline_VITIS_LOOP_389_5_fu_220_ap_done),
    .ap_idle(grp_resizeNNBilinear_0_2160_3840_1_1080_1920_1_2_Pipeline_VITIS_LOOP_389_5_fu_220_ap_idle),
    .ap_ready(grp_resizeNNBilinear_0_2160_3840_1_1080_1920_1_2_Pipeline_VITIS_LOOP_389_5_fu_220_ap_ready),
    .in_mat_420_dout(in_mat_420_dout),
    .in_mat_420_empty_n(in_mat_420_empty_n),
    .in_mat_420_read(grp_resizeNNBilinear_0_2160_3840_1_1080_1920_1_2_Pipeline_VITIS_LOOP_389_5_fu_220_in_mat_420_read),
    .out_mat_421_din(grp_resizeNNBilinear_0_2160_3840_1_1080_1920_1_2_Pipeline_VITIS_LOOP_389_5_fu_220_out_mat_421_din),
    .out_mat_421_full_n(out_mat_421_full_n),
    .out_mat_421_write(grp_resizeNNBilinear_0_2160_3840_1_1080_1920_1_2_Pipeline_VITIS_LOOP_389_5_fu_220_out_mat_421_write),
    .read_pixel(read_pixel_fu_106),
    .indexy_V(indexy_V_fu_130),
    .nextYScale_V(nextYScale_V_fu_126),
    .ret_V_17(ret_V_17_reg_1027),
    .loop_col_count(loop_col_count_reg_930),
    .cmp273(rev125_reg_1057),
    .line_buffer_V_0_0_address0(grp_resizeNNBilinear_0_2160_3840_1_1080_1920_1_2_Pipeline_VITIS_LOOP_389_5_fu_220_line_buffer_V_0_0_address0),
    .line_buffer_V_0_0_ce0(grp_resizeNNBilinear_0_2160_3840_1_1080_1920_1_2_Pipeline_VITIS_LOOP_389_5_fu_220_line_buffer_V_0_0_ce0),
    .line_buffer_V_0_0_we0(grp_resizeNNBilinear_0_2160_3840_1_1080_1920_1_2_Pipeline_VITIS_LOOP_389_5_fu_220_line_buffer_V_0_0_we0),
    .line_buffer_V_0_0_d0(grp_resizeNNBilinear_0_2160_3840_1_1080_1920_1_2_Pipeline_VITIS_LOOP_389_5_fu_220_line_buffer_V_0_0_d0),
    .line_buffer_V_0_0_q0(line_buffer_V_0_0_q0),
    .line_buffer_V_0_0_address1(grp_resizeNNBilinear_0_2160_3840_1_1080_1920_1_2_Pipeline_VITIS_LOOP_389_5_fu_220_line_buffer_V_0_0_address1),
    .line_buffer_V_0_0_ce1(grp_resizeNNBilinear_0_2160_3840_1_1080_1920_1_2_Pipeline_VITIS_LOOP_389_5_fu_220_line_buffer_V_0_0_ce1),
    .line_buffer_V_0_0_q1(line_buffer_V_0_0_q1),
    .line_buffer_V_1_0_address0(grp_resizeNNBilinear_0_2160_3840_1_1080_1920_1_2_Pipeline_VITIS_LOOP_389_5_fu_220_line_buffer_V_1_0_address0),
    .line_buffer_V_1_0_ce0(grp_resizeNNBilinear_0_2160_3840_1_1080_1920_1_2_Pipeline_VITIS_LOOP_389_5_fu_220_line_buffer_V_1_0_ce0),
    .line_buffer_V_1_0_we0(grp_resizeNNBilinear_0_2160_3840_1_1080_1920_1_2_Pipeline_VITIS_LOOP_389_5_fu_220_line_buffer_V_1_0_we0),
    .line_buffer_V_1_0_d0(grp_resizeNNBilinear_0_2160_3840_1_1080_1920_1_2_Pipeline_VITIS_LOOP_389_5_fu_220_line_buffer_V_1_0_d0),
    .line_buffer_V_1_0_q0(line_buffer_V_1_0_q0),
    .line_buffer_V_1_0_address1(grp_resizeNNBilinear_0_2160_3840_1_1080_1920_1_2_Pipeline_VITIS_LOOP_389_5_fu_220_line_buffer_V_1_0_address1),
    .line_buffer_V_1_0_ce1(grp_resizeNNBilinear_0_2160_3840_1_1080_1920_1_2_Pipeline_VITIS_LOOP_389_5_fu_220_line_buffer_V_1_0_ce1),
    .line_buffer_V_1_0_q1(line_buffer_V_1_0_q1),
    .tmp_V(tmp_V_reg_940),
    .first_row_index_5(first_row_index_1_fu_118),
    .trunc_ln3(trunc_ln712_reg_910),
    .indexy_pre_V(empty_59_reg_991),
    .add_i_i_i_i_i199_i(add_i_i_i_i_i199_i_reg_1075),
    .ret_V_3_cast(ret_V_3_cast_reg_996),
    .p_Result_s(grp_resizeNNBilinear_0_2160_3840_1_1080_1920_1_2_Pipeline_VITIS_LOOP_389_5_fu_220_p_Result_s),
    .indexy_pre_V_cast(empty_60_reg_1007),
    .shl_i_i_i_i_i(shl_i_i_i_i_i_reg_955),
    .indexx_pre_V_1(indexx_pre_V_1_reg_960),
    .cmp89(cmp89_reg_1049),
    .p_read1(p_read1),
    .icmp_ln1061_1(xor_ln1061_reg_1080),
    .op2_assign_2(op2_assign_2_reg_1069),
    .op2_assign(op2_assign_reg_1020),
    .cmp277(cmp277_reg_1063),
    .p_read3(p_read3),
    .read_pixel_1_out(grp_resizeNNBilinear_0_2160_3840_1_1080_1920_1_2_Pipeline_VITIS_LOOP_389_5_fu_220_read_pixel_1_out),
    .read_pixel_1_out_ap_vld(grp_resizeNNBilinear_0_2160_3840_1_1080_1920_1_2_Pipeline_VITIS_LOOP_389_5_fu_220_read_pixel_1_out_ap_vld),
    .indexy_V_1_out(grp_resizeNNBilinear_0_2160_3840_1_1080_1920_1_2_Pipeline_VITIS_LOOP_389_5_fu_220_indexy_V_1_out),
    .indexy_V_1_out_ap_vld(grp_resizeNNBilinear_0_2160_3840_1_1080_1920_1_2_Pipeline_VITIS_LOOP_389_5_fu_220_indexy_V_1_out_ap_vld),
    .nextYScale_V_1_out(grp_resizeNNBilinear_0_2160_3840_1_1080_1920_1_2_Pipeline_VITIS_LOOP_389_5_fu_220_nextYScale_V_1_out),
    .nextYScale_V_1_out_ap_vld(grp_resizeNNBilinear_0_2160_3840_1_1080_1920_1_2_Pipeline_VITIS_LOOP_389_5_fu_220_nextYScale_V_1_out_ap_vld),
    .ap_ext_blocking_n(grp_resizeNNBilinear_0_2160_3840_1_1080_1920_1_2_Pipeline_VITIS_LOOP_389_5_fu_220_ap_ext_blocking_n),
    .ap_str_blocking_n(grp_resizeNNBilinear_0_2160_3840_1_1080_1920_1_2_Pipeline_VITIS_LOOP_389_5_fu_220_ap_str_blocking_n),
    .ap_int_blocking_n(grp_resizeNNBilinear_0_2160_3840_1_1080_1920_1_2_Pipeline_VITIS_LOOP_389_5_fu_220_ap_int_blocking_n),
    .grp_scaleCompute_17_42_20_48_16_1_s_fu_195_p_din1(grp_resizeNNBilinear_0_2160_3840_1_1080_1920_1_2_Pipeline_VITIS_LOOP_389_5_fu_220_grp_scaleCompute_17_42_20_48_16_1_s_fu_195_p_din1),
    .grp_scaleCompute_17_42_20_48_16_1_s_fu_195_p_din2(grp_resizeNNBilinear_0_2160_3840_1_1080_1920_1_2_Pipeline_VITIS_LOOP_389_5_fu_220_grp_scaleCompute_17_42_20_48_16_1_s_fu_195_p_din2),
    .grp_scaleCompute_17_42_20_48_16_1_s_fu_195_p_dout0(grp_scaleCompute_17_42_20_48_16_1_s_fu_195_ap_return),
    .grp_scaleCompute_17_42_20_48_16_1_s_fu_195_p_ce(grp_resizeNNBilinear_0_2160_3840_1_1080_1920_1_2_Pipeline_VITIS_LOOP_389_5_fu_220_grp_scaleCompute_17_42_20_48_16_1_s_fu_195_p_ce)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_resizeNNBilinear_0_2160_3840_1_1080_1920_1_2_Pipeline_VITIS_LOOP_332_1_VITIS_LOOP_337_2_fu_210_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state2)) begin
            grp_resizeNNBilinear_0_2160_3840_1_1080_1920_1_2_Pipeline_VITIS_LOOP_332_1_VITIS_LOOP_337_2_fu_210_ap_start_reg <= 1'b1;
        end else if ((grp_resizeNNBilinear_0_2160_3840_1_1080_1920_1_2_Pipeline_VITIS_LOOP_332_1_VITIS_LOOP_337_2_fu_210_ap_ready == 1'b1)) begin
            grp_resizeNNBilinear_0_2160_3840_1_1080_1920_1_2_Pipeline_VITIS_LOOP_332_1_VITIS_LOOP_337_2_fu_210_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_resizeNNBilinear_0_2160_3840_1_1080_1920_1_2_Pipeline_VITIS_LOOP_389_5_fu_220_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state12)) begin
            grp_resizeNNBilinear_0_2160_3840_1_1080_1920_1_2_Pipeline_VITIS_LOOP_389_5_fu_220_ap_start_reg <= 1'b1;
        end else if ((grp_resizeNNBilinear_0_2160_3840_1_1080_1920_1_2_Pipeline_VITIS_LOOP_389_5_fu_220_ap_ready == 1'b1)) begin
            grp_resizeNNBilinear_0_2160_3840_1_1080_1920_1_2_Pipeline_VITIS_LOOP_389_5_fu_220_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_xfUDivResize_fu_178_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state2) | ((1'b0 == ap_block_state3_on_subcall_done) & (1'b1 == ap_CS_fsm_state3)))) begin
            grp_xfUDivResize_fu_178_ap_start_reg <= 1'b1;
        end else if ((grp_xfUDivResize_fu_178_ap_ready == 1'b1)) begin
            grp_xfUDivResize_fu_178_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        first_row_index_1_fu_118 <= 32'd0;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        first_row_index_1_fu_118 <= first_row_index_4_fu_751_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        i_fu_122 <= 32'd0;
    end else if (((icmp_ln382_fu_434_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state5))) begin
        i_fu_122 <= i_2_fu_439_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        indexy_V_fu_130 <= 17'd0;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        indexy_V_fu_130 <= grp_resizeNNBilinear_0_2160_3840_1_1080_1920_1_2_Pipeline_VITIS_LOOP_389_5_fu_220_indexy_V_1_out;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        nextYScale_V_fu_126 <= 17'd0;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        nextYScale_V_fu_126 <= grp_resizeNNBilinear_0_2160_3840_1_1080_1920_1_2_Pipeline_VITIS_LOOP_389_5_fu_220_nextYScale_V_1_out;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        output_rows_count_fu_114 <= 32'd0;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        output_rows_count_fu_114 <= output_rows_count_1_fu_688_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        read_rows_count_fu_110 <= 32'd2;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        read_rows_count_fu_110 <= read_rows_count_2_fu_738_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        add_i_i_i_i_i199_i_reg_1075 <= add_i_i_i_i_i199_i_fu_630_p2;
        cmp277_reg_1063 <= cmp277_fu_619_p2;
        cmp89_reg_1049 <= cmp89_fu_608_p2;
        op2_assign_2_reg_1069 <= op2_assign_2_fu_624_p2;
        rev125_reg_1057 <= rev125_fu_613_p2;
        xor_ln1061_reg_1080 <= xor_ln1061_fu_636_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        conv_i_i10_i309_i2_cast_reg_945[37 : 0] <= conv_i_i10_i309_i2_cast_fu_376_p1[37 : 0];
        indexx_pre_V_1_reg_960[41 : 22] <= indexx_pre_V_1_fu_405_p3[41 : 22];
        loop_col_count_reg_930 <= loop_col_count_fu_340_p3;
        loop_row_count_reg_925 <= loop_row_count_fu_330_p3;
        shl_i_i_i216_i_reg_965[41 : 22] <= shl_i_i_i216_i_fu_417_p3[41 : 22];
        shl_i_i_i_i233_i_reg_950[53 : 22] <= shl_i_i_i_i233_i_fu_385_p3[53 : 22];
        shl_i_i_i_i_i_reg_955[53 : 22] <= shl_i_i_i_i_i_fu_393_p3[53 : 22];
        sub272_reg_935 <= sub272_fu_346_p2;
        sub_ln902_reg_970 <= sub_ln902_fu_425_p2;
        tmp_V_reg_940 <= tmp_V_fu_351_p2;
        trunc_ln712_1_reg_920 <= trunc_ln712_1_fu_322_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        empty_59_reg_991 <= empty_59_fu_495_p1;
        empty_60_reg_1007 <= empty_60_fu_517_p1;
        icmp_ln902_reg_1012 <= icmp_ln902_fu_521_p2;
        indexy_pre_comp_V_reg_986 <= grp_scaleCompute_17_42_20_48_16_1_s_fu_195_ap_return;
        ret_V_3_cast_reg_996 <= {{indexy_pre_V_fu_487_p3[38:22]}};
        tmp_7_reg_1002 <= indexy_pre_V_fu_487_p3[32'd41];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        icmp_ln1061_1_reg_1032 <= icmp_ln1061_1_fu_586_p2;
        op2_assign_reg_1020 <= op2_assign_fu_529_p2;
        ret_V_17_reg_1027 <= ret_V_17_fu_574_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        read_pixel_fu_106 <= grp_resizeNNBilinear_0_2160_3840_1_1080_1920_1_2_Pipeline_VITIS_LOOP_389_5_fu_220_read_pixel_1_out;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        slt_reg_981 <= slt_fu_454_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        tmp_reg_900[32 : 1] <= tmp_fu_294_p3[32 : 1];
        xnew_reg_905[63 : 32] <= xnew_fu_302_p3[63 : 32];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        trunc_ln300_reg_890 <= trunc_ln300_fu_256_p1;
        trunc_ln301_reg_895 <= trunc_ln301_fu_260_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        trunc_ln712_reg_910 <= trunc_ln712_fu_310_p1;
        ynew_reg_915[63 : 32] <= ynew_fu_314_p3[63 : 32];
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

assign ap_ST_fsm_state11_blk = 1'b0;

assign ap_ST_fsm_state12_blk = 1'b0;

always @ (*) begin
    if ((grp_resizeNNBilinear_0_2160_3840_1_1080_1920_1_2_Pipeline_VITIS_LOOP_389_5_fu_220_ap_done == 1'b0)) begin
        ap_ST_fsm_state13_blk = 1'b1;
    end else begin
        ap_ST_fsm_state13_blk = 1'b0;
    end
end

assign ap_ST_fsm_state14_blk = 1'b0;

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_block_state3_on_subcall_done)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_xfUDivResize_fu_178_ap_done == 1'b0)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if ((((icmp_ln382_fu_434_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state5)) | ((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_wait_3 & ap_sub_ext_blocking_3) == 1'b1) & ((ap_wait_2 & ap_sub_ext_blocking_2) == 1'b1) & ((ap_wait_1 & ap_sub_ext_blocking_1) == 1'b1) & ((ap_wait_0 & ap_sub_ext_blocking_0) == 1'b1))) begin
        ap_ext_blocking_sub_n = 1'b0;
    end else begin
        ap_ext_blocking_sub_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_wait_3 & ap_sub_int_blocking_3) == 1'b1) & ((ap_wait_2 & ap_sub_int_blocking_2) == 1'b1) & ((ap_wait_1 & ap_sub_int_blocking_1) == 1'b1) & ((ap_wait_0 & ap_sub_int_blocking_0) == 1'b1))) begin
        ap_int_blocking_sub_n = 1'b0;
    end else begin
        ap_int_blocking_sub_n = 1'b1;
    end
end

always @ (*) begin
    if (((icmp_ln382_fu_434_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state5))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_wait_3 & ap_sub_str_blocking_3) == 1'b1) & ((ap_wait_2 & ap_sub_str_blocking_2) == 1'b1) & ((ap_wait_1 & ap_sub_str_blocking_1) == 1'b1) & ((ap_wait_0 & ap_sub_str_blocking_0) == 1'b1))) begin
        ap_str_blocking_sub_n = 1'b0;
    end else begin
        ap_str_blocking_sub_n = 1'b1;
    end
end

always @ (*) begin
    if ((grp_xfUDivResize_fu_178_ap_ext_blocking_n == 1'b0)) begin
        ap_sub_ext_blocking_0 = 1'b1;
    end else begin
        ap_sub_ext_blocking_0 = 1'b0;
    end
end

always @ (*) begin
    if ((grp_scaleCompute_17_42_20_48_16_1_s_fu_195_ap_ext_blocking_n == 1'b0)) begin
        ap_sub_ext_blocking_1 = 1'b1;
    end else begin
        ap_sub_ext_blocking_1 = 1'b0;
    end
end

always @ (*) begin
    if ((grp_resizeNNBilinear_0_2160_3840_1_1080_1920_1_2_Pipeline_VITIS_LOOP_332_1_VITIS_LOOP_337_2_fu_210_ap_ext_blocking_n == 1'b0)) begin
        ap_sub_ext_blocking_2 = 1'b1;
    end else begin
        ap_sub_ext_blocking_2 = 1'b0;
    end
end

always @ (*) begin
    if ((grp_resizeNNBilinear_0_2160_3840_1_1080_1920_1_2_Pipeline_VITIS_LOOP_389_5_fu_220_ap_ext_blocking_n == 1'b0)) begin
        ap_sub_ext_blocking_3 = 1'b1;
    end else begin
        ap_sub_ext_blocking_3 = 1'b0;
    end
end

always @ (*) begin
    if ((grp_xfUDivResize_fu_178_ap_int_blocking_n == 1'b0)) begin
        ap_sub_int_blocking_0 = 1'b1;
    end else begin
        ap_sub_int_blocking_0 = 1'b0;
    end
end

always @ (*) begin
    if ((grp_scaleCompute_17_42_20_48_16_1_s_fu_195_ap_int_blocking_n == 1'b0)) begin
        ap_sub_int_blocking_1 = 1'b1;
    end else begin
        ap_sub_int_blocking_1 = 1'b0;
    end
end

always @ (*) begin
    if ((grp_resizeNNBilinear_0_2160_3840_1_1080_1920_1_2_Pipeline_VITIS_LOOP_332_1_VITIS_LOOP_337_2_fu_210_ap_int_blocking_n == 1'b0)) begin
        ap_sub_int_blocking_2 = 1'b1;
    end else begin
        ap_sub_int_blocking_2 = 1'b0;
    end
end

always @ (*) begin
    if ((grp_resizeNNBilinear_0_2160_3840_1_1080_1920_1_2_Pipeline_VITIS_LOOP_389_5_fu_220_ap_int_blocking_n == 1'b0)) begin
        ap_sub_int_blocking_3 = 1'b1;
    end else begin
        ap_sub_int_blocking_3 = 1'b0;
    end
end

always @ (*) begin
    if ((grp_xfUDivResize_fu_178_ap_str_blocking_n == 1'b0)) begin
        ap_sub_str_blocking_0 = 1'b1;
    end else begin
        ap_sub_str_blocking_0 = 1'b0;
    end
end

always @ (*) begin
    if ((grp_scaleCompute_17_42_20_48_16_1_s_fu_195_ap_str_blocking_n == 1'b0)) begin
        ap_sub_str_blocking_1 = 1'b1;
    end else begin
        ap_sub_str_blocking_1 = 1'b0;
    end
end

always @ (*) begin
    if ((grp_resizeNNBilinear_0_2160_3840_1_1080_1920_1_2_Pipeline_VITIS_LOOP_332_1_VITIS_LOOP_337_2_fu_210_ap_str_blocking_n == 1'b0)) begin
        ap_sub_str_blocking_2 = 1'b1;
    end else begin
        ap_sub_str_blocking_2 = 1'b0;
    end
end

always @ (*) begin
    if ((grp_resizeNNBilinear_0_2160_3840_1_1080_1920_1_2_Pipeline_VITIS_LOOP_389_5_fu_220_ap_str_blocking_n == 1'b0)) begin
        ap_sub_str_blocking_3 = 1'b1;
    end else begin
        ap_sub_str_blocking_3 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_ST_fsm_state3 == ap_CS_fsm)) begin
        ap_wait_0 = 1'b1;
    end else begin
        ap_wait_0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_ST_fsm_state10 == ap_CS_fsm)) begin
        ap_wait_1 = 1'b1;
    end else begin
        ap_wait_1 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_ST_fsm_state3 == ap_CS_fsm)) begin
        ap_wait_2 = 1'b1;
    end else begin
        ap_wait_2 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_ST_fsm_state13 == ap_CS_fsm)) begin
        ap_wait_3 = 1'b1;
    end else begin
        ap_wait_3 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state12))) begin
        grp_scaleCompute_17_42_20_48_16_1_s_fu_195_ap_ce = grp_resizeNNBilinear_0_2160_3840_1_1080_1920_1_2_Pipeline_VITIS_LOOP_389_5_fu_220_grp_scaleCompute_17_42_20_48_16_1_s_fu_195_p_ce;
    end else if (((1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state6))) begin
        grp_scaleCompute_17_42_20_48_16_1_s_fu_195_ap_ce = 1'b1;
    end else begin
        grp_scaleCompute_17_42_20_48_16_1_s_fu_195_ap_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state12))) begin
        grp_scaleCompute_17_42_20_48_16_1_s_fu_195_currindex = grp_resizeNNBilinear_0_2160_3840_1_1080_1920_1_2_Pipeline_VITIS_LOOP_389_5_fu_220_grp_scaleCompute_17_42_20_48_16_1_s_fu_195_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        grp_scaleCompute_17_42_20_48_16_1_s_fu_195_currindex = output_rows_count_fu_114;
    end else begin
        grp_scaleCompute_17_42_20_48_16_1_s_fu_195_currindex = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state12))) begin
        grp_scaleCompute_17_42_20_48_16_1_s_fu_195_inscale = grp_resizeNNBilinear_0_2160_3840_1_1080_1920_1_2_Pipeline_VITIS_LOOP_389_5_fu_220_grp_scaleCompute_17_42_20_48_16_1_s_fu_195_p_din2;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        grp_scaleCompute_17_42_20_48_16_1_s_fu_195_inscale = trunc_ln712_1_reg_920;
    end else begin
        grp_scaleCompute_17_42_20_48_16_1_s_fu_195_inscale = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_xfUDivResize_fu_178_in_d = trunc_ln301_reg_895;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        grp_xfUDivResize_fu_178_in_d = trunc_ln300_reg_890;
    end else begin
        grp_xfUDivResize_fu_178_in_d = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_xfUDivResize_fu_178_in_n = ynew_reg_915;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        grp_xfUDivResize_fu_178_in_n = xnew_reg_905;
    end else begin
        grp_xfUDivResize_fu_178_in_n = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        in_mat_420_read = grp_resizeNNBilinear_0_2160_3840_1_1080_1920_1_2_Pipeline_VITIS_LOOP_389_5_fu_220_in_mat_420_read;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        in_mat_420_read = grp_resizeNNBilinear_0_2160_3840_1_1080_1920_1_2_Pipeline_VITIS_LOOP_332_1_VITIS_LOOP_337_2_fu_210_in_mat_420_read;
    end else begin
        in_mat_420_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        line_buffer_V_0_0_address0 = grp_resizeNNBilinear_0_2160_3840_1_1080_1920_1_2_Pipeline_VITIS_LOOP_389_5_fu_220_line_buffer_V_0_0_address0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        line_buffer_V_0_0_address0 = grp_resizeNNBilinear_0_2160_3840_1_1080_1920_1_2_Pipeline_VITIS_LOOP_332_1_VITIS_LOOP_337_2_fu_210_line_buffer_V_0_0_address0;
    end else begin
        line_buffer_V_0_0_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        line_buffer_V_0_0_ce0 = grp_resizeNNBilinear_0_2160_3840_1_1080_1920_1_2_Pipeline_VITIS_LOOP_389_5_fu_220_line_buffer_V_0_0_ce0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        line_buffer_V_0_0_ce0 = grp_resizeNNBilinear_0_2160_3840_1_1080_1920_1_2_Pipeline_VITIS_LOOP_332_1_VITIS_LOOP_337_2_fu_210_line_buffer_V_0_0_ce0;
    end else begin
        line_buffer_V_0_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        line_buffer_V_0_0_ce1 = grp_resizeNNBilinear_0_2160_3840_1_1080_1920_1_2_Pipeline_VITIS_LOOP_389_5_fu_220_line_buffer_V_0_0_ce1;
    end else begin
        line_buffer_V_0_0_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        line_buffer_V_0_0_d0 = grp_resizeNNBilinear_0_2160_3840_1_1080_1920_1_2_Pipeline_VITIS_LOOP_389_5_fu_220_line_buffer_V_0_0_d0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        line_buffer_V_0_0_d0 = grp_resizeNNBilinear_0_2160_3840_1_1080_1920_1_2_Pipeline_VITIS_LOOP_332_1_VITIS_LOOP_337_2_fu_210_line_buffer_V_0_0_d0;
    end else begin
        line_buffer_V_0_0_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        line_buffer_V_0_0_we0 = grp_resizeNNBilinear_0_2160_3840_1_1080_1920_1_2_Pipeline_VITIS_LOOP_389_5_fu_220_line_buffer_V_0_0_we0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        line_buffer_V_0_0_we0 = grp_resizeNNBilinear_0_2160_3840_1_1080_1920_1_2_Pipeline_VITIS_LOOP_332_1_VITIS_LOOP_337_2_fu_210_line_buffer_V_0_0_we0;
    end else begin
        line_buffer_V_0_0_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        line_buffer_V_1_0_address0 = grp_resizeNNBilinear_0_2160_3840_1_1080_1920_1_2_Pipeline_VITIS_LOOP_389_5_fu_220_line_buffer_V_1_0_address0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        line_buffer_V_1_0_address0 = grp_resizeNNBilinear_0_2160_3840_1_1080_1920_1_2_Pipeline_VITIS_LOOP_332_1_VITIS_LOOP_337_2_fu_210_line_buffer_V_1_0_address0;
    end else begin
        line_buffer_V_1_0_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        line_buffer_V_1_0_ce0 = grp_resizeNNBilinear_0_2160_3840_1_1080_1920_1_2_Pipeline_VITIS_LOOP_389_5_fu_220_line_buffer_V_1_0_ce0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        line_buffer_V_1_0_ce0 = grp_resizeNNBilinear_0_2160_3840_1_1080_1920_1_2_Pipeline_VITIS_LOOP_332_1_VITIS_LOOP_337_2_fu_210_line_buffer_V_1_0_ce0;
    end else begin
        line_buffer_V_1_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        line_buffer_V_1_0_ce1 = grp_resizeNNBilinear_0_2160_3840_1_1080_1920_1_2_Pipeline_VITIS_LOOP_389_5_fu_220_line_buffer_V_1_0_ce1;
    end else begin
        line_buffer_V_1_0_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        line_buffer_V_1_0_d0 = grp_resizeNNBilinear_0_2160_3840_1_1080_1920_1_2_Pipeline_VITIS_LOOP_389_5_fu_220_line_buffer_V_1_0_d0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        line_buffer_V_1_0_d0 = grp_resizeNNBilinear_0_2160_3840_1_1080_1920_1_2_Pipeline_VITIS_LOOP_332_1_VITIS_LOOP_337_2_fu_210_line_buffer_V_1_0_d0;
    end else begin
        line_buffer_V_1_0_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        line_buffer_V_1_0_we0 = grp_resizeNNBilinear_0_2160_3840_1_1080_1920_1_2_Pipeline_VITIS_LOOP_389_5_fu_220_line_buffer_V_1_0_we0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        line_buffer_V_1_0_we0 = grp_resizeNNBilinear_0_2160_3840_1_1080_1920_1_2_Pipeline_VITIS_LOOP_332_1_VITIS_LOOP_337_2_fu_210_line_buffer_V_1_0_we0;
    end else begin
        line_buffer_V_1_0_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        out_mat_421_write = grp_resizeNNBilinear_0_2160_3840_1_1080_1920_1_2_Pipeline_VITIS_LOOP_389_5_fu_220_out_mat_421_write;
    end else begin
        out_mat_421_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            if (((1'b0 == ap_block_state3_on_subcall_done) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            if (((grp_xfUDivResize_fu_178_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            if (((icmp_ln382_fu_434_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state5))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            if (((grp_resizeNNBilinear_0_2160_3840_1_1080_1920_1_2_Pipeline_VITIS_LOOP_389_5_fu_220_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state13))) begin
                ap_NS_fsm = ap_ST_fsm_state14;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_i_i_i_i_i199_i_fu_630_p2 = (ret_V_3_cast_reg_996 + 17'd1);

assign add_i_i_i_i_i286_i_fu_561_p2 = (ret_V_cast_fu_543_p4 + 17'd1);

assign add_ln511_fu_676_p2 = (output_rows_count_fu_114 + 32'd1);

assign and_ln1061_fu_733_p2 = (icmp_ln1061_fu_698_p2 & cmp89_reg_1049);

assign and_ln509_fu_660_p2 = (icmp_ln1049_fu_655_p2 & cmp277_reg_1063);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

always @ (*) begin
    ap_block_state3_on_subcall_done = ((grp_resizeNNBilinear_0_2160_3840_1_1080_1920_1_2_Pipeline_VITIS_LOOP_332_1_VITIS_LOOP_337_2_fu_210_ap_done == 1'b0) | (grp_xfUDivResize_fu_178_ap_done == 1'b0));
end

assign ap_ext_blocking_n = (ap_ext_blocking_sub_n & 1'b1);

assign ap_int_blocking_n = (ap_int_blocking_sub_n & 1'b1);

assign ap_str_blocking_n = (ap_str_blocking_sub_n & 1'b1);

assign cmp277_fu_619_p2 = ((read_rows_count_fu_110 == p_read) ? 1'b1 : 1'b0);

assign cmp89_fu_608_p2 = ((read_rows_count_fu_110 != p_read) ? 1'b1 : 1'b0);

assign cmp_i_i235_i_fu_475_p2 = (($signed(conv_i_i255_i_fu_463_p1) > $signed(shl_i_i_i_i233_i_reg_950)) ? 1'b1 : 1'b0);

assign conv_i_i10_i309_i2_cast_fu_376_p1 = conv_i_i10_i309_i2_fu_366_p4;

assign conv_i_i10_i309_i2_fu_366_p4 = {{grp_xfUDivResize_fu_178_ap_return[47:10]}};

assign conv_i_i255_i_fu_463_p0 = grp_scaleCompute_17_42_20_48_16_1_s_fu_195_ap_return;

assign conv_i_i255_i_fu_463_p1 = conv_i_i255_i_fu_463_p0;

assign conv_i_i_i300_i_fu_535_p1 = indexy_pre_comp_V_reg_986;

assign conv_i_i_i322_i_cast_fu_356_p4 = {{grp_xfUDivResize_fu_178_ap_return[31:10]}};

assign empty_57_fu_401_p1 = tmp_V_fu_351_p2[19:0];

assign empty_58_fu_413_p1 = i_op_assign_fu_380_p2[19:0];

assign empty_59_fu_495_p1 = indexy_pre_V_fu_487_p3[21:0];

assign empty_60_fu_517_p1 = indexy_pre_V_fu_487_p3[23:0];

assign first_row_index_2_fu_714_p3 = ((icmp_ln522_fu_708_p2[0:0] == 1'b1) ? 32'd0 : first_row_index_fu_703_p2);

assign first_row_index_3_fu_745_p3 = ((cmp89_reg_1049[0:0] == 1'b1) ? first_row_index_2_fu_714_p3 : first_row_index_1_fu_118);

assign first_row_index_4_fu_751_p3 = ((and_ln1061_fu_733_p2[0:0] == 1'b1) ? first_row_index_1_fu_118 : first_row_index_3_fu_745_p3);

assign first_row_index_fu_703_p2 = (first_row_index_1_fu_118 + 32'd1);

assign grp_resizeNNBilinear_0_2160_3840_1_1080_1920_1_2_Pipeline_VITIS_LOOP_332_1_VITIS_LOOP_337_2_fu_210_ap_start = grp_resizeNNBilinear_0_2160_3840_1_1080_1920_1_2_Pipeline_VITIS_LOOP_332_1_VITIS_LOOP_337_2_fu_210_ap_start_reg;

assign grp_resizeNNBilinear_0_2160_3840_1_1080_1920_1_2_Pipeline_VITIS_LOOP_389_5_fu_220_ap_start = grp_resizeNNBilinear_0_2160_3840_1_1080_1920_1_2_Pipeline_VITIS_LOOP_389_5_fu_220_ap_start_reg;

assign grp_resizeNNBilinear_0_2160_3840_1_1080_1920_1_2_Pipeline_VITIS_LOOP_389_5_fu_220_p_Result_s = tmp_7_reg_1002;

assign grp_xfUDivResize_fu_178_ap_start = grp_xfUDivResize_fu_178_ap_start_reg;

assign i_2_fu_439_p2 = (i_fu_122 + 32'd1);

assign i_op_assign_fu_380_p2 = ($signed(p_read) + $signed(32'd4294967295));

assign icmp_ln1049_1_fu_665_p2 = ((zext_ln1049_fu_651_p1 == op2_assign_2_reg_1069) ? 1'b1 : 1'b0);

assign icmp_ln1049_fu_655_p2 = ((zext_ln1049_fu_651_p1 == op2_assign_reg_1020) ? 1'b1 : 1'b0);

assign icmp_ln1061_1_fu_586_p2 = (($signed(zext_ln1061_1_fu_582_p1) < $signed(op2_assign_fu_529_p2)) ? 1'b1 : 1'b0);

assign icmp_ln1061_fu_698_p2 = (($signed(zext_ln1061_fu_694_p1) < $signed(op2_assign_reg_1020)) ? 1'b1 : 1'b0);

assign icmp_ln354_fu_326_p2 = (($signed(p_read2) > $signed(p_read)) ? 1'b1 : 1'b0);

assign icmp_ln356_fu_336_p2 = (($signed(p_read3) > $signed(p_read1)) ? 1'b1 : 1'b0);

assign icmp_ln382_fu_434_p2 = (($signed(i_fu_122) < $signed(loop_row_count_reg_925)) ? 1'b1 : 1'b0);

assign icmp_ln522_fu_708_p2 = ((first_row_index_fu_703_p2 == 32'd3) ? 1'b1 : 1'b0);

assign icmp_ln902_fu_521_p2 = ((trunc_ln387_fu_459_p1 != sub_ln902_reg_970) ? 1'b1 : 1'b0);

assign indexx_pre_V_1_fu_405_p3 = {{empty_57_fu_401_p1}, {22'd0}};

assign indexy_pre_V_fu_487_p3 = ((tmp_6_fu_467_p3[0:0] == 1'b1) ? 42'd0 : spec_select151_fu_480_p3);

assign loop_col_count_fu_340_p3 = ((icmp_ln356_fu_336_p2[0:0] == 1'b1) ? p_read3 : p_read1);

assign loop_row_count_fu_330_p3 = ((icmp_ln354_fu_326_p2[0:0] == 1'b1) ? p_read2 : p_read);

assign op2_assign_2_fu_624_p2 = ($signed(read_rows_count_fu_110) + $signed(32'd4294967294));

assign op2_assign_fu_529_p2 = ($signed(read_rows_count_fu_110) + $signed(32'd4294967295));

assign or_ln509_fu_670_p2 = (icmp_ln1049_1_fu_665_p2 | and_ln509_fu_660_p2);

assign out_mat_421_din = grp_resizeNNBilinear_0_2160_3840_1_1080_1920_1_2_Pipeline_VITIS_LOOP_389_5_fu_220_out_mat_421_din;

assign output_rows_count_1_fu_688_p3 = ((rev125_reg_1057[0:0] == 1'b1) ? select_ln509_fu_681_p3 : output_rows_count_fu_114);

assign p_Val2_s_fu_538_p2 = ($signed(conv_i_i_i300_i_fu_535_p1) + $signed(conv_i_i10_i309_i2_cast_reg_945));

assign read_rows_count_1_fu_722_p2 = (read_rows_count_fu_110 + 32'd1);

assign read_rows_count_2_fu_738_p3 = ((and_ln1061_fu_733_p2[0:0] == 1'b1) ? read_rows_count_fu_110 : sel_tmp1_fu_727_p3);

assign ret_V_17_fu_574_p3 = ((tmp_5_fu_553_p3[0:0] == 1'b1) ? select_ln901_fu_567_p3 : ret_V_cast_fu_543_p4);

assign ret_V_cast_fu_543_p4 = {{p_Val2_s_fu_538_p2[38:22]}};

assign rev125_fu_613_p2 = (slt_reg_981 ^ 1'd1);

assign sel_tmp1_fu_727_p3 = ((cmp89_reg_1049[0:0] == 1'b1) ? read_rows_count_1_fu_722_p2 : p_read);

assign select_ln509_fu_681_p3 = ((or_ln509_fu_670_p2[0:0] == 1'b1) ? add_ln511_fu_676_p2 : output_rows_count_fu_114);

assign select_ln901_fu_567_p3 = ((icmp_ln902_reg_1012[0:0] == 1'b1) ? add_i_i_i_i_i286_i_fu_561_p2 : ret_V_cast_fu_543_p4);

assign shl_i_i_i216_i_fu_417_p3 = {{empty_58_fu_413_p1}, {22'd0}};

assign shl_i_i_i_i233_i_fu_385_p3 = {{i_op_assign_fu_380_p2}, {22'd0}};

assign shl_i_i_i_i_i_fu_393_p3 = {{tmp_V_fu_351_p2}, {22'd0}};

assign slt_fu_454_p2 = (($signed(sub272_reg_935) < $signed(output_rows_count_fu_114)) ? 1'b1 : 1'b0);

assign spec_select151_fu_480_p2 = grp_scaleCompute_17_42_20_48_16_1_s_fu_195_ap_return;

assign spec_select151_fu_480_p3 = ((cmp_i_i235_i_fu_475_p2[0:0] == 1'b1) ? shl_i_i_i216_i_reg_965 : spec_select151_fu_480_p2);

assign sub272_fu_346_p2 = ($signed(p_read2) + $signed(32'd4294967295));

assign sub_ln902_fu_425_p2 = (22'd0 - conv_i_i_i322_i_cast_fu_356_p4);

assign tmp_5_fu_553_p3 = p_Val2_s_fu_538_p2[32'd42];

assign tmp_6_fu_467_p1 = grp_scaleCompute_17_42_20_48_16_1_s_fu_195_ap_return;

assign tmp_6_fu_467_p3 = tmp_6_fu_467_p1[32'd41];

assign tmp_V_fu_351_p2 = ($signed(p_read1) + $signed(32'd4294967295));

assign tmp_fu_294_p3 = {{p_read1}, {1'd0}};

assign trunc_ln300_fu_256_p1 = p_read3[15:0];

assign trunc_ln301_fu_260_p1 = p_read2[15:0];

assign trunc_ln387_fu_459_p0 = grp_scaleCompute_17_42_20_48_16_1_s_fu_195_ap_return;

assign trunc_ln387_fu_459_p1 = trunc_ln387_fu_459_p0[21:0];

assign trunc_ln712_1_fu_322_p1 = grp_xfUDivResize_fu_178_ap_return[47:0];

assign trunc_ln712_fu_310_p1 = grp_xfUDivResize_fu_178_ap_return[47:0];

assign xnew_fu_302_p3 = {{p_read1}, {32'd0}};

assign xor_ln1061_fu_636_p2 = (icmp_ln1061_1_reg_1032 ^ 1'd1);

assign ynew_fu_314_p3 = {{p_read}, {32'd0}};

assign zext_ln1049_fu_651_p1 = grp_resizeNNBilinear_0_2160_3840_1_1080_1920_1_2_Pipeline_VITIS_LOOP_389_5_fu_220_indexy_V_1_out;

assign zext_ln1061_1_fu_582_p1 = ret_V_17_fu_574_p3;

assign zext_ln1061_fu_694_p1 = grp_resizeNNBilinear_0_2160_3840_1_1080_1920_1_2_Pipeline_VITIS_LOOP_389_5_fu_220_nextYScale_V_1_out;

always @ (posedge ap_clk) begin
    tmp_reg_900[0] <= 1'b0;
    xnew_reg_905[31:0] <= 32'b00000000000000000000000000000000;
    ynew_reg_915[31:0] <= 32'b00000000000000000000000000000000;
    conv_i_i10_i309_i2_cast_reg_945[42:38] <= 5'b00000;
    shl_i_i_i_i233_i_reg_950[21:0] <= 22'b0000000000000000000000;
    shl_i_i_i_i_i_reg_955[21:0] <= 22'b0000000000000000000000;
    indexx_pre_V_1_reg_960[21:0] <= 22'b0000000000000000000000;
    shl_i_i_i216_i_reg_965[21:0] <= 22'b0000000000000000000000;
end

endmodule //resize_accel_resizeNNBilinear_0_2160_3840_1_1080_1920_1_2_s
