// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.1 (64-bit)
// Version: 2021.1
// Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module resize_accel_AxiStream2Mat (
        ldata1_dout,
        ldata1_empty_n,
        ldata1_read,
        in_mat_420_din,
        in_mat_420_full_n,
        in_mat_420_write,
        rows_dout,
        rows_empty_n,
        rows_read,
        cols_dout,
        cols_empty_n,
        cols_read,
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_ready,
        ap_idle,
        ap_continue,
        ap_ext_blocking_n,
        ap_str_blocking_n,
        ap_int_blocking_n
);


input  [127:0] ldata1_dout;
input   ldata1_empty_n;
output   ldata1_read;
output  [7:0] in_mat_420_din;
input   in_mat_420_full_n;
output   in_mat_420_write;
input  [31:0] rows_dout;
input   rows_empty_n;
output   rows_read;
input  [31:0] cols_dout;
input   cols_empty_n;
output   cols_read;
input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_ready;
output   ap_idle;
input   ap_continue;
output   ap_ext_blocking_n;
output   ap_str_blocking_n;
output   ap_int_blocking_n;

wire    last_blk_pxl_width_U0_ap_start;
wire    last_blk_pxl_width_U0_ap_done;
wire    last_blk_pxl_width_U0_ap_continue;
wire    last_blk_pxl_width_U0_ap_idle;
wire    last_blk_pxl_width_U0_ap_ready;
wire   [3:0] last_blk_pxl_width_U0_return_r;
wire    last_blk_pxl_width_U0_ap_ext_blocking_n;
wire    last_blk_pxl_width_U0_ap_str_blocking_n;
wire    last_blk_pxl_width_U0_ap_int_blocking_n;
wire    last_blk_width_channel_full_n;
wire    AxiStream2MatStream_2_U0_ap_start;
wire    AxiStream2MatStream_2_U0_ap_done;
wire    AxiStream2MatStream_2_U0_ap_continue;
wire    AxiStream2MatStream_2_U0_ap_idle;
wire    AxiStream2MatStream_2_U0_ap_ready;
wire    AxiStream2MatStream_2_U0_ldata1_read;
wire   [7:0] AxiStream2MatStream_2_U0_in_mat_420_din;
wire    AxiStream2MatStream_2_U0_in_mat_420_write;
wire    AxiStream2MatStream_2_U0_rows_read;
wire    AxiStream2MatStream_2_U0_cols_bound_per_npc_read;
wire    AxiStream2MatStream_2_U0_ap_ext_blocking_n;
wire    AxiStream2MatStream_2_U0_ap_str_blocking_n;
wire    AxiStream2MatStream_2_U0_ap_int_blocking_n;
wire   [3:0] last_blk_width_channel_dout;
wire    last_blk_width_channel_empty_n;
wire    ap_ext_blocking_cur_n;
wire    ap_str_blocking_cur_n;
wire    ap_int_blocking_cur_n;
wire    ap_ext_blocking_sub_n;
wire    ap_str_blocking_sub_n;
wire    ap_int_blocking_sub_n;

resize_accel_last_blk_pxl_width last_blk_pxl_width_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(last_blk_pxl_width_U0_ap_start),
    .ap_done(last_blk_pxl_width_U0_ap_done),
    .ap_continue(last_blk_pxl_width_U0_ap_continue),
    .ap_idle(last_blk_pxl_width_U0_ap_idle),
    .ap_ready(last_blk_pxl_width_U0_ap_ready),
    .return_r(last_blk_pxl_width_U0_return_r),
    .ap_ext_blocking_n(last_blk_pxl_width_U0_ap_ext_blocking_n),
    .ap_str_blocking_n(last_blk_pxl_width_U0_ap_str_blocking_n),
    .ap_int_blocking_n(last_blk_pxl_width_U0_ap_int_blocking_n)
);

resize_accel_AxiStream2MatStream_2_s AxiStream2MatStream_2_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(AxiStream2MatStream_2_U0_ap_start),
    .ap_done(AxiStream2MatStream_2_U0_ap_done),
    .ap_continue(AxiStream2MatStream_2_U0_ap_continue),
    .ap_idle(AxiStream2MatStream_2_U0_ap_idle),
    .ap_ready(AxiStream2MatStream_2_U0_ap_ready),
    .ldata1_dout(ldata1_dout),
    .ldata1_empty_n(ldata1_empty_n),
    .ldata1_read(AxiStream2MatStream_2_U0_ldata1_read),
    .in_mat_420_din(AxiStream2MatStream_2_U0_in_mat_420_din),
    .in_mat_420_full_n(in_mat_420_full_n),
    .in_mat_420_write(AxiStream2MatStream_2_U0_in_mat_420_write),
    .rows_dout(rows_dout),
    .rows_empty_n(rows_empty_n),
    .rows_read(AxiStream2MatStream_2_U0_rows_read),
    .cols_bound_per_npc_dout(cols_dout),
    .cols_bound_per_npc_empty_n(cols_empty_n),
    .cols_bound_per_npc_read(AxiStream2MatStream_2_U0_cols_bound_per_npc_read),
    .last_blk_width(last_blk_width_channel_dout),
    .ap_ext_blocking_n(AxiStream2MatStream_2_U0_ap_ext_blocking_n),
    .ap_str_blocking_n(AxiStream2MatStream_2_U0_ap_str_blocking_n),
    .ap_int_blocking_n(AxiStream2MatStream_2_U0_ap_int_blocking_n)
);

resize_accel_fifo_w4_d2_S last_blk_width_channel_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(last_blk_pxl_width_U0_return_r),
    .if_full_n(last_blk_width_channel_full_n),
    .if_write(last_blk_pxl_width_U0_ap_done),
    .if_dout(last_blk_width_channel_dout),
    .if_empty_n(last_blk_width_channel_empty_n),
    .if_read(AxiStream2MatStream_2_U0_ap_ready)
);

assign AxiStream2MatStream_2_U0_ap_continue = ap_continue;

assign AxiStream2MatStream_2_U0_ap_start = last_blk_width_channel_empty_n;

assign ap_done = AxiStream2MatStream_2_U0_ap_done;

assign ap_ext_blocking_cur_n = 1'b1;

assign ap_ext_blocking_n = (ap_ext_blocking_sub_n & ap_ext_blocking_cur_n);

assign ap_ext_blocking_sub_n = (last_blk_pxl_width_U0_ap_ext_blocking_n & AxiStream2MatStream_2_U0_ap_ext_blocking_n);

assign ap_idle = (last_blk_pxl_width_U0_ap_idle & (last_blk_width_channel_empty_n ^ 1'b1) & AxiStream2MatStream_2_U0_ap_idle);

assign ap_int_blocking_cur_n = 1'b1;

assign ap_int_blocking_n = (ap_int_blocking_sub_n & ap_int_blocking_cur_n);

assign ap_int_blocking_sub_n = (last_blk_pxl_width_U0_ap_int_blocking_n & AxiStream2MatStream_2_U0_ap_int_blocking_n);

assign ap_ready = last_blk_pxl_width_U0_ap_ready;

assign ap_str_blocking_cur_n = 1'b1;

assign ap_str_blocking_n = (ap_str_blocking_sub_n & ap_str_blocking_cur_n);

assign ap_str_blocking_sub_n = (last_blk_pxl_width_U0_ap_str_blocking_n & AxiStream2MatStream_2_U0_ap_str_blocking_n);

assign cols_read = AxiStream2MatStream_2_U0_cols_bound_per_npc_read;

assign in_mat_420_din = AxiStream2MatStream_2_U0_in_mat_420_din;

assign in_mat_420_write = AxiStream2MatStream_2_U0_in_mat_420_write;

assign last_blk_pxl_width_U0_ap_continue = last_blk_width_channel_full_n;

assign last_blk_pxl_width_U0_ap_start = ap_start;

assign ldata1_read = AxiStream2MatStream_2_U0_ldata1_read;

assign rows_read = AxiStream2MatStream_2_U0_rows_read;

endmodule //resize_accel_AxiStream2Mat
